var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// ../dist/route-manifest.json
var route_manifest_default = {
  generatedAt: "2026-08-12T01:42:04.945Z",
  source: "scripts/lib/route-manifest.mjs (derivado \u2014 n\xE3o editar \xE0 m\xE3o)",
  counts: {
    validExact: 1052,
    validPatterns: 11,
    redirects: 38,
    prerendered: 317,
    dynamicSlugs: 404,
    curated: 56,
    assetFiles: 711,
    private: 13
  },
  validExact: [
    "/",
    "/admin",
    "/admin/auditoria-os",
    "/admin/casos",
    "/admin/conversao",
    "/admin/dashboard",
    "/admin/funnel",
    "/admin/login",
    "/admin/operacao",
    "/admin/provas-monitor",
    "/admin/provas-verticais",
    "/admin/reviews",
    "/admin/vitals",
    "/ads/tecnico-informatica-curitiba",
    "/anuncie",
    "/areas-atendidas",
    "/arrumar-pc",
    "/arrumar-pc/belem",
    "/arrumar-pc/belo-horizonte",
    "/arrumar-pc/brasilia",
    "/arrumar-pc/campinas",
    "/arrumar-pc/campo-grande",
    "/arrumar-pc/cuiaba",
    "/arrumar-pc/curitiba-nacional",
    "/arrumar-pc/florianopolis",
    "/arrumar-pc/fortaleza",
    "/arrumar-pc/goiania",
    "/arrumar-pc/joao-pessoa",
    "/arrumar-pc/maceio",
    "/arrumar-pc/manaus",
    "/arrumar-pc/natal",
    "/arrumar-pc/online",
    "/arrumar-pc/porto-alegre",
    "/arrumar-pc/recife",
    "/arrumar-pc/rio-de-janeiro",
    "/arrumar-pc/salvador",
    "/arrumar-pc/sao-paulo",
    "/arrumar-pc/vitoria",
    "/assistencia-eletrodomesticos-inteligentes-curitiba",
    "/assistencia-tecnica-curitiba",
    "/atendimento-domicilio",
    "/atendimento-remoto",
    "/avaliar",
    "/bairros/academia-sjp",
    "/bairros/afonso-pena",
    "/bairros/agricola-sjp",
    "/bairros/agua-verde",
    "/bairros/alto-boqueirao",
    "/bairros/alto-da-gloria",
    "/bairros/alto-maracana",
    "/bairros/alto-taruma",
    "/bairros/antonio-olivero-cm",
    "/bairros/aristocrata",
    "/bairros/atuba-colombo",
    "/bairros/atuba-pinhais",
    "/bairros/aviacao",
    "/bairros/bacacheri",
    "/bairros/barigui-araucaria",
    "/bairros/barro-preto",
    "/bairros/bateias",
    "/bairros/batel",
    "/bairros/bigorrilho",
    "/bairros/boa-vista",
    "/bairros/boa-vista-at",
    "/bairros/boneca-do-iguacu-sjp",
    "/bairros/boqueirao",
    "/bairros/boqueirao-araucaria",
    "/bairros/borda-campo-sjp",
    "/bairros/borda-do-campo-qb",
    "/bairros/borda-do-campo-sjp",
    "/bairros/botiatuva",
    "/bairros/botiatuva-cm",
    "/bairros/braga",
    "/bairros/cabral",
    "/bairros/cachoeira-araucaria",
    "/bairros/cachoeira-at",
    "/bairros/caiua-piraquara",
    "/bairros/cajuru",
    "/bairros/california-araucaria",
    "/bairros/campina-da-barra",
    "/bairros/campina-grande-colombo",
    "/bairros/campo-comprido",
    "/bairros/campo-largo-roseira-sjp",
    "/bairros/campo-pequeno",
    "/bairros/campo-tenente-at",
    "/bairros/capao-da-imbuia",
    "/bairros/capela-velha",
    "/bairros/centro",
    "/bairros/centro-almirante-tamandare",
    "/bairros/centro-araucaria",
    "/bairros/centro-campo-largo",
    "/bairros/centro-campo-magro",
    "/bairros/centro-colombo",
    "/bairros/centro-fazenda-rio-grande",
    "/bairros/centro-pinhais",
    "/bairros/centro-piraquara",
    "/bairros/centro-quatro-barras",
    "/bairros/chapada",
    "/bairros/cic",
    "/bairros/cidade-jardim-sjp",
    "/bairros/colonia-antonio-prado",
    "/bairros/colonia-malhada-cl",
    "/bairros/colonia-murici-sjp",
    "/bairros/correia-de-freitas",
    "/bairros/costeira",
    "/bairros/costeira-araucaria",
    "/bairros/cristo-rei",
    "/bairros/cruzeiro",
    "/bairros/del-rey",
    "/bairros/embu-colombo",
    "/bairros/emiliano-perneta",
    "/bairros/espigao-alegre-cm",
    "/bairros/estacao-araucaria",
    "/bairros/estancia-pinhais",
    "/bairros/eucaliptos-frg",
    "/bairros/fatima-colombo",
    "/bairros/fazenda-velha-araucaria",
    "/bairros/fazendinha",
    "/bairros/ferraria",
    "/bairros/gabirobal",
    "/bairros/graciosa",
    "/bairros/graciosa-qb",
    "/bairros/gralha-azul",
    "/bairros/guajuvira",
    "/bairros/guaraituba-colombo",
    "/bairros/guarituba-piraquara",
    "/bairros/guatupe",
    "/bairros/hauer",
    "/bairros/hortencia-frg",
    "/bairros/hugo-lange",
    "/bairros/iguacu-araucaria",
    "/bairros/iguacu-frg",
    "/bairros/independencia-sjp",
    "/bairros/industrial-araucaria",
    "/bairros/ipe-sjp",
    "/bairros/irai-piraquara",
    "/bairros/italia-sjp",
    "/bairros/itaqui",
    "/bairros/jardim-amelia",
    "/bairros/jardim-america-campo-largo",
    "/bairros/jardim-bela-vista-piraquara",
    "/bairros/jardim-boa-vista-araucaria",
    "/bairros/jardim-boa-vista-cm",
    "/bairros/jardim-botanico",
    "/bairros/jardim-claudia",
    "/bairros/jardim-claudia-ii-pinhais",
    "/bairros/jardim-condor-frg",
    "/bairros/jardim-das-americas",
    "/bairros/jardim-das-pedras-frg",
    "/bairros/jardim-dona-rosa-pinhais",
    "/bairros/jardim-esperanca-cl",
    "/bairros/jardim-esplanada-pinhais",
    "/bairros/jardim-estados",
    "/bairros/jardim-florestal-qb",
    "/bairros/jardim-graziela",
    "/bairros/jardim-guilhermina",
    "/bairros/jardim-iguacu-araucaria",
    "/bairros/jardim-ipe-frg",
    "/bairros/jardim-japao-qb",
    "/bairros/jardim-karla-pinhais",
    "/bairros/jardim-laranjeiras-cl",
    "/bairros/jardim-menino-deus-qb",
    "/bairros/jardim-monte-santo",
    "/bairros/jardim-novo-horizonte-cl",
    "/bairros/jardim-osasco",
    "/bairros/jardim-paraiso-at",
    "/bairros/jardim-paranagua-at",
    "/bairros/jardim-pedro-demeterco",
    "/bairros/jardim-planalto-campo-largo",
    "/bairros/jardim-planalto-ii-cl",
    "/bairros/jardim-primavera-piraquara",
    "/bairros/jardim-roma",
    "/bairros/jardim-santo-antonio-piraquara",
    "/bairros/jardim-sao-jorge-at",
    "/bairros/jardim-sao-paulo-piraquara",
    "/bairros/jardim-shangrila-araucaria",
    "/bairros/jardim-social",
    "/bairros/jardim-tropical-pinhais",
    "/bairros/jardim-uniao-piraquara",
    "/bairros/jardim-wissinger-pinhais",
    "/bairros/joquei-clube-cm",
    "/bairros/juveve",
    "/bairros/lamenha-grande-cl",
    "/bairros/maracana-colombo",
    "/bairros/maria-antonieta",
    "/bairros/merces",
    "/bairros/monza-colombo",
    "/bairros/nacoes-frg",
    "/bairros/novo-mundo",
    "/bairros/osvaldo-cruz-colombo",
    "/bairros/ouro-fino",
    "/bairros/ouro-fino-sjp",
    "/bairros/palmital-campo-largo",
    "/bairros/palmital-colombo",
    "/bairros/palmital-pinhais",
    "/bairros/parque-da-fonte",
    "/bairros/parque-industrial-frg",
    "/bairros/parque-nascentes-pinhais",
    "/bairros/passauna",
    "/bairros/pedro-moro-sjp",
    "/bairros/pineville",
    "/bairros/pinheirinho",
    "/bairros/pioneiros-frg",
    "/bairros/planta-deodoro-piraquara",
    "/bairros/planta-sao-tiago-araucaria",
    "/bairros/portao",
    "/bairros/porto-das-laranjeiras",
    "/bairros/prado-velho-piraquara",
    "/bairros/quississana-sjp",
    "/bairros/reboucas",
    "/bairros/rio-pequeno-sjp",
    "/bairros/rio-verde-cm",
    "/bairros/roca-grande",
    "/bairros/rondinha",
    "/bairros/sabia",
    "/bairros/santa-cruz-campo-largo",
    "/bairros/santa-felicidade",
    "/bairros/santa-terezinha-colombo",
    "/bairros/santa-terezinha-frg",
    "/bairros/sao-cristao-piraquara",
    "/bairros/sao-cristovao",
    "/bairros/sao-dimas-colombo",
    "/bairros/sao-domingos",
    "/bairros/sao-francisco",
    "/bairros/sao-gabriel-colombo",
    "/bairros/sao-jose-campo-largo",
    "/bairros/sao-jose-dos-pinhais",
    "/bairros/sao-lourenco-frg",
    "/bairros/sao-lourenco-qb",
    "/bairros/sao-marcos",
    "/bairros/sao-marcos-campo-largo",
    "/bairros/sao-miguel-araucaria",
    "/bairros/sao-sebastiao-cm",
    "/bairros/sao-silvestre",
    "/bairros/sao-venancio",
    "/bairros/sede-campo-magro",
    "/bairros/seminario",
    "/bairros/sete-vilas",
    "/bairros/sitio-cercado",
    "/bairros/tangua-at",
    "/bairros/taruma",
    "/bairros/taxiqueira-colombo",
    "/bairros/thomaz-coelho",
    "/bairros/thomaz-coelho-ii",
    "/bairros/timbotuva-cl",
    "/bairros/tindiquera",
    "/bairros/tingui",
    "/bairros/tranqueira-at",
    "/bairros/tres-corregos",
    "/bairros/uberaba",
    "/bairros/vale-das-aguas",
    "/bairros/vargem-grande",
    "/bairros/vila-amelia-pinhais",
    "/bairros/vila-candida-cl",
    "/bairros/vila-izabel",
    "/bairros/vila-macedo-piraquara",
    "/bairros/vila-maria-antonieta-pinhais",
    "/bairros/vila-maria-qb",
    "/bairros/vila-nova-araucaria",
    "/bairros/vila-sao-jose-qb",
    "/bairros/vila-solene",
    "/bairros/vila-taruma",
    "/bairros/weissopolis",
    "/bairros/xaxim",
    "/blog",
    "/blog/automatizar-tarefas-com-ia-n8n-make",
    "/blog/backup-como-proteger-seus-arquivos",
    "/blog/backup-nuvem-empresas-qual-escolher",
    "/blog/comandos-linux-essenciais-iniciantes",
    "/blog/como-atualizar-windows-corretamente",
    "/blog/como-aumentar-velocidade-internet",
    "/blog/como-bloquear-acesso-internet-criancas",
    "/blog/como-bloquear-numero-celular",
    "/blog/como-cadastrar-preciso-de-um",
    "/blog/como-clonar-hd-para-ssd",
    "/blog/como-clonar-hd-para-ssd-passo-a-passo",
    "/blog/como-conectar-celular-tv",
    "/blog/como-conectar-wifi-tv-nao-conecta",
    "/blog/como-configurar-2fa-em-tudo",
    "/blog/como-configurar-active-directory",
    "/blog/como-configurar-backup-automatizado",
    "/blog/como-configurar-bios-uefi-corretamente",
    "/blog/como-configurar-cron-jobs-linux",
    "/blog/como-configurar-firewall-pfsense",
    "/blog/como-configurar-firewall-ufw-linux",
    "/blog/como-configurar-rede-linux-netplan",
    "/blog/como-configurar-rede-wifi-empresarial",
    "/blog/como-configurar-repetidor-wifi",
    "/blog/como-configurar-roteador-wifi-iniciantes",
    "/blog/como-configurar-servidor-de-arquivos",
    "/blog/como-configurar-servidor-web-apache-nginx-linux",
    "/blog/como-configurar-ssh-seguro-linux",
    "/blog/como-configurar-vlan-rede-corporativa",
    "/blog/como-configurar-vpn-empresarial",
    "/blog/como-criar-conta-usuario-windows-criancas",
    "/blog/como-criar-imagens-com-stable-diffusion",
    "/blog/como-criar-prompts-eficazes-chatgpt",
    "/blog/como-criar-script-bash-iniciantes",
    "/blog/como-crimpar-cabo-de-rede-rj45",
    "/blog/como-deixar-celular-android-mais-rapido",
    "/blog/como-deixar-computador-mais-rapido",
    "/blog/como-deixar-windows-11-mais-rapido-iniciantes",
    "/blog/como-detectar-invasao-rede",
    "/blog/como-diagnosticar-placa-mae-defeituosa",
    "/blog/como-economizar-bateria-celular",
    "/blog/como-escolher-melhor-kit-cameras-seguranca",
    "/blog/como-escolher-um-bom-antivirus",
    "/blog/como-escolher-uma-workstation",
    "/blog/como-fazer-backup-celular-android",
    "/blog/como-fazer-backup-completo-windows-11",
    "/blog/como-fazer-backup-fotos-windows-iniciantes",
    "/blog/como-fazer-backup-na-nuvem",
    "/blog/como-fazer-manutencao-impressora",
    "/blog/como-fazer-manutencao-nobreak",
    "/blog/como-fazer-overclock-cpu-com-seguranca",
    "/blog/como-fazer-pentest-basico-rede",
    "/blog/como-fazer-print-tela-celular",
    "/blog/como-fazer-teste-velocidade-internet",
    "/blog/como-fazer-upgrade-ssd-nvme",
    "/blog/como-formatar-pc-sem-perder-arquivos",
    "/blog/como-gerenciar-pacotes-apt-dnf-linux",
    "/blog/como-imprimir-pdf-windows",
    "/blog/como-instalar-aplicativos-celular-com-seguranca",
    "/blog/como-instalar-impressora-windows-passo-a-passo",
    "/blog/como-instalar-lamp-stack-ubuntu",
    "/blog/como-instalar-linux-dual-boot-windows",
    "/blog/como-instalar-postgresql-linux",
    "/blog/como-instalar-segundo-ssd-notebook",
    "/blog/como-instalar-ubuntu-do-zero",
    "/blog/como-instalar-windows-11-do-zero",
    "/blog/como-instalar-windows-11-do-zero-2026",
    "/blog/como-instalar-windows-11-pc-antigo",
    "/blog/como-limpar-notebook-por-dentro",
    "/blog/como-melhorar-sinal-wifi-em-casa",
    "/blog/como-monitorar-servidor-linux",
    "/blog/como-montar-pc-do-zero-guia-completo",
    "/blog/como-montar-pc-gamer-2026",
    "/blog/como-montar-rack-de-rede",
    "/blog/como-mudar-nome-rede-wifi",
    "/blog/como-organizar-arquivos-windows-iniciantes",
    "/blog/como-proteger-computador-golpes-internet",
    "/blog/como-proteger-rede-wifi-empresa",
    "/blog/como-recuperar-arquivos-apagados",
    "/blog/como-recuperar-arquivos-apagados-windows",
    "/blog/como-recuperar-conta-google-bloqueada",
    "/blog/como-recuperar-conta-hackeada",
    "/blog/como-recuperar-dados-hd-com-defeito",
    "/blog/como-recuperar-dados-hd-defeituoso",
    "/blog/como-remover-virus-sem-formatar",
    "/blog/como-remover-virus-windows-iniciantes",
    "/blog/como-resetar-senha-windows",
    "/blog/como-resolver-tela-azul-windows",
    "/blog/como-rodar-ia-localmente-no-pc",
    "/blog/como-saber-quem-esta-usando-meu-wifi",
    "/blog/como-saber-se-pc-tem-virus",
    "/blog/como-saber-se-pc-tem-virus-malware",
    "/blog/como-testar-fonte-de-alimentacao-pc",
    "/blog/como-transferir-dados-celular-novo",
    "/blog/como-treinar-ia-customizada-fine-tuning",
    "/blog/como-trocar-papel-de-parede-tela-bloqueio-windows",
    "/blog/como-trocar-pasta-termica",
    "/blog/como-trocar-pasta-termica-notebook",
    "/blog/como-trocar-senha-wifi",
    "/blog/como-trocar-tela-notebook-passo-a-passo",
    "/blog/como-usar-docker-linux-guia-completo",
    "/blog/como-usar-google-fotos-iniciantes",
    "/blog/como-usar-ia-no-dia-a-dia-dicas-praticas",
    "/blog/como-usar-rede-wifi-para-visitas",
    "/blog/como-usar-rsync-backup-linux",
    "/blog/como-usar-systemd-linux",
    "/blog/computador-lento-causas-solucoes",
    "/blog/configurar-email-outlook-office-365",
    "/blog/diagnostico-tecnico-por-que-e-pago",
    "/blog/dicas-manter-notebook-funcionando-bem",
    "/blog/diferenca-camera-wifi-dvr-qual-escolher",
    "/blog/diferenca-llm-machine-learning-deep-learning",
    "/blog/diferenca-windows-10-vs-11",
    "/blog/distribuicoes-linux-qual-melhor-para-voce",
    "/blog/equipe-especializada-cftv-litoral-parana",
    "/blog/erros-comuns-upgrade-computador",
    "/blog/ia-para-criacao-conteudo-profissional",
    "/blog/ia-para-pequenas-empresas-como-comecar",
    "/blog/ia-substituir-empregos-mitos-verdades",
    "/blog/impressora-nao-imprime-solucoes",
    "/blog/inteligencia-artificial-evolucao-historia",
    "/blog/linux-para-pc-antigo-leve-rapido",
    "/blog/linux-vs-windows-diferencas-qual-escolher",
    "/blog/manutencao-preventiva-computador-guia",
    "/blog/melhores-antivirus-2026-comparativo",
    "/blog/melhores-antivirus-gratuitos-2026",
    "/blog/melhores-ferramentas-ia-gratuitas-2026",
    "/blog/melhores-ias-para-programacao-2026",
    "/blog/monitoramento-24-horas-como-funciona",
    "/blog/notebook-nao-liga-o-que-fazer",
    "/blog/notebook-superaquecendo-o-que-fazer",
    "/blog/notebook-superaquecendo-solucoes",
    "/blog/office-365-guia-completo-empresas",
    "/blog/office-365-vs-office-tradicional",
    "/blog/organizacao-de-ti-para-pequenos-escritorios",
    "/blog/pc-muito-lento-como-acelerar",
    "/blog/pc-nao-liga-o-que-fazer",
    "/blog/phishing-como-identificar-golpes",
    "/blog/por-que-todo-prestador-deve-estar-preciso-de-um",
    "/blog/preciso-de-um-para-eletricistas",
    "/blog/preciso-de-um-para-pintores-pedreiros",
    "/blog/preciso-de-um-para-tecnicos-informatica",
    "/blog/preciso-de-um-plataforma-prestadores",
    "/blog/preciso-de-um-todos-os-ramos",
    "/blog/preciso-de-um-vagas-oportunidades",
    "/blog/quando-trocar-computador-ou-reparar",
    "/blog/quando-trocar-hd-por-ssd",
    "/blog/ransomware-como-proteger-empresa",
    "/blog/seguranca-casas-praia-itapoa-guaratuba",
    "/blog/seguranca-digital-empresas-guia-2024",
    "/blog/sinais-computador-com-virus",
    "/blog/ssd-vs-hd-vale-a-pena-upgrade",
    "/blog/tela-azul-windows-como-resolver",
    "/blog/trocar-windows-por-linux-vale-a-pena",
    "/blog/wifi-caindo-toda-hora",
    "/blog/wifi-lento-como-melhorar",
    "/blog/windows-11-atualizacao-kb5074105-novidades",
    "/blog/windows-11-lento-como-resolver",
    "/blog/windows-11-vale-a-pena-atualizar",
    "/blog/windows-nao-atualiza-erros",
    "/cftv",
    "/cftv/araucaria",
    "/cftv/campo-largo",
    "/cftv/curitiba",
    "/cftv/guaratuba",
    "/cftv/litoral",
    "/cftv/pinhais",
    "/cftv/sao-jose-dos-pinhais",
    "/coleta-e-entrega",
    "/coleta-formulario",
    "/como-avaliar",
    "/como-funciona",
    "/conserto-celular-curitiba",
    "/conserto-celular/agua-verde",
    "/conserto-celular/almirante-tamandare",
    "/conserto-celular/araucaria",
    "/conserto-celular/batel",
    "/conserto-celular/boqueirao",
    "/conserto-celular/cajuru",
    "/conserto-celular/campo-largo",
    "/conserto-celular/campo-magro",
    "/conserto-celular/centro",
    "/conserto-celular/cic",
    "/conserto-celular/colombo",
    "/conserto-celular/curitiba",
    "/conserto-celular/fazenda-rio-grande",
    "/conserto-celular/pinhais",
    "/conserto-celular/piraquara",
    "/conserto-celular/portao",
    "/conserto-celular/quatro-barras",
    "/conserto-celular/santa-felicidade",
    "/conserto-celular/sao-jose-dos-pinhais",
    "/conserto-impressora-curitiba",
    "/conserto-som-curitiba",
    "/conserto-som/agua-verde",
    "/conserto-som/almirante-tamandare",
    "/conserto-som/araucaria",
    "/conserto-som/batel",
    "/conserto-som/boqueirao",
    "/conserto-som/cajuru",
    "/conserto-som/campo-largo",
    "/conserto-som/campo-magro",
    "/conserto-som/centro",
    "/conserto-som/cic",
    "/conserto-som/colombo",
    "/conserto-som/curitiba",
    "/conserto-som/fazenda-rio-grande",
    "/conserto-som/pinhais",
    "/conserto-som/piraquara",
    "/conserto-som/portao",
    "/conserto-som/quatro-barras",
    "/conserto-som/santa-felicidade",
    "/conserto-som/sao-jose-dos-pinhais",
    "/conserto-tv-curitiba",
    "/conserto-tv/agua-verde",
    "/conserto-tv/almirante-tamandare",
    "/conserto-tv/araucaria",
    "/conserto-tv/batel",
    "/conserto-tv/boqueirao",
    "/conserto-tv/cajuru",
    "/conserto-tv/campo-largo",
    "/conserto-tv/campo-magro",
    "/conserto-tv/centro",
    "/conserto-tv/cic",
    "/conserto-tv/colombo",
    "/conserto-tv/curitiba",
    "/conserto-tv/fazenda-rio-grande",
    "/conserto-tv/pinhais",
    "/conserto-tv/piraquara",
    "/conserto-tv/portao",
    "/conserto-tv/quatro-barras",
    "/conserto-tv/santa-felicidade",
    "/conserto-tv/sao-jose-dos-pinhais",
    "/conserto-videogame-curitiba",
    "/conserto-videogame/agua-verde",
    "/conserto-videogame/almirante-tamandare",
    "/conserto-videogame/araucaria",
    "/conserto-videogame/batel",
    "/conserto-videogame/boqueirao",
    "/conserto-videogame/cajuru",
    "/conserto-videogame/campo-largo",
    "/conserto-videogame/campo-magro",
    "/conserto-videogame/centro",
    "/conserto-videogame/cic",
    "/conserto-videogame/colombo",
    "/conserto-videogame/curitiba",
    "/conserto-videogame/fazenda-rio-grande",
    "/conserto-videogame/pinhais",
    "/conserto-videogame/piraquara",
    "/conserto-videogame/portao",
    "/conserto-videogame/quatro-barras",
    "/conserto-videogame/santa-felicidade",
    "/conserto-videogame/sao-jose-dos-pinhais",
    "/contato",
    "/debug/telemetria",
    "/depoimentos",
    "/diagnostico-60s",
    "/diagnostico-tecnico",
    "/empresa-de-ti-curitiba",
    "/equipamentos-atendidos",
    "/excluir-meus-dados",
    "/faq",
    "/funil-indisponivel",
    "/gestor-responsavel",
    "/guia-tecnico-informatica",
    "/index",
    "/marcas",
    "/marcas/acer",
    "/marcas/amd",
    "/marcas/apple",
    "/marcas/asus",
    "/marcas/corsair",
    "/marcas/dell",
    "/marcas/gigabyte",
    "/marcas/hp",
    "/marcas/intel",
    "/marcas/intelbras",
    "/marcas/kingston",
    "/marcas/lenovo",
    "/marcas/lg",
    "/marcas/logitech",
    "/marcas/microsoft",
    "/marcas/motorola",
    "/marcas/msi",
    "/marcas/nvidia",
    "/marcas/positivo",
    "/marcas/razer",
    "/marcas/samsung",
    "/marcas/seagate",
    "/marcas/sony",
    "/marcas/tp-link",
    "/marcas/western-digital",
    "/marcas/xiaomi",
    "/obrigado",
    "/ordem-de-servico",
    "/patrocinadores",
    "/politica-de-cookies-e-anuncios",
    "/politica-de-pecas-do-cliente",
    "/politica-de-privacidade",
    "/precos-e-politicas",
    "/problemas-reais-e-casos",
    "/problemas/alto-falante-queimado-curitiba",
    "/problemas/amplificador-nao-liga-curitiba",
    "/problemas/assistencia-tecnica-urgente-curitiba",
    "/problemas/backup-perdido-curitiba",
    "/problemas/cabo-rede-nao-funciona-curitiba",
    "/problemas/caixa-som-nao-carrega-curitiba",
    "/problemas/caixa-som-sem-audio-curitiba",
    "/problemas/caixa-som-sem-bluetooth-curitiba",
    "/problemas/camera-seguranca-nao-funciona-curitiba",
    "/problemas/celular-bateria-inchada-curitiba",
    "/problemas/celular-camera-nao-funciona-curitiba",
    "/problemas/celular-com-virus-curitiba",
    "/problemas/celular-lento-curitiba",
    "/problemas/celular-listras-na-tela-curitiba",
    "/problemas/celular-molhou-curitiba",
    "/problemas/celular-nao-carrega-curitiba",
    "/problemas/celular-nao-liga-curitiba",
    "/problemas/celular-sem-sinal-curitiba",
    "/problemas/celular-tela-quebrada-curitiba",
    "/problemas/celular-touch-nao-funciona-curitiba",
    "/problemas/computador-com-cheiro-de-queimado-curitiba",
    "/problemas/computador-com-som-estranho-curitiba",
    "/problemas/computador-com-tela-preta-curitiba",
    "/problemas/computador-com-virus-curitiba",
    "/problemas/computador-desligando-apos-segundos-curitiba",
    "/problemas/computador-lento",
    "/problemas/computador-lento-curitiba",
    "/problemas/computador-liga-e-desliga-curitiba",
    "/problemas/computador-muito-barulhento-curitiba",
    "/problemas/computador-nao-conecta-bluetooth-curitiba",
    "/problemas/computador-nao-desliga-curitiba",
    "/problemas/computador-nao-liga-curitiba",
    "/problemas/computador-nao-reconhece-usb-curitiba",
    "/problemas/computador-reiniciando-sozinho-curitiba",
    "/problemas/computador-sem-video-curitiba",
    "/problemas/computador-sem-wifi-curitiba",
    "/problemas/computador-travando-curitiba",
    "/problemas/conserto-computador-domicilio-curitiba",
    "/problemas/curto-em-placa-eletronica",
    "/problemas/custo-reparo-vs-novo",
    "/problemas/erro-0x0000007b-curitiba",
    "/problemas/erro-0x80004005-curitiba",
    "/problemas/erro-0x80070005-curitiba",
    "/problemas/erro-0x80070057-curitiba",
    "/problemas/erro-0x800f081f-curitiba",
    "/problemas/erro-0x80240034-curitiba",
    "/problemas/erro-0xc00000e-curitiba",
    "/problemas/erro-0xc000021a-curitiba",
    "/problemas/erro-ao-instalar-memoria-ram",
    "/problemas/erro-ao-instalar-windows-curitiba",
    "/problemas/erro-apos-formatacao",
    "/problemas/erro-atualizacao-windows-11-curitiba",
    "/problemas/erro-bios-curitiba",
    "/problemas/erro-disco-100-porcento-curitiba",
    "/problemas/erro-disco-cheio-curitiba",
    "/problemas/erro-driver-windows-curitiba",
    "/problemas/erro-particao-windows-curitiba",
    "/problemas/erro-registro-windows-curitiba",
    "/problemas/erro-windows-update-curitiba",
    "/problemas/erros-comuns-em-upgrade",
    "/problemas/fonte-queimada-curitiba",
    "/problemas/formatacao-resolve-curitiba",
    "/problemas/gpu-desgastada",
    "/problemas/hd-externo-nao-reconhece-curitiba",
    "/problemas/hd-fazendo-barulho-curitiba",
    "/problemas/impressora-cartucho-nao-reconhece-curitiba",
    "/problemas/impressora-erro-conexao-usb-wifi-curitiba",
    "/problemas/impressora-nao-imprime-curitiba",
    "/problemas/impressora-papel-preso-curitiba",
    "/problemas/impressora-tinta-nao-sai-curitiba",
    "/problemas/internet-lenta-curitiba",
    "/problemas/listras-tela-celular-apos-atualizacao-curitiba",
    "/problemas/manutencao-notebook-curitiba-rapido",
    "/problemas/memoria-ram-com-defeito-curitiba",
    "/problemas/microsoldagem-celular-curitiba",
    "/problemas/monitor-piscando-curitiba",
    "/problemas/monitor-sem-sinal-curitiba",
    "/problemas/mouse-nao-funciona-curitiba",
    "/problemas/notebook-apos-upgrade-nao-liga-curitiba",
    "/problemas/notebook-bateria-nao-carrega-curitiba",
    "/problemas/notebook-com-agua-ou-liquido-curitiba",
    "/problemas/notebook-com-tela-piscando-curitiba",
    "/problemas/notebook-com-tela-quebrada-curitiba",
    "/problemas/notebook-desliga-sozinho-curitiba",
    "/problemas/notebook-desligando-sozinho-curitiba",
    "/problemas/notebook-esquentando-curitiba",
    "/problemas/notebook-esquentando-desligando-curitiba",
    "/problemas/notebook-esquentando-muito-curitiba",
    "/problemas/notebook-lento-curitiba",
    "/problemas/notebook-nao-carrega-bateria-curitiba",
    "/problemas/notebook-nao-carrega-curitiba",
    "/problemas/notebook-nao-conecta-bluetooth-curitiba",
    "/problemas/notebook-nao-liga",
    "/problemas/notebook-nao-liga-curitiba",
    "/problemas/notebook-sem-audio-curitiba",
    "/problemas/notebook-sem-imagem-curitiba",
    "/problemas/notebook-sem-som-curitiba",
    "/problemas/notebook-sem-webcam-curitiba",
    "/problemas/notebook-sem-wifi-curitiba",
    "/problemas/notebook-superaquecendo-curitiba",
    "/problemas/notebook-teclado-nao-funciona-curitiba",
    "/problemas/notebook-tela-amarelada-curitiba",
    "/problemas/notebook-tela-escura-curitiba",
    "/problemas/notebook-tela-preta-curitiba",
    "/problemas/notebook-touchpad-nao-funciona-curitiba",
    "/problemas/o-que-causa-curto-em-placa",
    "/problemas/o-que-fazer-computador-nao-liga",
    "/problemas/o-que-fazer-notebook-lento",
    "/problemas/pc-com-barulho-estranho-curitiba",
    "/problemas/pc-com-pop-ups-e-propagandas-curitiba",
    "/problemas/pc-com-programas-pesados",
    "/problemas/pc-com-tela-congelada-curitiba",
    "/problemas/pc-com-tela-preta-curitiba",
    "/problemas/pc-com-virus-ransomware-curitiba",
    "/problemas/pc-desligando-sozinho-curitiba",
    "/problemas/pc-fazendo-barulho-estranho-curitiba",
    "/problemas/pc-nao-conecta-bluetooth-curitiba",
    "/problemas/pc-nao-conecta-internet-curitiba",
    "/problemas/pc-nao-conecta-wifi-curitiba",
    "/problemas/pc-nao-entra-modo-seguro-curitiba",
    "/problemas/pc-nao-reconhece-hd-curitiba",
    "/problemas/pc-nao-reconhece-segundo-monitor-curitiba",
    "/problemas/pc-nao-reconhece-usb-curitiba",
    "/problemas/pc-reiniciando-sozinho-curitiba",
    "/problemas/pc-sem-audio-curitiba",
    "/problemas/pc-sem-imagem-curitiba",
    "/problemas/pc-sem-som-hdmi-curitiba",
    "/problemas/pc-superaquecendo-curitiba",
    "/problemas/pc-trava-ao-jogar-curitiba",
    "/problemas/pc-travando-em-jogos-curitiba",
    "/problemas/pc-travando-jogos-curitiba",
    "/problemas/pen-drive-nao-reconhece-curitiba",
    "/problemas/placa-de-video-nao-funciona-curitiba",
    "/problemas/placa-mae-com-defeito-curitiba",
    "/problemas/placa-mae-queimada",
    "/problemas/por-que-conserto-placa-mae-custa-caro-curitiba",
    "/problemas/por-que-display-e-caro-curitiba",
    "/problemas/quando-nao-compensa-reparo",
    "/problemas/quando-trocar-computador",
    "/problemas/quanto-custa-trocar-tela-celular-curitiba",
    "/problemas/quanto-custa-trocar-tela-tv-curitiba",
    "/problemas/radio-nao-liga-curitiba",
    "/problemas/reballing-bga-curitiba",
    "/problemas/recapacitacao-placa-eletronica-curitiba",
    "/problemas/receiver-sem-som-curitiba",
    "/problemas/reflow-bga-curitiba",
    "/problemas/reparo-placa-mae-celular-curitiba",
    "/problemas/reparo-placa-mae-notebook-curitiba",
    "/problemas/reparo-placa-principal-tv-curitiba",
    "/problemas/reparo-placa-som-amplificador-curitiba",
    "/problemas/riscos-de-tentar-consertar",
    "/problemas/smart-tv-lenta-curitiba",
    "/problemas/som-automotivo-nao-funciona-curitiba",
    "/problemas/som-chiando-curitiba",
    "/problemas/som-nao-funciona-curitiba",
    "/problemas/ssd-nao-reconhece-curitiba",
    "/problemas/teclado-mouse-nao-funciona-curitiba",
    "/problemas/teclado-nao-funciona-curitiba",
    "/problemas/tecnico-computador-perto-de-mim",
    "/problemas/tecnico-informatica-emergencia-curitiba",
    "/problemas/tela-azul-windows-curitiba",
    "/problemas/troca-chip-bga-curitiba",
    "/problemas/tv-cheiro-queimado-curitiba",
    "/problemas/tv-com-linhas-na-tela-curitiba",
    "/problemas/tv-com-som-sem-imagem-curitiba",
    "/problemas/tv-com-tela-escura-curitiba",
    "/problemas/tv-controle-nao-funciona-curitiba",
    "/problemas/tv-demora-ligar-curitiba",
    "/problemas/tv-desliga-sozinha-curitiba",
    "/problemas/tv-desligando-sozinha-curitiba",
    "/problemas/tv-imagem-fantasma-curitiba",
    "/problemas/tv-listras-horizontais-verticais-conserto-curitiba",
    "/problemas/tv-listras-na-tela-curitiba",
    "/problemas/tv-manchas-na-tela-curitiba",
    "/problemas/tv-nao-conecta-wifi-bluetooth-curitiba",
    "/problemas/tv-nao-liga-curitiba",
    "/problemas/tv-pixel-morto-curitiba",
    "/problemas/tv-sem-cores-curitiba",
    "/problemas/tv-sem-hdmi-curitiba",
    "/problemas/tv-sem-imagem-curitiba",
    "/problemas/tv-sem-som-curitiba",
    "/problemas/tv-sem-wifi-curitiba",
    "/problemas/tv-som-sem-video-curitiba",
    "/problemas/tv-tela-quebrada-curitiba",
    "/problemas/tv-travando-lenta-curitiba",
    "/problemas/upgrade-deu-problema",
    "/problemas/vale-a-pena-consertar-computador",
    "/problemas/vale-a-pena-consertar-notebook",
    "/problemas/wifi-caindo-curitiba",
    "/problemas/windows-lento-curitiba",
    "/problemas/windows-travando-na-atualizacao-curitiba",
    "/procedimentos-placa",
    "/procedimentos/alto-falante-queimado-curitiba",
    "/procedimentos/amplificador-nao-liga-curitiba",
    "/procedimentos/assistencia-tecnica-urgente-curitiba",
    "/procedimentos/backup-perdido-curitiba",
    "/procedimentos/cabo-rede-nao-funciona-curitiba",
    "/procedimentos/caixa-som-nao-carrega-curitiba",
    "/procedimentos/caixa-som-sem-audio-curitiba",
    "/procedimentos/caixa-som-sem-bluetooth-curitiba",
    "/procedimentos/camera-seguranca-nao-funciona-curitiba",
    "/procedimentos/celular-bateria-inchada-curitiba",
    "/procedimentos/celular-camera-nao-funciona-curitiba",
    "/procedimentos/celular-com-virus-curitiba",
    "/procedimentos/celular-lento-curitiba",
    "/procedimentos/celular-listras-na-tela-curitiba",
    "/procedimentos/celular-molhou-curitiba",
    "/procedimentos/celular-nao-carrega-curitiba",
    "/procedimentos/celular-nao-liga-curitiba",
    "/procedimentos/celular-sem-sinal-curitiba",
    "/procedimentos/celular-tela-quebrada-curitiba",
    "/procedimentos/celular-touch-nao-funciona-curitiba",
    "/procedimentos/computador-com-cheiro-de-queimado-curitiba",
    "/procedimentos/computador-com-som-estranho-curitiba",
    "/procedimentos/computador-com-tela-preta-curitiba",
    "/procedimentos/computador-com-virus-curitiba",
    "/procedimentos/computador-desligando-apos-segundos-curitiba",
    "/procedimentos/computador-lento-curitiba",
    "/procedimentos/computador-liga-e-desliga-curitiba",
    "/procedimentos/computador-muito-barulhento-curitiba",
    "/procedimentos/computador-nao-conecta-bluetooth-curitiba",
    "/procedimentos/computador-nao-desliga-curitiba",
    "/procedimentos/computador-nao-liga-curitiba",
    "/procedimentos/computador-nao-reconhece-usb-curitiba",
    "/procedimentos/computador-reiniciando-sozinho-curitiba",
    "/procedimentos/computador-sem-video-curitiba",
    "/procedimentos/computador-sem-wifi-curitiba",
    "/procedimentos/computador-travando-curitiba",
    "/procedimentos/conserto-computador-domicilio-curitiba",
    "/procedimentos/curto-em-placa-eletronica",
    "/procedimentos/custo-reparo-vs-novo",
    "/procedimentos/erro-0x0000007b-curitiba",
    "/procedimentos/erro-0x80004005-curitiba",
    "/procedimentos/erro-0x80070005-curitiba",
    "/procedimentos/erro-0x80070057-curitiba",
    "/procedimentos/erro-0x800f081f-curitiba",
    "/procedimentos/erro-0x80240034-curitiba",
    "/procedimentos/erro-0xc00000e-curitiba",
    "/procedimentos/erro-0xc000021a-curitiba",
    "/procedimentos/erro-ao-instalar-memoria-ram",
    "/procedimentos/erro-ao-instalar-windows-curitiba",
    "/procedimentos/erro-apos-formatacao",
    "/procedimentos/erro-atualizacao-windows-11-curitiba",
    "/procedimentos/erro-bios-curitiba",
    "/procedimentos/erro-disco-100-porcento-curitiba",
    "/procedimentos/erro-disco-cheio-curitiba",
    "/procedimentos/erro-driver-windows-curitiba",
    "/procedimentos/erro-particao-windows-curitiba",
    "/procedimentos/erro-registro-windows-curitiba",
    "/procedimentos/erro-windows-update-curitiba",
    "/procedimentos/erros-comuns-em-upgrade",
    "/procedimentos/fonte-queimada-curitiba",
    "/procedimentos/formatacao-resolve-curitiba",
    "/procedimentos/gpu-desgastada",
    "/procedimentos/hd-externo-nao-reconhece-curitiba",
    "/procedimentos/hd-fazendo-barulho-curitiba",
    "/procedimentos/impressora-cartucho-nao-reconhece-curitiba",
    "/procedimentos/impressora-erro-conexao-usb-wifi-curitiba",
    "/procedimentos/impressora-nao-imprime-curitiba",
    "/procedimentos/impressora-papel-preso-curitiba",
    "/procedimentos/impressora-tinta-nao-sai-curitiba",
    "/procedimentos/internet-lenta-curitiba",
    "/procedimentos/listras-tela-celular-apos-atualizacao-curitiba",
    "/procedimentos/manutencao-notebook-curitiba-rapido",
    "/procedimentos/memoria-ram-com-defeito-curitiba",
    "/procedimentos/microsoldagem-celular-curitiba",
    "/procedimentos/monitor-piscando-curitiba",
    "/procedimentos/monitor-sem-sinal-curitiba",
    "/procedimentos/mouse-nao-funciona-curitiba",
    "/procedimentos/notebook-apos-upgrade-nao-liga-curitiba",
    "/procedimentos/notebook-bateria-nao-carrega-curitiba",
    "/procedimentos/notebook-com-agua-ou-liquido-curitiba",
    "/procedimentos/notebook-com-tela-piscando-curitiba",
    "/procedimentos/notebook-com-tela-quebrada-curitiba",
    "/procedimentos/notebook-desliga-sozinho-curitiba",
    "/procedimentos/notebook-desligando-sozinho-curitiba",
    "/procedimentos/notebook-esquentando-curitiba",
    "/procedimentos/notebook-esquentando-desligando-curitiba",
    "/procedimentos/notebook-esquentando-muito-curitiba",
    "/procedimentos/notebook-lento-curitiba",
    "/procedimentos/notebook-nao-carrega-bateria-curitiba",
    "/procedimentos/notebook-nao-carrega-curitiba",
    "/procedimentos/notebook-nao-conecta-bluetooth-curitiba",
    "/procedimentos/notebook-nao-liga-curitiba",
    "/procedimentos/notebook-sem-audio-curitiba",
    "/procedimentos/notebook-sem-imagem-curitiba",
    "/procedimentos/notebook-sem-som-curitiba",
    "/procedimentos/notebook-sem-webcam-curitiba",
    "/procedimentos/notebook-sem-wifi-curitiba",
    "/procedimentos/notebook-superaquecendo-curitiba",
    "/procedimentos/notebook-teclado-nao-funciona-curitiba",
    "/procedimentos/notebook-tela-amarelada-curitiba",
    "/procedimentos/notebook-tela-escura-curitiba",
    "/procedimentos/notebook-tela-preta-curitiba",
    "/procedimentos/notebook-touchpad-nao-funciona-curitiba",
    "/procedimentos/o-que-causa-curto-em-placa",
    "/procedimentos/o-que-fazer-computador-nao-liga",
    "/procedimentos/o-que-fazer-notebook-lento",
    "/procedimentos/pc-com-barulho-estranho-curitiba",
    "/procedimentos/pc-com-pop-ups-e-propagandas-curitiba",
    "/procedimentos/pc-com-programas-pesados",
    "/procedimentos/pc-com-tela-congelada-curitiba",
    "/procedimentos/pc-com-tela-preta-curitiba",
    "/procedimentos/pc-com-virus-ransomware-curitiba",
    "/procedimentos/pc-desligando-sozinho-curitiba",
    "/procedimentos/pc-fazendo-barulho-estranho-curitiba",
    "/procedimentos/pc-nao-conecta-bluetooth-curitiba",
    "/procedimentos/pc-nao-conecta-internet-curitiba",
    "/procedimentos/pc-nao-conecta-wifi-curitiba",
    "/procedimentos/pc-nao-entra-modo-seguro-curitiba",
    "/procedimentos/pc-nao-reconhece-hd-curitiba",
    "/procedimentos/pc-nao-reconhece-segundo-monitor-curitiba",
    "/procedimentos/pc-nao-reconhece-usb-curitiba",
    "/procedimentos/pc-reiniciando-sozinho-curitiba",
    "/procedimentos/pc-sem-audio-curitiba",
    "/procedimentos/pc-sem-imagem-curitiba",
    "/procedimentos/pc-sem-som-hdmi-curitiba",
    "/procedimentos/pc-superaquecendo-curitiba",
    "/procedimentos/pc-trava-ao-jogar-curitiba",
    "/procedimentos/pc-travando-em-jogos-curitiba",
    "/procedimentos/pc-travando-jogos-curitiba",
    "/procedimentos/pen-drive-nao-reconhece-curitiba",
    "/procedimentos/placa-de-video-nao-funciona-curitiba",
    "/procedimentos/placa-mae-com-defeito-curitiba",
    "/procedimentos/placa-mae-queimada",
    "/procedimentos/por-que-conserto-placa-mae-custa-caro-curitiba",
    "/procedimentos/por-que-display-e-caro-curitiba",
    "/procedimentos/quando-nao-compensa-reparo",
    "/procedimentos/quando-trocar-computador",
    "/procedimentos/quanto-custa-trocar-tela-celular-curitiba",
    "/procedimentos/quanto-custa-trocar-tela-tv-curitiba",
    "/procedimentos/radio-nao-liga-curitiba",
    "/procedimentos/reballing-bga-curitiba",
    "/procedimentos/recapacitacao-placa-eletronica-curitiba",
    "/procedimentos/receiver-sem-som-curitiba",
    "/procedimentos/reflow-bga-curitiba",
    "/procedimentos/reparo-placa-mae-celular-curitiba",
    "/procedimentos/reparo-placa-mae-notebook-curitiba",
    "/procedimentos/reparo-placa-principal-tv-curitiba",
    "/procedimentos/reparo-placa-som-amplificador-curitiba",
    "/procedimentos/riscos-de-tentar-consertar",
    "/procedimentos/smart-tv-lenta-curitiba",
    "/procedimentos/som-automotivo-nao-funciona-curitiba",
    "/procedimentos/som-chiando-curitiba",
    "/procedimentos/som-nao-funciona-curitiba",
    "/procedimentos/ssd-nao-reconhece-curitiba",
    "/procedimentos/teclado-mouse-nao-funciona-curitiba",
    "/procedimentos/teclado-nao-funciona-curitiba",
    "/procedimentos/tecnico-computador-perto-de-mim",
    "/procedimentos/tecnico-informatica-emergencia-curitiba",
    "/procedimentos/tela-azul-windows-curitiba",
    "/procedimentos/troca-chip-bga-curitiba",
    "/procedimentos/tv-cheiro-queimado-curitiba",
    "/procedimentos/tv-com-linhas-na-tela-curitiba",
    "/procedimentos/tv-com-som-sem-imagem-curitiba",
    "/procedimentos/tv-com-tela-escura-curitiba",
    "/procedimentos/tv-controle-nao-funciona-curitiba",
    "/procedimentos/tv-demora-ligar-curitiba",
    "/procedimentos/tv-desliga-sozinha-curitiba",
    "/procedimentos/tv-desligando-sozinha-curitiba",
    "/procedimentos/tv-imagem-fantasma-curitiba",
    "/procedimentos/tv-listras-horizontais-verticais-conserto-curitiba",
    "/procedimentos/tv-listras-na-tela-curitiba",
    "/procedimentos/tv-manchas-na-tela-curitiba",
    "/procedimentos/tv-nao-conecta-wifi-bluetooth-curitiba",
    "/procedimentos/tv-nao-liga-curitiba",
    "/procedimentos/tv-pixel-morto-curitiba",
    "/procedimentos/tv-sem-cores-curitiba",
    "/procedimentos/tv-sem-hdmi-curitiba",
    "/procedimentos/tv-sem-imagem-curitiba",
    "/procedimentos/tv-sem-som-curitiba",
    "/procedimentos/tv-sem-wifi-curitiba",
    "/procedimentos/tv-som-sem-video-curitiba",
    "/procedimentos/tv-tela-quebrada-curitiba",
    "/procedimentos/tv-travando-lenta-curitiba",
    "/procedimentos/upgrade-deu-problema",
    "/procedimentos/vale-a-pena-consertar-computador",
    "/procedimentos/vale-a-pena-consertar-notebook",
    "/procedimentos/wifi-caindo-curitiba",
    "/procedimentos/windows-lento-curitiba",
    "/procedimentos/windows-travando-na-atualizacao-curitiba",
    "/quando-nao-compensa",
    "/seguranca-dos-dados",
    "/seja-parceiro",
    "/servicos",
    "/servicos/backup-para-empresas",
    "/servicos/backup-recuperacao/centro",
    "/servicos/computador-lento",
    "/servicos/computador-nao-liga",
    "/servicos/conserto-celular",
    "/servicos/conserto-monitor",
    "/servicos/conserto-pc-notebook/araucaria",
    "/servicos/conserto-pc-notebook/batel",
    "/servicos/conserto-pc-notebook/campo-largo",
    "/servicos/conserto-pc-notebook/cic",
    "/servicos/conserto-pc-notebook/pinhais",
    "/servicos/conserto-pc-notebook/portao",
    "/servicos/conserto-pc-notebook/sao-jose-dos-pinhais",
    "/servicos/conserto-placa",
    "/servicos/conserto-tv",
    "/servicos/formatacao",
    "/servicos/formatacao-computador/araucaria",
    "/servicos/formatacao-computador/campo-comprido",
    "/servicos/formatacao-computador/campo-largo",
    "/servicos/formatacao-computador/centro",
    "/servicos/formatacao-computador/pinhais",
    "/servicos/formatacao-computador/portao",
    "/servicos/formatacao-computador/sao-jose-dos-pinhais",
    "/servicos/manutencao-de-computador",
    "/servicos/manutencao-de-notebook",
    "/servicos/manutencao-preventiva-empresas",
    "/servicos/manutencao-tv",
    "/servicos/manutencao-tv/agua-verde",
    "/servicos/manutencao-tv/alto-da-xv",
    "/servicos/manutencao-tv/batel",
    "/servicos/manutencao-tv/bigorrilho",
    "/servicos/manutencao-tv/boa-vista",
    "/servicos/manutencao-tv/boqueirao",
    "/servicos/manutencao-tv/cabral",
    "/servicos/manutencao-tv/cajuru",
    "/servicos/manutencao-tv/centro",
    "/servicos/manutencao-tv/cic",
    "/servicos/manutencao-tv/cristo-rei",
    "/servicos/manutencao-tv/ecoville",
    "/servicos/manutencao-tv/jardim-das-americas",
    "/servicos/manutencao-tv/portao",
    "/servicos/manutencao-tv/reboucas",
    "/servicos/manutencao-tv/santa-felicidade",
    "/servicos/montagem-de-pc",
    "/servicos/montagem-pc",
    "/servicos/montagem-pc/cic",
    "/servicos/pc-gamer",
    "/servicos/recuperacao-de-dados",
    "/servicos/redes-e-wifi",
    "/servicos/redes-wifi/agua-verde",
    "/servicos/redes-wifi/alto-da-xv",
    "/servicos/redes-wifi/araucaria",
    "/servicos/redes-wifi/batel",
    "/servicos/redes-wifi/bigorrilho",
    "/servicos/redes-wifi/boa-vista",
    "/servicos/redes-wifi/boqueirao",
    "/servicos/redes-wifi/cabral",
    "/servicos/redes-wifi/cajuru",
    "/servicos/redes-wifi/campo-largo",
    "/servicos/redes-wifi/centro",
    "/servicos/redes-wifi/cic",
    "/servicos/redes-wifi/cristo-rei",
    "/servicos/redes-wifi/ecoville",
    "/servicos/redes-wifi/jardim-das-americas",
    "/servicos/redes-wifi/pinhais",
    "/servicos/redes-wifi/portao",
    "/servicos/redes-wifi/reboucas",
    "/servicos/redes-wifi/santa-felicidade",
    "/servicos/redes-wifi/sao-jose-dos-pinhais",
    "/servicos/remocao-de-virus",
    "/servicos/remocao-virus/araucaria",
    "/servicos/remocao-virus/batel",
    "/servicos/remocao-virus/campo-largo",
    "/servicos/remocao-virus/centro",
    "/servicos/remocao-virus/pinhais",
    "/servicos/remocao-virus/portao",
    "/servicos/remocao-virus/sao-jose-dos-pinhais",
    "/servicos/suporte-home-office",
    "/servicos/suporte-tecnico-empresarial",
    "/servicos/upgrade-ssd-memoria/araucaria",
    "/servicos/upgrade-ssd-memoria/batel",
    "/servicos/upgrade-ssd-memoria/pinhais",
    "/servicos/upgrade-ssd-memoria/santa-felicidade",
    "/servicos/upgrade-ssd-memoria/sao-jose-dos-pinhais",
    "/servicos/upgrade-ssd-ram",
    "/sobre",
    "/status",
    "/status-da-ordem-de-servico",
    "/status-de-anuncios",
    "/status-os",
    "/tecnico-informatica-almirante-tamandare",
    "/tecnico-informatica-araucaria",
    "/tecnico-informatica-campo-largo",
    "/tecnico-informatica-campo-magro",
    "/tecnico-informatica-colombo",
    "/tecnico-informatica-curitiba",
    "/tecnico-informatica-fazenda-rio-grande",
    "/tecnico-informatica-pinhais",
    "/tecnico-informatica-piraquara",
    "/tecnico-informatica-quatro-barras",
    "/tecnico-informatica-sao-jose-pinhais",
    "/termos-e-condicoes"
  ],
  validPatterns: [
    "/arrumar-pc/:cidade",
    "/arrumar-pc/servico/:servico/:cidade",
    "/blog/:slug",
    "/conserto-celular/:local",
    "/conserto-som/:local",
    "/conserto-tv/:local",
    "/conserto-videogame/:local",
    "/marcas/:slug",
    "/problemas/:slug",
    "/procedimentos/:slug",
    "/servicos/:servico/:cidade"
  ],
  patternInfo: [
    {
      pattern: "/arrumar-pc/:cidade",
      closed: true,
      knownCount: 21
    },
    {
      pattern: "/arrumar-pc/servico/:servico/:cidade",
      closed: false,
      knownCount: 0
    },
    {
      pattern: "/blog/:slug",
      closed: true,
      knownCount: 159
    },
    {
      pattern: "/conserto-celular/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/conserto-som/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/conserto-tv/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/conserto-videogame/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/marcas/:slug",
      closed: true,
      knownCount: 26
    },
    {
      pattern: "/problemas/:slug",
      closed: true,
      knownCount: 191
    },
    {
      pattern: "/procedimentos/:slug",
      closed: true,
      knownCount: 189
    },
    {
      pattern: "/servicos/:servico/:cidade",
      closed: true,
      knownCount: 64
    }
  ],
  redirects: [
    {
      from: "/servicos/formatacao-computador",
      to: "/servicos/formatacao",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/remocao-virus",
      to: "/servicos/remocao-de-virus",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/upgrade-ssd-memoria",
      to: "/servicos/upgrade-ssd-ram",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/conserto-pc-notebook",
      to: "/servicos/manutencao-de-computador",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/conserto-notebook-curitiba",
      to: "/servicos/manutencao-de-notebook",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/redes-wifi",
      to: "/servicos/redes-e-wifi",
      motivo: "variacao-slug"
    },
    {
      from: "/tecnico-informatica-sao-jose-dos-pinhais",
      to: "/tecnico-informatica-sao-jose-pinhais",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/backup-recuperacao",
      to: "/servicos/recuperacao-de-dados",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/montagem-de-pc-gamer",
      to: "/servicos/montagem-de-pc",
      motivo: "variacao-slug"
    },
    {
      from: "/pc-gamer-curitiba",
      to: "/servicos/pc-gamer",
      motivo: "url-antiga"
    },
    {
      from: "/formatacao-de-computador-curitiba",
      to: "/servicos/formatacao",
      motivo: "url-antiga"
    },
    {
      from: "/remocao-de-virus-curitiba",
      to: "/servicos/remocao-de-virus",
      motivo: "url-antiga"
    },
    {
      from: "/upgrade-ssd-curitiba",
      to: "/servicos/upgrade-ssd-ram",
      motivo: "url-antiga"
    },
    {
      from: "/upgrade-memoria-ram-curitiba",
      to: "/servicos/upgrade-ssd-ram",
      motivo: "url-antiga"
    },
    {
      from: "/conserto-de-notebook-curitiba",
      to: "/servicos/manutencao-de-notebook",
      motivo: "url-antiga"
    },
    {
      from: "/suporte-tecnico-remoto",
      to: "/atendimento-remoto",
      motivo: "url-antiga"
    },
    {
      from: "/assistencia-tecnica-empresas-curitiba",
      to: "/servicos/suporte-tecnico-empresarial",
      motivo: "url-antiga"
    },
    {
      from: "/suporte-empresas",
      to: "/servicos/suporte-tecnico-empresarial",
      motivo: "url-antiga"
    },
    {
      from: "/reflow-bga-curitiba",
      to: "/procedimentos/reflow-bga-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/reballing-bga-curitiba",
      to: "/procedimentos/reballing-bga-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/troca-chip-bga-curitiba",
      to: "/procedimentos/troca-chip-bga-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/microsoldagem-celular-curitiba",
      to: "/procedimentos/microsoldagem-celular-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/recapacitacao-placa-eletronica-curitiba",
      to: "/procedimentos/recapacitacao-placa-eletronica-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/privacidade",
      to: "/politica-de-privacidade",
      motivo: "alias-institucional"
    },
    {
      from: "/termos",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/valores",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/precos",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/termos-condicoes-valores",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/publicidade",
      to: "/anuncie",
      motivo: "alias-institucional"
    },
    {
      from: "/pessoa-fisica",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/para-voce",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/residencial",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/tecnico-a-domicilio",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/pessoa-juridica",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/para-empresas",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/empresas",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/ti-para-empresas",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/suporte-corporativo",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    }
  ],
  privatePrefixes: [
    "/admin",
    "/ads"
  ],
  assetPrefixes: [
    "/assets/",
    "/lovable-uploads/",
    "/images/",
    "/fonts/",
    "/css/",
    "/blog/"
  ],
  assetFiles: [
    "/_headers",
    "/_redirects",
    "/ads-status.json",
    "/ads.txt",
    "/apple-touch-icon-20260624.png",
    "/apple-touch-icon.png",
    "/assets/AcademiaSJP-CZ4619nR.js",
    "/assets/AdminCasos-DbL91Omb.js",
    "/assets/AdminConversao-DNxfh1iA.js",
    "/assets/AdminDashboard-CFX6y-iE.js",
    "/assets/AdminFunnel-DFU-zYq-.js",
    "/assets/AdminLogin-Dpd4hAHZ.js",
    "/assets/AdminOperacao-T3i9NvDK.js",
    "/assets/AdminOsAudit-BuUDNVCM.js",
    "/assets/AdminProvasMonitor-awIiklpW.js",
    "/assets/AdminProvasVerticais-Qji2RaSL.js",
    "/assets/AdminReviews-CK0XBgh9.js",
    "/assets/AdminVitals-BpuYkjzD.js",
    "/assets/AfonsoPena-B6z1JWdR.js",
    "/assets/AgricolareSJP-BkUVfFSr.js",
    "/assets/AguaVerde-Bxe-Qlnt.js",
    "/assets/AguaVerdeBairro-DJ4JNG2q.js",
    "/assets/AltoBoqueiraoCtba-ANSk4hYq.js",
    "/assets/AltoGloria-DPUN7gzL.js",
    "/assets/AltoMaracanaColombo-DJ5BNseH.js",
    "/assets/AltoTaruma-4mB12HJD.js",
    "/assets/AnimatedSection-TdFxbNGX.js",
    "/assets/AntonioOliveraCM-DYXEdOqi.js",
    "/assets/Anuncie-D2Y8hDV_.js",
    "/assets/AraucariaCentro-D-UrrbJV.js",
    "/assets/AreasAtendidas-fmxhxAtn.js",
    "/assets/Aristocrata-CCHFPjGP.js",
    "/assets/ArrumarPC--YCUQ5Vv.js",
    "/assets/ArrumarPCCity-DcAwRkqz.js",
    "/assets/ArrumarPCServicoCidade-CvwVPviB.js",
    "/assets/AssistenciaEletrodomesticosInteligentesCuritiba-DcpVp9k2.js",
    "/assets/AssistenciaTecnicaCuritiba-BZRuRqpj.js",
    "/assets/AtendimentoDomicilio-DLKj28eT.js",
    "/assets/AtendimentoRemoto-B6Yfv9Yh.js",
    "/assets/AtubaColombo-EVr3szji.js",
    "/assets/AtubaPinhais-B41M5eVy.js",
    "/assets/Avaliar-rvemGBhR.js",
    "/assets/Aviacao-D8k15_3A.js",
    "/assets/Bacacheri-DKE1xue4.js",
    "/assets/BackupCentro-CZOMPTv3.js",
    "/assets/BairroLocalLayout-vwHsrSZe.js",
    "/assets/BairroTemplate-DGjLiy-6.js",
    "/assets/BariguiAraucaria-DGWY1XJ-.js",
    "/assets/BarroPreto-CfEvBKD2.js",
    "/assets/BateiasCL-DbNHugd5.js",
    "/assets/Batel-qC0WS1-R.js",
    "/assets/BenefitsGrid-B49wQquI.js",
    "/assets/Bigorrilho-BRSBNOUH.js",
    "/assets/BlocoInteligencia-B5K0Vlh4.js",
    "/assets/Blocos3U-BJuxfyS9.js",
    "/assets/Blog-Ddio00iu.js",
    "/assets/BlogPost-BTHjiuit.js",
    "/assets/BlogPostFAQ-T-qUDTmS.js",
    "/assets/BoaVista-Cjt2iEqt.js",
    "/assets/BoaVistaTamandare-rq3fjRq8.js",
    "/assets/BonecaSJP-BVNFwFcd.js",
    "/assets/Boqueirao-aQXNDCVX.js",
    "/assets/BoqueiraoAraucaria-DSnxdxaO.js",
    "/assets/BordaDoCampoQB-BmPpk2vm.js",
    "/assets/BordaDoCampoSJP-CGS8j3O-.js",
    "/assets/BordoDoCampoSJP2-ocD1wHWT.js",
    "/assets/BotiatuvaCL-Sub9DRiJ.js",
    "/assets/BotiatuvaCM-CRtFsutG.js",
    "/assets/Braga-ClUv33-F.js",
    "/assets/Breadcrumbs-32tRnZEj.js",
    "/assets/CFTV-zQBJoyi1.js",
    "/assets/CFTVAraucaria-iNb953b0.js",
    "/assets/CFTVCampoLargo-DseR2rO5.js",
    "/assets/CFTVCityTemplate-gCDfM2Hs.js",
    "/assets/CFTVCuritiba-D-uPNHNO.js",
    "/assets/CFTVGuaratuba-Du5yHj9C.js",
    "/assets/CFTVLitoral-DlCNQUNV.js",
    "/assets/CFTVPinhais-Bc-_slW4.js",
    "/assets/CFTVSaoJosePinhais-DJOmgrwQ.js",
    "/assets/CIC-CWm5O7gx.js",
    "/assets/CTASection-CT3uGIhq.js",
    "/assets/Cabral-DURYFoNn.js",
    "/assets/CacheiraAraucaria-D2X3I66X.js",
    "/assets/CachoeiraAT-BF0lFlrc.js",
    "/assets/CaiuaPiraquara-BJ5-mRnp.js",
    "/assets/Cajuru-BhMgefuJ.js",
    "/assets/CaliforniaAraucaria-DSH-318M.js",
    "/assets/CampinaDaBarra-CWibEQQ2.js",
    "/assets/CampinaGrandeColombo-cMDT_FjL.js",
    "/assets/CampoComprido-Cf5kiSZz.js",
    "/assets/CampoDoTenenteTamandare-pfkrtuwq.js",
    "/assets/CampoLargoCentro-CA0ALpC6.js",
    "/assets/CampoLargoSJP-C3quRAcE.js",
    "/assets/CampoPequenoColombo-D_mycLke.js",
    "/assets/CapaoImbuia-DJVpPucU.js",
    "/assets/CapelaVelhaAraucaria-BGs1Cf9E.js",
    "/assets/CategoryLocalTemplate-C8Pfh8Bs.js",
    "/assets/Centro-PBrR_VnA.js",
    "/assets/CentroAlmiranteTamandare-DDx8cPoi.js",
    "/assets/CentroCampoMagro-C2fmRpI9.js",
    "/assets/CentroColombo-CUQY-PDt.js",
    "/assets/CentroFRG-CJwi6_WP.js",
    "/assets/CentroPiraquara-51_OkN1C.js",
    "/assets/CentroQuatroBarras-Bm6K-XaO.js",
    "/assets/ChapadaAraucaria-BhBTauOn.js",
    "/assets/CidadeJardimSJP-aQiEdHHK.js",
    "/assets/CidadeLandingLayout-DANfHjbd.js",
    "/assets/CityServiceSchema-Fc2vk3Iq.js",
    "/assets/ClusterLinks-BWtxcShO.js",
    "/assets/ColareColombo-BffjHDey.js",
    "/assets/ColetaEntrega-DzohJ8bg.js",
    "/assets/ColetaFormulario-DyeO5TFO.js",
    "/assets/ColoniaAntonioPradoAT-Cy6QlpGT.js",
    "/assets/ColoniaMalhadaCL-Fg5lwig3.js",
    "/assets/ColoniaMurcySJP-D2a1KwrI.js",
    "/assets/ComoAvaliar-D4YvypEu.js",
    "/assets/ComoFunciona-CbxF1b97.js",
    "/assets/ComputadorLento-B1E9Jkrz.js",
    "/assets/ComputadorLento-BUdBauzB.js",
    "/assets/ComputadorNaoLiga-Cva8oePI.js",
    "/assets/ConsertoCelular-PogZY_UZ.js",
    "/assets/ConsertoImpressoraCuritiba-DZqUUDFt.js",
    "/assets/ConsertoNotebookAraucaria-CkPbp5ho.js",
    "/assets/ConsertoNotebookBatel-BTl5Lj7-.js",
    "/assets/ConsertoNotebookCIC-Bb53d-Oo.js",
    "/assets/ConsertoNotebookCampoLargo-Brqsehn3.js",
    "/assets/ConsertoNotebookPinhais-DuhIz3j0.js",
    "/assets/ConsertoNotebookPortao-a_DDo4Y3.js",
    "/assets/ConsertoNotebookSaoJosePinhais-Cr--6HwH.js",
    "/assets/Contato-Dn3BsV66.js",
    "/assets/CorreiaDeFreitasCL-j6wYL9pu.js",
    "/assets/Costeira-Cfy77C6g.js",
    "/assets/CosteiraAraucaria-gdrDatJm.js",
    "/assets/CristoRei-BdcvAi3d.js",
    "/assets/Cruzeiro-CHSBMKK5.js",
    "/assets/DebugTelemetria-C0aA32Ds.js",
    "/assets/DelRey-CKTgo1X_.js",
    "/assets/Depoimentos-Cm7nBply.js",
    "/assets/Diagnostico60s-ndhU8cw4.js",
    "/assets/DiagnosticoTecnico-DDVfKfjU.js",
    "/assets/EditorialContentLinks-qUo6P1Pc.js",
    "/assets/EeatProofsSection-BnIDfwkg.js",
    "/assets/EmbuColombo-sfqy1nFL.js",
    "/assets/EmilianoPerneta-Djq1tzi3.js",
    "/assets/EmpresaDeTiCuritiba-fVODZvDZ.js",
    "/assets/EquipamentosAtendidos-CS-IQDUh.js",
    "/assets/EspigoAlegreCM-DykoAlTp.js",
    "/assets/EstacaoAraucaria-C2o7nmMK.js",
    "/assets/EstanciaPinhais-WkcurRlm.js",
    "/assets/EucaliptosFRG-G9mdNd-j.js",
    "/assets/EucaliptosFRG2-QHPbqrxn.js",
    "/assets/ExcluirMeusDados-B1GRmFpn.js",
    "/assets/ExperienciaBadge-BQrJNAlH.js",
    "/assets/FAQ-BXgYN0eZ.js",
    "/assets/FatimaColombo-CvmwgCel.js",
    "/assets/FazendaVelhaAraucaria-DfsLglns.js",
    "/assets/Fazendinha-Cjqx71Yo.js",
    "/assets/FerrariaCampoLargo-DfVXKnZ5.js",
    "/assets/FloatingParticles-DSdtZLps.js",
    "/assets/Footer-DMqYcy1u.js",
    "/assets/FormatacaoAraucaria-C1haSCDy.js",
    "/assets/FormatacaoCampoComprido-CDJ1tl16.js",
    "/assets/FormatacaoCampoLargo-DwgDPYUA.js",
    "/assets/FormatacaoCentro-BLD6WLxe.js",
    "/assets/FormatacaoPinhais-D7sYz5Xb.js",
    "/assets/FormatacaoPortao-DRUk-mj5.js",
    "/assets/FormatacaoSaoJosePinhais-DIjmlfrn.js",
    "/assets/FunilIndisponivel-BN6AAz55.js",
    "/assets/GA4ChecklistPanel-B5_Wt-nA.js",
    "/assets/GabirobalColombo-vMYSQEFN.js",
    "/assets/GarantiaNotaFiscalPagamento-Dfvf0mCZ.js",
    "/assets/GestorResponsavel-CWEQdw2X.js",
    "/assets/GraciosaMirQB-BbPO33Li.js",
    "/assets/GraciosaPinhais-D8rJwsqp.js",
    "/assets/GralhaAzulFRG-k4sVbjyz.js",
    "/assets/GuajuviraAraucaria-CaBa7R7I.js",
    "/assets/GuaraitubaColombo-D7uf8hA8.js",
    "/assets/GuaritubaPiraquara-DVlhSVjW.js",
    "/assets/Guatupe-CEcRLeK0.js",
    "/assets/GuiaTecnicoInformatica-44gJ1avG.js",
    "/assets/Hauer-BS0b20Eq.js",
    "/assets/Header-JxHJA6z7.js",
    "/assets/HomeSections-C0MO_hy5.js",
    "/assets/HortenciaFRG-CiDNK2gM.js",
    "/assets/HugoLange-BNqWi055.js",
    "/assets/IguacuAraucaria-C9cvm9yo.js",
    "/assets/IguacuFRG-5WmUfTgm.js",
    "/assets/IndependenciaSJP-BbWp_cdx.js",
    "/assets/IndustrialAraucaria-X8HHtyKz.js",
    "/assets/InlineTriageCTA-BOMogNrA.js",
    "/assets/InterlinkingBlock-DlaaxBj1.js",
    "/assets/IpeSJP-dGT07oMl.js",
    "/assets/IraiPiraquara-DoZ-aT6e.js",
    "/assets/ItaliaSJP-BCakel__.js",
    "/assets/ItaquiCL-CC6WMyW9.js",
    "/assets/JardimAmelia-D0nEctOt.js",
    "/assets/JardimAmericaCL-BlKkOEP-.js",
    "/assets/JardimAmericas-B_aj2uE9.js",
    "/assets/JardimBelaVistaPiraquara-Cikb8B9l.js",
    "/assets/JardimBoaVistaAraucaria-CNZbhETy.js",
    "/assets/JardimBoaVistaCM-B4_Xrwof.js",
    "/assets/JardimClaudia-CNiRGx_M.js",
    "/assets/JardimClaudiaIIPinhais-DBgsi1kV.js",
    "/assets/JardimCondorFRG-D1eKUHaw.js",
    "/assets/JardimDasPedrasFRG-C9ubmyMm.js",
    "/assets/JardimDonaRosaPinhais-DTsq3EKw.js",
    "/assets/JardimEsperancaCL-B8Waf5M0.js",
    "/assets/JardimEsplanadaPinhais-Dn7a-J_4.js",
    "/assets/JardimEstadosFRG-zx_phnTY.js",
    "/assets/JardimFlorestalQB-BUxs57sd.js",
    "/assets/JardimGrazielaAT-Dd6AUXx9.js",
    "/assets/JardimGuilherminaCampoLargo-CmIVcS09.js",
    "/assets/JardimIguacuAraucaria-DS9mnEvJ.js",
    "/assets/JardimIperigoFRG-EOY7Xcb5.js",
    "/assets/JardimJaponeQB-iguqymPv.js",
    "/assets/JardimKarlaPinhais-DzVPgP_4.js",
    "/assets/JardimLaranjeirasCL-B2rF4hsS.js",
    "/assets/JardimMeninoDeusQB-DDk4jiyX.js",
    "/assets/JardimMontoSantoAT-CJt2pwV9.js",
    "/assets/JardimNovoHorizonteCL-UstjNU53.js",
    "/assets/JardimOsascoColombo-DOogGGAa.js",
    "/assets/JardimParaisoAT-DSeK94gW.js",
    "/assets/JardimParanaguaTamandare-DEttOWgt.js",
    "/assets/JardimPedroDemeterco-BEeImLJb.js",
    "/assets/JardimPlanaltoCL-ALLcJeKT.js",
    "/assets/JardimPlanaltoIICL-CPnIuUui.js",
    "/assets/JardimPrimaveraPiraquara-YU941biE.js",
    "/assets/JardimRomaAT-BUrBj2N_.js",
    "/assets/JardimSantoAntonioPiraquara-Bo_ebvsj.js",
    "/assets/JardimSaoJorgeTamandare-LK5Epof8.js",
    "/assets/JardimSaoPauloPiraquara-CmvZi8gv.js",
    "/assets/JardimShangrilaAraucaria-C8Fqj2tB.js",
    "/assets/JardimSocial-bbR3Iw_b.js",
    "/assets/JardimTropicalPinhais-D647usxP.js",
    "/assets/JardimUniaoPiraquara-D0mbsROm.js",
    "/assets/JardimWissingerPinhais-CWdsLOtu.js",
    "/assets/JoqueiFRCM-Cd7-D5Kl.js",
    "/assets/Juveve-BL1LuysH.js",
    "/assets/LamenhaGrandeCL-uKlKlA0K.js",
    "/assets/LegacyApp-DoIg0EO8.js",
    "/assets/LocalBusinessJsonLd-D2IEI5zQ.js",
    "/assets/LocalFAQSection-BvtrPOuM.js",
    "/assets/ManutencaoTV-Bl_iwKZZ.js",
    "/assets/ManutencaoTvAguaVerde-C6NsUsJl.js",
    "/assets/ManutencaoTvAltoXV-BbDmwA-Y.js",
    "/assets/ManutencaoTvBatel-CdMZRAme.js",
    "/assets/ManutencaoTvBigorrilho-CWyUP2Ha.js",
    "/assets/ManutencaoTvBoaVista-CEgBvgNv.js",
    "/assets/ManutencaoTvBoqueirao-2G-w3GI-.js",
    "/assets/ManutencaoTvCabral-B-qadNek.js",
    "/assets/ManutencaoTvCajuru-DuPzFpxi.js",
    "/assets/ManutencaoTvCentro-8WukvXma.js",
    "/assets/ManutencaoTvCic-GnTUiAs-.js",
    "/assets/ManutencaoTvCristoRei-CDSATydW.js",
    "/assets/ManutencaoTvEcoville-btY3saVq.js",
    "/assets/ManutencaoTvJardimAmericas-BRwSK2--.js",
    "/assets/ManutencaoTvPortao-CV55BIXy.js",
    "/assets/ManutencaoTvReboucas-CGaEXgs3.js",
    "/assets/ManutencaoTvSantaFelicidade-CQ5J95DO.js",
    "/assets/MaracanaColombo-DB1Nwt3N.js",
    "/assets/MarcaPage-BoK3EJOz.js",
    "/assets/Marcas-B0D_sfyM.js",
    "/assets/MariaAntonieta-DGHHkx8u.js",
    "/assets/Merces-B5737YYN.js",
    "/assets/MontagemPc-BacjoRUf.js",
    "/assets/MontagemPcCIC-Kkr3v4mK.js",
    "/assets/MonzaColombo-XOmcH5No.js",
    "/assets/NacoesFRG-DAjU4cgJ.js",
    "/assets/NotFound-DTNOe-9z.js",
    "/assets/NotebookNaoLiga-DENjUYhW.js",
    "/assets/NovoMundo-7NGzOcu1.js",
    "/assets/Obrigado-DRyaq8AZ.js",
    "/assets/OrdemDeServico-C7sKc1M1.js",
    "/assets/OswaldoCruzColombo-C7LPRWdK.js",
    "/assets/OuroFinoCL-sJQcXvRE.js",
    "/assets/OuroFinoSJP-C5a8X67-.js",
    "/assets/PageHero-drRgWDg8.js",
    "/assets/PageSEO-4h-6c5tM.js",
    "/assets/PageTableOfContents-7hVfH8As.js",
    "/assets/PalmitalCL-Bhl5OCZ_.js",
    "/assets/PalmitalColombo-DRjLRGdb.js",
    "/assets/PalmitalPinhais-gaqJQiKB.js",
    "/assets/ParqueDaFonte-COlV72vA.js",
    "/assets/ParqueNascentesPinhais-TWegUE7l.js",
    "/assets/PassaunaAraucaria-m3C_-FC8.js",
    "/assets/PedroMoroSJP-CzAZFLxd.js",
    "/assets/PilarEditorialLinks-B7l2xUuM.js",
    "/assets/PinevillePinhais-DLZsuLlS.js",
    "/assets/PinhaisCentro-4TpjMxHK.js",
    "/assets/Pinheirinho-z_m4of2v.js",
    "/assets/PioneirosFRG-BI2HiN36.js",
    "/assets/PlantaDeodoroPiraquara-BfU20pgI.js",
    "/assets/PlantaSaoTiagoAraucaria-DcIwv8gy.js",
    "/assets/PoliticaCookiesAnuncios-B6FNk2Vl.js",
    "/assets/PoliticaPecasCliente-BV-vwn12.js",
    "/assets/PoliticaPrivacidade-CmGD3Dea.js",
    "/assets/Portao-CqPfKQMV.js",
    "/assets/PortoDasLaranjeiras-GraLmPdS.js",
    "/assets/PradoVelhoPiraquara-BRSpOVUt.js",
    "/assets/PrecosEPoliticas-xCH7BvIY.js",
    "/assets/ProblemaPage-C8jgcLPx.js",
    "/assets/ProblemasReaisCasos-DaYmERbz.js",
    "/assets/ProcedimentosPlaca-DX6DuCra.js",
    "/assets/ProximosPassos-DPr92mEz.js",
    "/assets/QuandoNaoCompensa-GeMBKWqC.js",
    "/assets/QuissisanaSJP-DF8cuErw.js",
    "/assets/RealImageSection-CCKwS5x6.js",
    "/assets/Reboucas-D_uTF7qV.js",
    "/assets/RedesWifiAguaVerde-BkLWXIcm.js",
    "/assets/RedesWifiAltoXV-BCeN6JxV.js",
    "/assets/RedesWifiAraucaria-pLA1lIjG.js",
    "/assets/RedesWifiBatel-DJqgs-rw.js",
    "/assets/RedesWifiBigorrilho-BJlQFMUN.js",
    "/assets/RedesWifiBoaVista-DJYwIBuj.js",
    "/assets/RedesWifiBoqueirao-DLCxDPuO.js",
    "/assets/RedesWifiCIC-CI6l8L0N.js",
    "/assets/RedesWifiCabral-CB9iD1Bz.js",
    "/assets/RedesWifiCajuru-CNgWfHKg.js",
    "/assets/RedesWifiCampoLargo-D4akLhck.js",
    "/assets/RedesWifiCentro-DnQomSc4.js",
    "/assets/RedesWifiCristoRei-DG1xk_Vd.js",
    "/assets/RedesWifiEcoville-0_RASQxo.js",
    "/assets/RedesWifiJardimAmericas-cXcVW-nu.js",
    "/assets/RedesWifiPinhais-C5PASnQh.js",
    "/assets/RedesWifiPortao-BzC_1O4w.js",
    "/assets/RedesWifiReboucas-jM8zpPpw.js",
    "/assets/RedesWifiSantaFelicidadeAncora-Dkwj_DpR.js",
    "/assets/RedesWifiSaoJosePinhais-BU2r28Da.js",
    "/assets/RemocaoVirusAraucaria-BUiyL9Cj.js",
    "/assets/RemocaoVirusBatel-BAKdR66n.js",
    "/assets/RemocaoVirusCampoLargo-2gBe6obl.js",
    "/assets/RemocaoVirusCentro-BVRzhFlL.js",
    "/assets/RemocaoVirusPinhais-Ckj_zsix.js",
    "/assets/RemocaoVirusPortao-DFLLVbKA.js",
    "/assets/RemocaoVirusSaoJosePinhais-FegEpgjR.js",
    "/assets/ReviewsGrid-CntcXuw1.js",
    "/assets/RioPequenoSJP-DkmfMZi8.js",
    "/assets/RioVerdeCM-DbgSV1hk.js",
    "/assets/RocaGrandeColombo-CrTj3DTx.js",
    "/assets/RondinhaCL-Cs6iAU-l.js",
    "/assets/SabiaAraucaria-NeqSR64N.js",
    "/assets/SantaCruzCL-Dm112v5s.js",
    "/assets/SantaFelicidade-D0qv_jKs.js",
    "/assets/SantaTerezinhaColombo-B65gFySI.js",
    "/assets/SantaTerezinhaFRG-DlYPzwlV.js",
    "/assets/SaoCristaoPiraquara-nT1jvMoD.js",
    "/assets/SaoCristovao-ByVIMF8F.js",
    "/assets/SaoDomingos-bjfhzDq4.js",
    "/assets/SaoFrancisco-B141WxqE.js",
    "/assets/SaoGabrielColombo-D0TTnLq8.js",
    "/assets/SaoJoseCampoLargo-CCvGdpS_.js",
    "/assets/SaoJoseDosPinhais-BsoJtCNx.js",
    "/assets/SaoLourencoFRG-C7JYGYux.js",
    "/assets/SaoLourencoQB-D7RLkqEi.js",
    "/assets/SaoMarcos-DrFQDunM.js",
    "/assets/SaoMarcosCampoLargo-BPKpGhJy.js",
    "/assets/SaoMiguelAraucaria-Cz4XZFot.js",
    "/assets/SaoSebastiaoCM-DzfS_tat.js",
    "/assets/SaoSilvestreCL-Bh6Yw8Ur.js",
    "/assets/SaoVenancioAT-C6WxsmK8.js",
    "/assets/SedeCampoMagro-AgLMmTKa.js",
    "/assets/SegurancaDosDados-BSO4dCcs.js",
    "/assets/SejaParceiro-TzcYpVp8.js",
    "/assets/Seminario-CJgBu3zm.js",
    "/assets/ServiceLandingSchema-BSGlVTVb.js",
    "/assets/ServiceLocalLinks-D5EOnxAY.js",
    "/assets/ServicoBairroGerado-Bbr8YF9g.js",
    "/assets/ServicoBairroTemplate-DrF_5-r0.js",
    "/assets/ServicoCidadePage-BKGVDkKs.js",
    "/assets/ServicoCore-D3oYOdOG.js",
    "/assets/Servicos-jkNStYCC.js",
    "/assets/ServicosCorrelatos-D5F0vrlq.js",
    "/assets/SeteVilas-CXTTd73F.js",
    "/assets/SitioCercado-DoIYNuIg.js",
    "/assets/Sobre-sarDJEbf.js",
    "/assets/Status-D7tEWMd7.js",
    "/assets/StatusAnuncios-Dc1xOPmH.js",
    "/assets/StatusOs-HOq0FulR.js",
    "/assets/TanguaAT-FRtMLkVX.js",
    "/assets/Taruma-CAV_GZqG.js",
    "/assets/TaxiqueiraColomboo-DUBSNGmq.js",
    "/assets/TecnicoInformaticaAlmiranteTamandare-Cst77oPw.js",
    "/assets/TecnicoInformaticaAraucaria-CDQI23cS.js",
    "/assets/TecnicoInformaticaCampoLargo-EqwfHzsc.js",
    "/assets/TecnicoInformaticaCampoMagro-DaEka9g4.js",
    "/assets/TecnicoInformaticaColombo-wW33Jea-.js",
    "/assets/TecnicoInformaticaCuritiba-DMpb3KYn.js",
    "/assets/TecnicoInformaticaCuritibaAds-lrN01zBC.js",
    "/assets/TecnicoInformaticaFazendaRioGrande-BvBiv1XI.js",
    "/assets/TecnicoInformaticaPinhais-DX02plaV.js",
    "/assets/TecnicoInformaticaPiraquara-CR8RnWq3.js",
    "/assets/TecnicoInformaticaQuatroBarras-C3rtAolW.js",
    "/assets/TecnicoInformaticaSaoJosePinhais-CdClwwY6.js",
    "/assets/TermosCondicoes-Bb5WFPld.js",
    "/assets/ThomazCoelhoAraucaria-B8kZlW8G.js",
    "/assets/ThomazCoelhoIIAraucaria-hSamZi_7.js",
    "/assets/TimbotuvaCL-DXAig6Nd.js",
    "/assets/Tindiquera-nHuGq1sz.js",
    "/assets/Tingui-CYYE1oVE.js",
    "/assets/TranqueiraAT-ier0xetK.js",
    "/assets/TresCorregosCL-BAzl3E-L.js",
    "/assets/TrustSection-DDxwCgwN.js",
    "/assets/Uberaba-DqxeZmEP.js",
    "/assets/UpgradeSsdAraucaria-iWvtW_oq.js",
    "/assets/UpgradeSsdBatel-DGJqf8Ep.js",
    "/assets/UpgradeSsdPinhais-CfOo3IYN.js",
    "/assets/UpgradeSsdSantaFelicidade-XnE0yRH4.js",
    "/assets/UpgradeSsdSaoJosePinhais-DhbaosFP.js",
    "/assets/ValeDasAguas-iyNJQfgJ.js",
    "/assets/VargemGrande-BAoU2wGi.js",
    "/assets/VilaAmeliaPinhais-_IEIbVXa.js",
    "/assets/VilaCandidaCL-BRC0GO2i.js",
    "/assets/VilaIzabel-BIkYSYmN.js",
    "/assets/VilaMacedoPiraquara-yQYuf8YG.js",
    "/assets/VilaMariaAntonietaPinhais-BIBKbnrp.js",
    "/assets/VilaMariaQB-DaOfvdpB.js",
    "/assets/VilaNovaAraucaria-Bw-xZq6y.js",
    "/assets/VilaSaoJoseQB-I56KgXiQ.js",
    "/assets/VilaSoleneCL-D7yT7S6Z.js",
    "/assets/VilaTaruma-bB12FnB_.js",
    "/assets/WeissopolisPinhais-BNCaroLg.js",
    "/assets/WhatsAppChat-BLzklagY.js",
    "/assets/WhatsAppChatbot-VXH87ZAK.js",
    "/assets/Xaxim-D_gbqzha.js",
    "/assets/accordion-CLMX6oDY.js",
    "/assets/badge-ZAWwNIgm.js",
    "/assets/blogEditorialCovers-KPd3q6kJ.js",
    "/assets/blogEditorialRegistry-CVRb4dp_.js",
    "/assets/blogPostsContent-D__akPqV.js",
    "/assets/brandsData-HmyhpRLt.js",
    "/assets/card-ClBp7NMF.js",
    "/assets/cftv-hero-C2ia0q8m.jpg",
    "/assets/cftv-hero-D_slKZ7e.js",
    "/assets/cidadesData-CX8qYqbj.js",
    "/assets/cities-CrX0xORL.js",
    "/assets/coletaConfig-DU0rO5lM.js",
    "/assets/diagnosticoChecklists--Mf6JZo0.js",
    "/assets/editorialClusters-DzoJGs5U.js",
    "/assets/gestorResponsavel-CFo91I5F.js",
    "/assets/hero-arrumar-pc-belem-1280-B1pE2Xnx.jpg",
    "/assets/hero-arrumar-pc-belem-1280-BDr07QVJ.webp",
    "/assets/hero-arrumar-pc-belem-1536-BBwPyEze.webp",
    "/assets/hero-arrumar-pc-belem-1536-_8MOwOx6.jpg",
    "/assets/hero-arrumar-pc-belem-768-B1SXGyz3.webp",
    "/assets/hero-arrumar-pc-belem-768-CNZO28Yy.jpg",
    "/assets/hero-arrumar-pc-belem-DxktoJCW.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-1280-BjEvcq3H.webp",
    "/assets/hero-arrumar-pc-belo-horizonte-1280-DuzQkDn5.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-1536-BCtFhajW.webp",
    "/assets/hero-arrumar-pc-belo-horizonte-1536-D988ollT.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-768-Djf8q7_F.webp",
    "/assets/hero-arrumar-pc-belo-horizonte-768-Drh5dpWs.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-BSxL9HHs.jpg",
    "/assets/hero-arrumar-pc-brasilia-1280-BgTzv7PE.webp",
    "/assets/hero-arrumar-pc-brasilia-1280-DKbCxALX.jpg",
    "/assets/hero-arrumar-pc-brasilia-1536-B4ozxIPs.webp",
    "/assets/hero-arrumar-pc-brasilia-1536-D-y3NcLF.jpg",
    "/assets/hero-arrumar-pc-brasilia-768-BNqbKxHx.webp",
    "/assets/hero-arrumar-pc-brasilia-768-C23vaEyT.jpg",
    "/assets/hero-arrumar-pc-brasilia-BJrG6Tzc.jpg",
    "/assets/hero-arrumar-pc-campinas-1280-B8idh88g.jpg",
    "/assets/hero-arrumar-pc-campinas-1280-OUiVQh3k.webp",
    "/assets/hero-arrumar-pc-campinas-1536-CQUOI01r.webp",
    "/assets/hero-arrumar-pc-campinas-1536-DYdUj0wm.jpg",
    "/assets/hero-arrumar-pc-campinas-768-BMU96GQX.jpg",
    "/assets/hero-arrumar-pc-campinas-768-BOqqju3R.webp",
    "/assets/hero-arrumar-pc-campinas-nHsVE00G.jpg",
    "/assets/hero-arrumar-pc-campo-grande-1280-B4jI2oDe.jpg",
    "/assets/hero-arrumar-pc-campo-grande-1280-D0_YoSWL.webp",
    "/assets/hero-arrumar-pc-campo-grande-1536-BDapa_LO.jpg",
    "/assets/hero-arrumar-pc-campo-grande-1536-Be-qe0ki.webp",
    "/assets/hero-arrumar-pc-campo-grande-768-BrFZHFxA.webp",
    "/assets/hero-arrumar-pc-campo-grande-768-CVLjn6co.jpg",
    "/assets/hero-arrumar-pc-campo-grande-TosZFSpU.jpg",
    "/assets/hero-arrumar-pc-cuiaba-1280-DOszEQMA.webp",
    "/assets/hero-arrumar-pc-cuiaba-1280-DZfe7ltx.jpg",
    "/assets/hero-arrumar-pc-cuiaba-1536-CQU8YbjU.webp",
    "/assets/hero-arrumar-pc-cuiaba-1536-D6J-fuea.jpg",
    "/assets/hero-arrumar-pc-cuiaba-768-Ba_ldpQN.jpg",
    "/assets/hero-arrumar-pc-cuiaba-768-CubeosJg.webp",
    "/assets/hero-arrumar-pc-cuiaba-BHlf2rv-.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-1280-Be_PLGlN.webp",
    "/assets/hero-arrumar-pc-curitiba-nacional-1280-D_5MBzKk.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-1536-B-ZA5Wpt.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-1536-B2lKmJSI.webp",
    "/assets/hero-arrumar-pc-curitiba-nacional-768-Ak5oHfYd.webp",
    "/assets/hero-arrumar-pc-curitiba-nacional-768-CgVG2Mr1.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-BWwBUm_G.jpg",
    "/assets/hero-arrumar-pc-florianopolis-1280-DJefZuo0.jpg",
    "/assets/hero-arrumar-pc-florianopolis-1280-jTKWhWps.webp",
    "/assets/hero-arrumar-pc-florianopolis-1536-BtX5BG-e.jpg",
    "/assets/hero-arrumar-pc-florianopolis-1536-H7Oenh5y.webp",
    "/assets/hero-arrumar-pc-florianopolis-768-CeD9bi2p.webp",
    "/assets/hero-arrumar-pc-florianopolis-768-D5f2dNq-.jpg",
    "/assets/hero-arrumar-pc-florianopolis-D14sfDAY.jpg",
    "/assets/hero-arrumar-pc-fortaleza-1280-BYIfVn80.jpg",
    "/assets/hero-arrumar-pc-fortaleza-1280-Bt5uxsol.webp",
    "/assets/hero-arrumar-pc-fortaleza-1536-CvTcUSGj.webp",
    "/assets/hero-arrumar-pc-fortaleza-1536-DzJbQpeY.jpg",
    "/assets/hero-arrumar-pc-fortaleza-768-DXi4DUct.webp",
    "/assets/hero-arrumar-pc-fortaleza-768-FBPaHVZi.jpg",
    "/assets/hero-arrumar-pc-fortaleza-wRHH5l6h.jpg",
    "/assets/hero-arrumar-pc-goiania-1280-9eigbKso.jpg",
    "/assets/hero-arrumar-pc-goiania-1280-CdS0m-GL.webp",
    "/assets/hero-arrumar-pc-goiania-1536-Qdf56Djh.jpg",
    "/assets/hero-arrumar-pc-goiania-1536-cCxfHQwi.webp",
    "/assets/hero-arrumar-pc-goiania-768-BKYsayJX.jpg",
    "/assets/hero-arrumar-pc-goiania-768-ByplqC9L.webp",
    "/assets/hero-arrumar-pc-goiania-iYlWgWMa.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-1280-Cxq_bfvV.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-1280-DK-AoGj9.webp",
    "/assets/hero-arrumar-pc-joao-pessoa-1536-1nSdR4qe.webp",
    "/assets/hero-arrumar-pc-joao-pessoa-1536-DzQj8QLv.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-768-DSNxKET9.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-768-TPlzMCEK.webp",
    "/assets/hero-arrumar-pc-joao-pessoa-DAvJEHI4.jpg",
    "/assets/hero-arrumar-pc-maceio-1280--zhzrMLG.webp",
    "/assets/hero-arrumar-pc-maceio-1280-B8h5TOIE.jpg",
    "/assets/hero-arrumar-pc-maceio-1536-Cb6-htzV.webp",
    "/assets/hero-arrumar-pc-maceio-1536-D15Mw9zd.jpg",
    "/assets/hero-arrumar-pc-maceio-768-C8x3tAYS.webp",
    "/assets/hero-arrumar-pc-maceio-768-DwrtdiIR.jpg",
    "/assets/hero-arrumar-pc-maceio-CVITa_VZ.jpg",
    "/assets/hero-arrumar-pc-manaus-1280-DXKrdiXk.jpg",
    "/assets/hero-arrumar-pc-manaus-1280-LPRsJc3O.webp",
    "/assets/hero-arrumar-pc-manaus-1536-BVC4euou.webp",
    "/assets/hero-arrumar-pc-manaus-1536-JSa2FuIw.jpg",
    "/assets/hero-arrumar-pc-manaus-768-DLlwWGqZ.webp",
    "/assets/hero-arrumar-pc-manaus-768-LvjUtfMr.jpg",
    "/assets/hero-arrumar-pc-manaus-CX14Fnfy.jpg",
    "/assets/hero-arrumar-pc-natal-1280-DpYNYWEc.jpg",
    "/assets/hero-arrumar-pc-natal-1280-dv-EJwW6.webp",
    "/assets/hero-arrumar-pc-natal-1536-DF_RbzZf.jpg",
    "/assets/hero-arrumar-pc-natal-1536-DQmHdSt8.webp",
    "/assets/hero-arrumar-pc-natal-768-5esMPnYy.webp",
    "/assets/hero-arrumar-pc-natal-768-DJ98N1On.jpg",
    "/assets/hero-arrumar-pc-natal-D_GghYn2.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-1280-DNLI6ls5.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-1280-Dtpfn-sZ.webp",
    "/assets/hero-arrumar-pc-porto-alegre-1536-CLbxAsmF.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-1536-KnbkDg90.webp",
    "/assets/hero-arrumar-pc-porto-alegre-768-BOXam7Lf.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-768-Bf1DIKYd.webp",
    "/assets/hero-arrumar-pc-porto-alegre-C1HXpLeH.jpg",
    "/assets/hero-arrumar-pc-recife-1280-BuF3jnPO.jpg",
    "/assets/hero-arrumar-pc-recife-1280-U34QHSDJ.webp",
    "/assets/hero-arrumar-pc-recife-1536-C2bRnBek.webp",
    "/assets/hero-arrumar-pc-recife-1536-UmGWnRhs.jpg",
    "/assets/hero-arrumar-pc-recife-768-Bve6S0N8.jpg",
    "/assets/hero-arrumar-pc-recife-768-CDCVyTKs.webp",
    "/assets/hero-arrumar-pc-recife-ByaKL3AR.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1280-Ch6Ju853.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1280-D-VF46hJ.webp",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1536-CLS2aK4R.webp",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1536-DOZOhL2f.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-768-BPWerF76.webp",
    "/assets/hero-arrumar-pc-rio-de-janeiro-768-uJTXjCtx.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-DIU38_Kc.jpg",
    "/assets/hero-arrumar-pc-salvador-1280-Dy-EHWlJ.jpg",
    "/assets/hero-arrumar-pc-salvador-1280-zvzVtimH.webp",
    "/assets/hero-arrumar-pc-salvador-1536-BsqjXETZ.webp",
    "/assets/hero-arrumar-pc-salvador-1536-CJN5X22Q.jpg",
    "/assets/hero-arrumar-pc-salvador-768-BEnlrXym.webp",
    "/assets/hero-arrumar-pc-salvador-768-BrUyiC20.jpg",
    "/assets/hero-arrumar-pc-salvador-pyYTkeL7.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-1280-BgrMWAzd.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-1280-DMXNT82x.webp",
    "/assets/hero-arrumar-pc-sao-paulo-1536-BX8gJuVx.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-1536-CPlriY0v.webp",
    "/assets/hero-arrumar-pc-sao-paulo-768--F4CiZVy.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-768-BDYo1f9p.webp",
    "/assets/hero-arrumar-pc-sao-paulo-UqvB6GPs.jpg",
    "/assets/hero-arrumar-pc-vitoria-1280-B8EbfrVj.webp",
    "/assets/hero-arrumar-pc-vitoria-1280-D3vxeyqV.jpg",
    "/assets/hero-arrumar-pc-vitoria-1536-BAkEkapH.webp",
    "/assets/hero-arrumar-pc-vitoria-1536-BQZenwLq.jpg",
    "/assets/hero-arrumar-pc-vitoria-768-B5Y_HUpe.webp",
    "/assets/hero-arrumar-pc-vitoria-768-CuncjJhZ.jpg",
    "/assets/hero-arrumar-pc-vitoria-ysV1gJDF.jpg",
    "/assets/imageCredits-Mj9moAfo.js",
    "/assets/images-JaXLmvFV.js",
    "/assets/index-B33dId_v.css",
    "/assets/index-BrZgr-mZ.js",
    "/assets/index-CDbz7DPB.js",
    "/assets/index-OTcgXMep.css",
    "/assets/indexingPolicy-CwG_VZLi.js",
    "/assets/label-C7q87PVl.js",
    "/assets/og-arrumar-pc-belem-Baw5HNjK.jpg",
    "/assets/og-arrumar-pc-belo-horizonte-Dzo9gC4g.jpg",
    "/assets/og-arrumar-pc-brasil-CubHo-x4.jpg",
    "/assets/og-arrumar-pc-brasilia-zPwVmPff.jpg",
    "/assets/og-arrumar-pc-campinas-C9AjH1L9.jpg",
    "/assets/og-arrumar-pc-campo-grande-BEDxfEwN.jpg",
    "/assets/og-arrumar-pc-cuiaba-D3pFMUV_.jpg",
    "/assets/og-arrumar-pc-curitiba-nacional-DeURmIkp.jpg",
    "/assets/og-arrumar-pc-florianopolis-DLdHSpz8.jpg",
    "/assets/og-arrumar-pc-fortaleza-Byw-lRGT.jpg",
    "/assets/og-arrumar-pc-goiania-Ql2v0KVb.jpg",
    "/assets/og-arrumar-pc-joao-pessoa-B4RnoMoj.jpg",
    "/assets/og-arrumar-pc-maceio-BRkoRhdb.jpg",
    "/assets/og-arrumar-pc-manaus-CmkkcZCu.jpg",
    "/assets/og-arrumar-pc-natal-DLotTjYz.jpg",
    "/assets/og-arrumar-pc-porto-alegre-D30G9ffS.jpg",
    "/assets/og-arrumar-pc-recife-Bs68c_MX.jpg",
    "/assets/og-arrumar-pc-rio-de-janeiro-DbixX1zN.jpg",
    "/assets/og-arrumar-pc-salvador-UgtH5GH8.jpg",
    "/assets/og-arrumar-pc-sao-paulo-DeK1gSYG.jpg",
    "/assets/og-arrumar-pc-vitoria-xGC6Okn6.jpg",
    "/assets/ogCacheBust-DRi2zEuh.js",
    "/assets/osRegistry-Cr0vtKoF.js",
    "/assets/pdfDoc-YJCpx3Yv.js",
    "/assets/politicaMontagem-BySdpwLJ.js",
    "/assets/precosConfig-Cg3IOUYm.js",
    "/assets/problemaPagesData-DLKy5Ig3.js",
    "/assets/qaExclusion-D7qRVf-a.js",
    "/assets/reviewRequest-CZGyeHRA.js",
    "/assets/select-qWYIhE28.js",
    "/assets/servicoCidadeData-CMGzgn25.js",
    "/assets/servicosCore-Dte_97yH.js",
    "/assets/sonner-B89fBO1c.js",
    "/assets/toaster-CwsWsSpF.js",
    "/assets/use-toast-DwTQcbAP.js",
    "/assets/useAdminAuth-C0uLS4m8.js",
    "/assets/vendor-WeafOKnK.js",
    "/assets/visualEmpresarial3s-BbE7P-Lj.js",
    "/assets/webVitals-B_eXv0Ru.js",
    "/assets/whatsappUtm-B8YHP6iy.js",
    "/assets/wifiTvBairroData-DrYbq0Ho.js",
    "/assets/windows-11-kb5074105-update-CNLAHtC2.jpg",
    "/blog/backup-como-proteger-seus-arquivos.jpg",
    "/blog/como-escolher-uma-workstation.jpg",
    "/blog/como-melhorar-sinal-wifi-em-casa.jpg",
    "/blog/como-saber-se-pc-tem-virus-malware.jpg",
    "/blog/computador-lento-causas-solucoes.jpg",
    "/blog/notebook-nao-liga-o-que-fazer.jpg",
    "/blog/notebook-superaquecendo-o-que-fazer.jpg",
    "/blog/organizacao-de-ti-para-pequenos-escritorios.jpg",
    "/blog/quando-trocar-hd-por-ssd.jpg",
    "/build-status.json",
    "/css/style.css",
    "/dynamic-slugs.json",
    "/f783ab585dfa9e6b017cb058009cccae.txt",
    "/favicon-20260624.ico",
    "/favicon-20260624.png",
    "/favicon-32-20260624.png",
    "/favicon-32.png",
    "/favicon.ico",
    "/favicon.png",
    "/fonts/montserrat-var.woff2",
    "/fonts/poppins-600.woff2",
    "/fonts/poppins-700.woff2",
    "/icon-512.png",
    "/llms-full.txt",
    "/llms.txt",
    "/logo-dark.png",
    "/logo-dark.webp",
    "/logo.png",
    "/logo.webp",
    "/lovable-uploads/1c69699b-770f-4ea3-bd50-34bb6823a3b5.png",
    "/lovable-uploads/22325e55-7640-4775-99b0-4d43b5cad21d.png",
    "/lovable-uploads/279c1746-6e5b-4d0e-93d4-976d837ecec0.png",
    "/lovable-uploads/53d9783d-317d-495e-86b6-22371a986744.png",
    "/lovable-uploads/727e8770-4368-4aa5-a5a5-e495f01d9124.png",
    "/lovable-uploads/7364f9af-20c4-4e14-8105-585235697ca1.png",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-240.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-360.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-480.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-800.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859.png",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859.webp",
    "/lovable-uploads/829c2c24-8525-4b99-8cad-42c8cfc83a91.png",
    "/lovable-uploads/87899615-1234-4c6d-a8ca-ee38ec566ef4.png",
    "/lovable-uploads/87899615-1234-4c6d-a8ca-ee38ec566ef4.webp",
    "/lovable-uploads/97228481-0bbd-4d82-a9aa-bcc0212e1c7b.png",
    "/lovable-uploads/b2277aaf-f886-48c7-822a-6a5d1e266855.png",
    "/lovable-uploads/b702f033-fd78-4d1e-ae32-2ad60f672710.png",
    "/lovable-uploads/b702f033-fd78-4d1e-ae32-2ad60f672710.webp",
    "/lovable-uploads/c858cf99-e05f-4d8f-a05a-c741ebfabfea.png",
    "/lovable-uploads/c858cf99-e05f-4d8f-a05a-c741ebfabfea.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302-1200.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302-400.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302-800.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302.jpg",
    "/lovable-uploads/cover-celular-curitiba.jpg",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89-1200.webp",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89-400.webp",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89-800.webp",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89.jpg",
    "/lovable-uploads/cover-wifi-curitiba.jpg",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b-1200.webp",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b-400.webp",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b-800.webp",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b.jpg",
    "/lovable-uploads/cover-windows-curitiba.jpg",
    "/lovable-uploads/f6b6dc27-d68d-4f00-9c1f-c407ef986264.png",
    "/lovable-uploads/ff1b2738-e2a0-4b39-bdb7-47b8b71e33cb.png",
    "/manifest.json",
    "/midia-kit-tecnico-curitiba.pdf",
    "/og-image.png",
    "/placeholder.svg",
    "/robots.txt",
    "/sitemap-bairros.xml",
    "/sitemap-editorial.xml",
    "/sitemap-index.xml",
    "/sitemap-main.xml",
    "/sitemap-marcas.xml",
    "/sitemap-news.xml",
    "/sitemap-problemas.xml",
    "/sitemap-regioes.xml",
    "/sitemap-servicos.xml",
    "/sitemap.xml"
  ],
  curated: [
    "/",
    "/anuncie",
    "/areas-atendidas",
    "/atendimento-domicilio",
    "/atendimento-remoto",
    "/bairros/agua-verde",
    "/bairros/batel",
    "/bairros/centro",
    "/bairros/cic",
    "/bairros/portao",
    "/blog",
    "/blog/backup-como-proteger-seus-arquivos",
    "/blog/como-escolher-uma-workstation",
    "/blog/como-melhorar-sinal-wifi-em-casa",
    "/blog/como-saber-se-pc-tem-virus-malware",
    "/blog/notebook-superaquecendo-o-que-fazer",
    "/blog/organizacao-de-ti-para-pequenos-escritorios",
    "/blog/quando-trocar-hd-por-ssd",
    "/coleta-e-entrega",
    "/como-funciona",
    "/contato",
    "/diagnostico-tecnico",
    "/empresa-de-ti-curitiba",
    "/equipamentos-atendidos",
    "/faq",
    "/guia-tecnico-informatica",
    "/politica-de-pecas-do-cliente",
    "/precos-e-politicas",
    "/problemas/computador-lento",
    "/problemas/notebook-nao-liga",
    "/quando-nao-compensa",
    "/seguranca-dos-dados",
    "/servicos",
    "/servicos/backup-para-empresas",
    "/servicos/conserto-monitor",
    "/servicos/conserto-placa",
    "/servicos/conserto-tv",
    "/servicos/formatacao",
    "/servicos/manutencao-de-computador",
    "/servicos/manutencao-de-notebook",
    "/servicos/manutencao-preventiva-empresas",
    "/servicos/montagem-de-pc",
    "/servicos/pc-gamer",
    "/servicos/recuperacao-de-dados",
    "/servicos/redes-e-wifi",
    "/servicos/remocao-de-virus",
    "/servicos/suporte-home-office",
    "/servicos/suporte-tecnico-empresarial",
    "/servicos/upgrade-ssd-ram",
    "/sobre",
    "/tecnico-informatica-araucaria",
    "/tecnico-informatica-campo-largo",
    "/tecnico-informatica-colombo",
    "/tecnico-informatica-curitiba",
    "/tecnico-informatica-pinhais",
    "/tecnico-informatica-sao-jose-pinhais"
  ]
};

// worker.js
import notFoundHtml from "./665111f8ceeff9100311e69d3438110498df7921-404.html";

// ../scripts/lib/site-env.mjs
import { readFileSync, existsSync } from "node:fs";
var fileEnv = {};
for (const f of [".env.local", ".env"]) {
  if (!existsSync(f)) continue;
  for (const line of readFileSync(f, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (!m) continue;
    const key = m[1];
    if (key in fileEnv) continue;
    fileEnv[key] = m[2].trim().replace(/^["']|["']$/g, "");
  }
}
var env = { ...fileEnv, ...process.env };
var clean = /* @__PURE__ */ __name((v) => typeof v === "string" && v.trim() ? v.trim() : "", "clean");
var SITE_DOMAIN = clean(env.VITE_SITE_DOMAIN);
var SITE_CONFIGURED = Boolean(SITE_DOMAIN);
var BASE_URL = SITE_CONFIGURED ? `https://${SITE_DOMAIN}` : "";
var INDEXING_ENABLED = SITE_CONFIGURED && clean(env.VITE_SITE_INDEXING_ENABLED).toLowerCase() === "true";
var BRAND_NAME = clean(env.VITE_BRAND_NAME) || "O T\xE9cnico de Inform\xE1tica";
var wa = clean(env.VITE_WHATSAPP_NUMBER);
var WHATSAPP_NUMBER = /^\d{12,15}$/.test(wa) ? wa : "";
var WHATSAPP_CONFIGURED = Boolean(WHATSAPP_NUMBER);
var DAY_NAMES = { Mo: "Monday", Tu: "Tuesday", We: "Wednesday", Th: "Thursday", Fr: "Friday", Sa: "Saturday", Su: "Sunday" };
var DAY_ORDER = Object.keys(DAY_NAMES);
var DEFAULT_BUSINESS_HOURS = "";
var BUSINESS_HOURS_SPEC = clean(env.VITE_BUSINESS_HOURS) || DEFAULT_BUSINESS_HOURS;
function parseBusinessHours(spec) {
  const out = [];
  for (const part of String(spec).split(";")) {
    const m = part.trim().match(/^([A-Za-z,\-]+)\s+(\d{2}:\d{2})-(\d{2}:\d{2})$/);
    if (!m) continue;
    const days = [];
    for (const token of m[1].split(",")) {
      const range = token.split("-");
      if (range.length === 2) {
        const from = DAY_ORDER.indexOf(range[0]);
        const to = DAY_ORDER.indexOf(range[1]);
        if (from < 0 || to < 0 || to < from) continue;
        for (let i = from; i <= to; i += 1) days.push(DAY_NAMES[DAY_ORDER[i]]);
      } else if (DAY_NAMES[token]) days.push(DAY_NAMES[token]);
    }
    if (days.length) out.push({ "@type": "OpeningHoursSpecification", dayOfWeek: days, opens: m[2], closes: m[3] });
  }
  return out;
}
__name(parseBusinessHours, "parseBusinessHours");
var OPENING_HOURS = parseBusinessHours(BUSINESS_HOURS_SPEC);
var GA4_ID = clean(env.VITE_GA4_ID);
var GOOGLE_ADS_ID = clean(env.VITE_GOOGLE_ADS_ID);
var GOOGLE_ADS_CONVERSION_LABEL = clean(env.VITE_GOOGLE_ADS_CONVERSION_LABEL);
var ADSENSE_PUBLISHER_ID = clean(env.ADSENSE_PUBLISHER_ID);

// ../scripts/lib/edge-router.mjs
var ORIGIN_PLACEHOLDER = "LOVABLE_ORIGIN_NOT_CONFIGURED";
var ALLOWED_HOSTS = [SITE_DOMAIN, `www.${SITE_DOMAIN}`];
var HEALTH_PATH = "/__edge/health";
function healthPayload(compiled2, manifest, problems = []) {
  return {
    service: "route-guard",
    status: problems.length ? "degraded" : "ok",
    build: {
      generatedAt: manifest?.generatedAt ?? null,
      source: manifest?.source ?? null
    },
    manifest: {
      ok: problems.length === 0,
      problems,
      minimums: MANIFEST_MINIMUMS
    },
    counts: {
      validExact: compiled2.counts.validExact,
      openPatterns: compiled2.openPatterns.length,
      redirects: compiled2.counts.redirects,
      assetFiles: compiled2.counts.assetFiles
    },
    checkedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
}
__name(healthPayload, "healthPayload");
var MANIFEST_MINIMUMS = {
  validExact: 200,
  redirects: 1,
  assetFiles: 5
};
function normalizePath(rawPath) {
  if (typeof rawPath !== "string" || rawPath === "") return null;
  let p = rawPath;
  if (!p.startsWith("/")) return null;
  if (/[\u0000-\u001f\u007f]/.test(p)) return null;
  try {
    p = decodeURIComponent(p);
  } catch {
    return null;
  }
  if (/[\u0000-\u001f\u007f]/.test(p)) return null;
  const out = [];
  for (const seg of p.split("/")) {
    if (seg === "" || seg === ".") continue;
    if (seg === "..") {
      if (out.length === 0) return null;
      out.pop();
      continue;
    }
    out.push(seg);
  }
  const normalized = `/${out.join("/")}`;
  return normalized === "/" ? "/" : normalized.replace(/\/+$/, "");
}
__name(normalizePath, "normalizePath");
function compileManifest(manifest) {
  if (!manifest || typeof manifest !== "object") throw new Error("manifesto ausente");
  const exact = new Set((manifest.validExact ?? []).map((p) => normalizePath(p) ?? p));
  const patternInfo = manifest.patternInfo ?? (manifest.validPatterns ?? []).map((pattern) => ({ pattern, closed: false }));
  const openPatterns = patternInfo.filter((p) => !p.closed).map((p) => pathToRegex(p.pattern));
  const redirects = /* @__PURE__ */ new Map();
  for (const r of manifest.redirects ?? []) {
    const from = normalizePath(r.from ?? r[0]);
    if (from) redirects.set(from, r.to ?? r[1]);
  }
  const assetFiles = new Set((manifest.assetFiles ?? []).map((f) => f.startsWith("/") ? f : `/${f}`));
  return {
    exact,
    openPatterns,
    redirects,
    assetFiles,
    counts: {
      validExact: exact.size,
      redirects: redirects.size,
      assetFiles: assetFiles.size
    }
  };
}
__name(compileManifest, "compileManifest");
function pathToRegex(routePath) {
  const source = routePath.split("/").filter(Boolean).map((seg) => seg === "*" || seg.startsWith(":") ? "[^/]+" : seg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("/");
  return new RegExp(`^/${source}/?$`);
}
__name(pathToRegex, "pathToRegex");
function assertManifestSane(compiled2) {
  const problems = [];
  for (const [key, min] of Object.entries(MANIFEST_MINIMUMS)) {
    if (compiled2.counts[key] < min) problems.push(`${key}=${compiled2.counts[key]} < m\xEDnimo ${min}`);
  }
  return problems;
}
__name(assertManifestSane, "assertManifestSane");
var looksLikeFile = /* @__PURE__ */ __name((p) => /\.[a-z0-9]{1,8}$/i.test(p), "looksLikeFile");
function decide(req, m) {
  const host = String(req.host ?? "").toLowerCase().split(":")[0];
  if (!ALLOWED_HOSTS.includes(host)) return { action: "reject", status: 421, reason: "host-nao-permitido" };
  if (host === `www.${SITE_DOMAIN}`) {
    const rawPath = typeof req.pathname === "string" && req.pathname.startsWith("/") ? req.pathname : "/";
    return {
      action: "redirect",
      status: 308,
      location: `${BASE_URL}${rawPath}${req.search ?? ""}`,
      reason: "www-para-apex"
    };
  }
  const pathname = normalizePath(req.pathname);
  if (pathname === null) return { action: "notfound", status: 404, reason: "path-malformado" };
  const search = req.search ?? "";
  const target = m.redirects.get(pathname);
  if (target) {
    const location = target.includes("?") || !search ? target : `${target}${search}`;
    return { action: "redirect", status: 301, location, reason: "alias" };
  }
  if (looksLikeFile(pathname)) {
    if (m.assetFiles.has(pathname)) return { action: "asset", status: 200, reason: "asset-existente" };
    return { action: "notfound", status: 404, reason: "asset-inexistente" };
  }
  if (m.exact.has(pathname) || m.openPatterns.some((re) => re.test(pathname))) {
    return { action: "proxy", status: 200, reason: "rota-valida" };
  }
  return { action: "notfound", status: 404, reason: "rota-inexistente" };
}
__name(decide, "decide");

// worker.js
var compiled = compileManifest(route_manifest_default);
var manifestProblems = assertManifestSane(compiled);
var NOT_FOUND_HEADERS = {
  "content-type": "text/html; charset=UTF-8",
  "cache-control": "no-store",
  "x-robots-tag": "noindex, nofollow"
};
function notFound(method) {
  const body = method === "HEAD" ? null : notFoundHtml;
  return new Response(body, { status: 404, headers: NOT_FOUND_HEADERS });
}
__name(notFound, "notFound");
var worker_default = {
  async fetch(request, env2) {
    const url = new URL(request.url);
    if (url.pathname === HEALTH_PATH) {
      return new Response(JSON.stringify(healthPayload(compiled, route_manifest_default, manifestProblems), null, 2), {
        status: manifestProblems.length ? 503 : 200,
        headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-robots-tag": "noindex, nofollow" }
      });
    }
    if (manifestProblems.length) {
      return new Response("edge desabilitado: manifesto inv\xE1lido", { status: 503 });
    }
    const d = decide({ host: url.hostname, method: request.method, pathname: url.pathname, search: url.search }, compiled);
    if (d.action === "reject") return new Response("host n\xE3o atendido", { status: 421 });
    if (d.action === "redirect") {
      const location = new URL(d.location, url.origin).toString();
      return new Response(null, {
        status: d.status === 308 ? 308 : 301,
        headers: { location, "cache-control": "public, max-age=86400" }
      });
    }
    if (d.action === "notfound") return notFound(request.method);
    const mode = env2?.ORIGIN_MODE ?? "dns";
    if (mode === "dns") return fetch(request);
    const origin = env2?.LOVABLE_ORIGIN ?? ORIGIN_PLACEHOLDER;
    if (origin === ORIGIN_PLACEHOLDER) {
      return new Response("origem n\xE3o configurada", { status: 503 });
    }
    const target = new URL(url.pathname + url.search, `https://${origin}`);
    const proxied = new Request(target.toString(), request);
    proxied.headers.set("host", origin);
    proxied.headers.set("x-forwarded-host", url.hostname);
    return fetch(proxied);
  }
};
export {
  worker_default as default
};
//# sourceMappingURL=worker.js.map
