var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// ../dist/route-manifest.json
var route_manifest_default = {
  generatedAt: "2026-08-06T06:42:53.812Z",
  source: "scripts/lib/route-manifest.mjs (derivado \u2014 n\xE3o editar \xE0 m\xE3o)",
  counts: {
    validExact: 1032,
    validPatterns: 11,
    redirects: 35,
    prerendered: 311,
    dynamicSlugs: 404,
    curated: 51,
    assetFiles: 700,
    private: 7
  },
  validExact: [
    "/",
    "/admin",
    "/admin/dashboard",
    "/admin/funnel",
    "/admin/login",
    "/admin/reviews",
    "/admin/vitals",
    "/ads/tecnico-informatica-curitiba",
    "/arrumar-pc",
    "/arrumar-pc/belem",
    "/arrumar-pc/belo-horizonte",
    "/arrumar-pc/brasilia",
    "/arrumar-pc/campinas",
    "/arrumar-pc/campo-grande",
    "/arrumar-pc/cuiaba",
    "/arrumar-pc/curitiba-nacional",
    "/arrumar-pc/florianopolis",
    "/arrumar-pc/fortaleza",
    "/arrumar-pc/goiania",
    "/arrumar-pc/joao-pessoa",
    "/arrumar-pc/maceio",
    "/arrumar-pc/manaus",
    "/arrumar-pc/natal",
    "/arrumar-pc/online",
    "/arrumar-pc/porto-alegre",
    "/arrumar-pc/recife",
    "/arrumar-pc/rio-de-janeiro",
    "/arrumar-pc/salvador",
    "/arrumar-pc/sao-paulo",
    "/arrumar-pc/vitoria",
    "/assistencia-eletrodomesticos-inteligentes-curitiba",
    "/assistencia-tecnica-curitiba",
    "/atendimento-domicilio",
    "/atendimento-remoto",
    "/bairros/academia-sjp",
    "/bairros/afonso-pena",
    "/bairros/agricola-sjp",
    "/bairros/agua-verde",
    "/bairros/alto-boqueirao",
    "/bairros/alto-da-gloria",
    "/bairros/alto-maracana",
    "/bairros/alto-taruma",
    "/bairros/antonio-olivero-cm",
    "/bairros/aristocrata",
    "/bairros/atuba-colombo",
    "/bairros/atuba-pinhais",
    "/bairros/aviacao",
    "/bairros/bacacheri",
    "/bairros/barigui-araucaria",
    "/bairros/barro-preto",
    "/bairros/bateias",
    "/bairros/batel",
    "/bairros/bigorrilho",
    "/bairros/boa-vista",
    "/bairros/boa-vista-at",
    "/bairros/boneca-do-iguacu-sjp",
    "/bairros/boqueirao",
    "/bairros/boqueirao-araucaria",
    "/bairros/borda-campo-sjp",
    "/bairros/borda-do-campo-qb",
    "/bairros/borda-do-campo-sjp",
    "/bairros/botiatuva",
    "/bairros/botiatuva-cm",
    "/bairros/braga",
    "/bairros/cabral",
    "/bairros/cachoeira-araucaria",
    "/bairros/cachoeira-at",
    "/bairros/caiua-piraquara",
    "/bairros/cajuru",
    "/bairros/california-araucaria",
    "/bairros/campina-da-barra",
    "/bairros/campina-grande-colombo",
    "/bairros/campo-comprido",
    "/bairros/campo-largo-roseira-sjp",
    "/bairros/campo-pequeno",
    "/bairros/campo-tenente-at",
    "/bairros/capao-da-imbuia",
    "/bairros/capela-velha",
    "/bairros/centro",
    "/bairros/centro-almirante-tamandare",
    "/bairros/centro-araucaria",
    "/bairros/centro-campo-largo",
    "/bairros/centro-campo-magro",
    "/bairros/centro-colombo",
    "/bairros/centro-fazenda-rio-grande",
    "/bairros/centro-pinhais",
    "/bairros/centro-piraquara",
    "/bairros/centro-quatro-barras",
    "/bairros/chapada",
    "/bairros/cic",
    "/bairros/cidade-jardim-sjp",
    "/bairros/colonia-antonio-prado",
    "/bairros/colonia-malhada-cl",
    "/bairros/colonia-murici-sjp",
    "/bairros/correia-de-freitas",
    "/bairros/costeira",
    "/bairros/costeira-araucaria",
    "/bairros/cristo-rei",
    "/bairros/cruzeiro",
    "/bairros/del-rey",
    "/bairros/embu-colombo",
    "/bairros/emiliano-perneta",
    "/bairros/espigao-alegre-cm",
    "/bairros/estacao-araucaria",
    "/bairros/estancia-pinhais",
    "/bairros/eucaliptos-frg",
    "/bairros/fatima-colombo",
    "/bairros/fazenda-velha-araucaria",
    "/bairros/fazendinha",
    "/bairros/ferraria",
    "/bairros/gabirobal",
    "/bairros/graciosa",
    "/bairros/graciosa-qb",
    "/bairros/gralha-azul",
    "/bairros/guajuvira",
    "/bairros/guaraituba-colombo",
    "/bairros/guarituba-piraquara",
    "/bairros/guatupe",
    "/bairros/hauer",
    "/bairros/hortencia-frg",
    "/bairros/hugo-lange",
    "/bairros/iguacu-araucaria",
    "/bairros/iguacu-frg",
    "/bairros/independencia-sjp",
    "/bairros/industrial-araucaria",
    "/bairros/ipe-sjp",
    "/bairros/irai-piraquara",
    "/bairros/italia-sjp",
    "/bairros/itaqui",
    "/bairros/jardim-amelia",
    "/bairros/jardim-america-campo-largo",
    "/bairros/jardim-bela-vista-piraquara",
    "/bairros/jardim-boa-vista-araucaria",
    "/bairros/jardim-boa-vista-cm",
    "/bairros/jardim-botanico",
    "/bairros/jardim-claudia",
    "/bairros/jardim-claudia-ii-pinhais",
    "/bairros/jardim-condor-frg",
    "/bairros/jardim-das-americas",
    "/bairros/jardim-das-pedras-frg",
    "/bairros/jardim-dona-rosa-pinhais",
    "/bairros/jardim-esperanca-cl",
    "/bairros/jardim-esplanada-pinhais",
    "/bairros/jardim-estados",
    "/bairros/jardim-florestal-qb",
    "/bairros/jardim-graziela",
    "/bairros/jardim-guilhermina",
    "/bairros/jardim-iguacu-araucaria",
    "/bairros/jardim-ipe-frg",
    "/bairros/jardim-japao-qb",
    "/bairros/jardim-karla-pinhais",
    "/bairros/jardim-laranjeiras-cl",
    "/bairros/jardim-menino-deus-qb",
    "/bairros/jardim-monte-santo",
    "/bairros/jardim-novo-horizonte-cl",
    "/bairros/jardim-osasco",
    "/bairros/jardim-paraiso-at",
    "/bairros/jardim-paranagua-at",
    "/bairros/jardim-pedro-demeterco",
    "/bairros/jardim-planalto-campo-largo",
    "/bairros/jardim-planalto-ii-cl",
    "/bairros/jardim-primavera-piraquara",
    "/bairros/jardim-roma",
    "/bairros/jardim-santo-antonio-piraquara",
    "/bairros/jardim-sao-jorge-at",
    "/bairros/jardim-sao-paulo-piraquara",
    "/bairros/jardim-shangrila-araucaria",
    "/bairros/jardim-social",
    "/bairros/jardim-tropical-pinhais",
    "/bairros/jardim-uniao-piraquara",
    "/bairros/jardim-wissinger-pinhais",
    "/bairros/joquei-clube-cm",
    "/bairros/juveve",
    "/bairros/lamenha-grande-cl",
    "/bairros/maracana-colombo",
    "/bairros/maria-antonieta",
    "/bairros/merces",
    "/bairros/monza-colombo",
    "/bairros/nacoes-frg",
    "/bairros/novo-mundo",
    "/bairros/osvaldo-cruz-colombo",
    "/bairros/ouro-fino",
    "/bairros/ouro-fino-sjp",
    "/bairros/palmital-campo-largo",
    "/bairros/palmital-colombo",
    "/bairros/palmital-pinhais",
    "/bairros/parque-da-fonte",
    "/bairros/parque-industrial-frg",
    "/bairros/parque-nascentes-pinhais",
    "/bairros/passauna",
    "/bairros/pedro-moro-sjp",
    "/bairros/pineville",
    "/bairros/pinheirinho",
    "/bairros/pioneiros-frg",
    "/bairros/planta-deodoro-piraquara",
    "/bairros/planta-sao-tiago-araucaria",
    "/bairros/portao",
    "/bairros/porto-das-laranjeiras",
    "/bairros/prado-velho-piraquara",
    "/bairros/quississana-sjp",
    "/bairros/reboucas",
    "/bairros/rio-pequeno-sjp",
    "/bairros/rio-verde-cm",
    "/bairros/roca-grande",
    "/bairros/rondinha",
    "/bairros/sabia",
    "/bairros/santa-cruz-campo-largo",
    "/bairros/santa-felicidade",
    "/bairros/santa-terezinha-colombo",
    "/bairros/santa-terezinha-frg",
    "/bairros/sao-cristao-piraquara",
    "/bairros/sao-cristovao",
    "/bairros/sao-dimas-colombo",
    "/bairros/sao-domingos",
    "/bairros/sao-francisco",
    "/bairros/sao-gabriel-colombo",
    "/bairros/sao-jose-campo-largo",
    "/bairros/sao-jose-dos-pinhais",
    "/bairros/sao-lourenco-frg",
    "/bairros/sao-lourenco-qb",
    "/bairros/sao-marcos",
    "/bairros/sao-marcos-campo-largo",
    "/bairros/sao-miguel-araucaria",
    "/bairros/sao-sebastiao-cm",
    "/bairros/sao-silvestre",
    "/bairros/sao-venancio",
    "/bairros/sede-campo-magro",
    "/bairros/seminario",
    "/bairros/sete-vilas",
    "/bairros/sitio-cercado",
    "/bairros/tangua-at",
    "/bairros/taruma",
    "/bairros/taxiqueira-colombo",
    "/bairros/thomaz-coelho",
    "/bairros/thomaz-coelho-ii",
    "/bairros/timbotuva-cl",
    "/bairros/tindiquera",
    "/bairros/tingui",
    "/bairros/tranqueira-at",
    "/bairros/tres-corregos",
    "/bairros/uberaba",
    "/bairros/vale-das-aguas",
    "/bairros/vargem-grande",
    "/bairros/vila-amelia-pinhais",
    "/bairros/vila-candida-cl",
    "/bairros/vila-izabel",
    "/bairros/vila-macedo-piraquara",
    "/bairros/vila-maria-antonieta-pinhais",
    "/bairros/vila-maria-qb",
    "/bairros/vila-nova-araucaria",
    "/bairros/vila-sao-jose-qb",
    "/bairros/vila-solene",
    "/bairros/vila-taruma",
    "/bairros/weissopolis",
    "/bairros/xaxim",
    "/blog",
    "/blog/automatizar-tarefas-com-ia-n8n-make",
    "/blog/backup-como-proteger-seus-arquivos",
    "/blog/backup-nuvem-empresas-qual-escolher",
    "/blog/comandos-linux-essenciais-iniciantes",
    "/blog/como-atualizar-windows-corretamente",
    "/blog/como-aumentar-velocidade-internet",
    "/blog/como-bloquear-acesso-internet-criancas",
    "/blog/como-bloquear-numero-celular",
    "/blog/como-cadastrar-preciso-de-um",
    "/blog/como-clonar-hd-para-ssd",
    "/blog/como-clonar-hd-para-ssd-passo-a-passo",
    "/blog/como-conectar-celular-tv",
    "/blog/como-conectar-wifi-tv-nao-conecta",
    "/blog/como-configurar-2fa-em-tudo",
    "/blog/como-configurar-active-directory",
    "/blog/como-configurar-backup-automatizado",
    "/blog/como-configurar-bios-uefi-corretamente",
    "/blog/como-configurar-cron-jobs-linux",
    "/blog/como-configurar-firewall-pfsense",
    "/blog/como-configurar-firewall-ufw-linux",
    "/blog/como-configurar-rede-linux-netplan",
    "/blog/como-configurar-rede-wifi-empresarial",
    "/blog/como-configurar-repetidor-wifi",
    "/blog/como-configurar-roteador-wifi-iniciantes",
    "/blog/como-configurar-servidor-de-arquivos",
    "/blog/como-configurar-servidor-web-apache-nginx-linux",
    "/blog/como-configurar-ssh-seguro-linux",
    "/blog/como-configurar-vlan-rede-corporativa",
    "/blog/como-configurar-vpn-empresarial",
    "/blog/como-criar-conta-usuario-windows-criancas",
    "/blog/como-criar-imagens-com-stable-diffusion",
    "/blog/como-criar-prompts-eficazes-chatgpt",
    "/blog/como-criar-script-bash-iniciantes",
    "/blog/como-crimpar-cabo-de-rede-rj45",
    "/blog/como-deixar-celular-android-mais-rapido",
    "/blog/como-deixar-computador-mais-rapido",
    "/blog/como-deixar-windows-11-mais-rapido-iniciantes",
    "/blog/como-detectar-invasao-rede",
    "/blog/como-diagnosticar-placa-mae-defeituosa",
    "/blog/como-economizar-bateria-celular",
    "/blog/como-escolher-melhor-kit-cameras-seguranca",
    "/blog/como-escolher-um-bom-antivirus",
    "/blog/como-fazer-backup-celular-android",
    "/blog/como-fazer-backup-completo-windows-11",
    "/blog/como-fazer-backup-fotos-windows-iniciantes",
    "/blog/como-fazer-backup-na-nuvem",
    "/blog/como-fazer-manutencao-impressora",
    "/blog/como-fazer-manutencao-nobreak",
    "/blog/como-fazer-overclock-cpu-com-seguranca",
    "/blog/como-fazer-pentest-basico-rede",
    "/blog/como-fazer-print-tela-celular",
    "/blog/como-fazer-teste-velocidade-internet",
    "/blog/como-fazer-upgrade-ssd-nvme",
    "/blog/como-formatar-pc-sem-perder-arquivos",
    "/blog/como-gerenciar-pacotes-apt-dnf-linux",
    "/blog/como-imprimir-pdf-windows",
    "/blog/como-instalar-aplicativos-celular-com-seguranca",
    "/blog/como-instalar-impressora-windows-passo-a-passo",
    "/blog/como-instalar-lamp-stack-ubuntu",
    "/blog/como-instalar-linux-dual-boot-windows",
    "/blog/como-instalar-postgresql-linux",
    "/blog/como-instalar-segundo-ssd-notebook",
    "/blog/como-instalar-ubuntu-do-zero",
    "/blog/como-instalar-windows-11-do-zero",
    "/blog/como-instalar-windows-11-do-zero-2026",
    "/blog/como-instalar-windows-11-pc-antigo",
    "/blog/como-limpar-notebook-por-dentro",
    "/blog/como-melhorar-sinal-wifi-em-casa",
    "/blog/como-monitorar-servidor-linux",
    "/blog/como-montar-pc-do-zero-guia-completo",
    "/blog/como-montar-pc-gamer-2026",
    "/blog/como-montar-rack-de-rede",
    "/blog/como-mudar-nome-rede-wifi",
    "/blog/como-organizar-arquivos-windows-iniciantes",
    "/blog/como-proteger-computador-golpes-internet",
    "/blog/como-proteger-rede-wifi-empresa",
    "/blog/como-recuperar-arquivos-apagados",
    "/blog/como-recuperar-arquivos-apagados-windows",
    "/blog/como-recuperar-conta-google-bloqueada",
    "/blog/como-recuperar-conta-hackeada",
    "/blog/como-recuperar-dados-hd-com-defeito",
    "/blog/como-recuperar-dados-hd-defeituoso",
    "/blog/como-remover-virus-sem-formatar",
    "/blog/como-remover-virus-windows-iniciantes",
    "/blog/como-resetar-senha-windows",
    "/blog/como-resolver-tela-azul-windows",
    "/blog/como-rodar-ia-localmente-no-pc",
    "/blog/como-saber-quem-esta-usando-meu-wifi",
    "/blog/como-saber-se-pc-tem-virus",
    "/blog/como-saber-se-pc-tem-virus-malware",
    "/blog/como-testar-fonte-de-alimentacao-pc",
    "/blog/como-transferir-dados-celular-novo",
    "/blog/como-treinar-ia-customizada-fine-tuning",
    "/blog/como-trocar-papel-de-parede-tela-bloqueio-windows",
    "/blog/como-trocar-pasta-termica",
    "/blog/como-trocar-pasta-termica-notebook",
    "/blog/como-trocar-senha-wifi",
    "/blog/como-trocar-tela-notebook-passo-a-passo",
    "/blog/como-usar-docker-linux-guia-completo",
    "/blog/como-usar-google-fotos-iniciantes",
    "/blog/como-usar-ia-no-dia-a-dia-dicas-praticas",
    "/blog/como-usar-rede-wifi-para-visitas",
    "/blog/como-usar-rsync-backup-linux",
    "/blog/como-usar-systemd-linux",
    "/blog/computador-lento-causas-solucoes",
    "/blog/configurar-email-outlook-office-365",
    "/blog/diagnostico-tecnico-por-que-e-pago",
    "/blog/dicas-manter-notebook-funcionando-bem",
    "/blog/diferenca-camera-wifi-dvr-qual-escolher",
    "/blog/diferenca-llm-machine-learning-deep-learning",
    "/blog/diferenca-windows-10-vs-11",
    "/blog/distribuicoes-linux-qual-melhor-para-voce",
    "/blog/equipe-especializada-cftv-litoral-parana",
    "/blog/erros-comuns-upgrade-computador",
    "/blog/ia-para-criacao-conteudo-profissional",
    "/blog/ia-para-pequenas-empresas-como-comecar",
    "/blog/ia-substituir-empregos-mitos-verdades",
    "/blog/impressora-nao-imprime-solucoes",
    "/blog/inteligencia-artificial-evolucao-historia",
    "/blog/linux-para-pc-antigo-leve-rapido",
    "/blog/linux-vs-windows-diferencas-qual-escolher",
    "/blog/manutencao-preventiva-computador-guia",
    "/blog/melhores-antivirus-2026-comparativo",
    "/blog/melhores-antivirus-gratuitos-2026",
    "/blog/melhores-ferramentas-ia-gratuitas-2026",
    "/blog/melhores-ias-para-programacao-2026",
    "/blog/monitoramento-24-horas-como-funciona",
    "/blog/notebook-nao-liga-o-que-fazer",
    "/blog/notebook-superaquecendo-o-que-fazer",
    "/blog/notebook-superaquecendo-solucoes",
    "/blog/office-365-guia-completo-empresas",
    "/blog/office-365-vs-office-tradicional",
    "/blog/pc-muito-lento-como-acelerar",
    "/blog/pc-nao-liga-o-que-fazer",
    "/blog/phishing-como-identificar-golpes",
    "/blog/por-que-todo-prestador-deve-estar-preciso-de-um",
    "/blog/preciso-de-um-para-eletricistas",
    "/blog/preciso-de-um-para-pintores-pedreiros",
    "/blog/preciso-de-um-para-tecnicos-informatica",
    "/blog/preciso-de-um-plataforma-prestadores",
    "/blog/preciso-de-um-todos-os-ramos",
    "/blog/preciso-de-um-vagas-oportunidades",
    "/blog/quando-trocar-computador-ou-reparar",
    "/blog/quando-trocar-hd-por-ssd",
    "/blog/ransomware-como-proteger-empresa",
    "/blog/seguranca-casas-praia-itapoa-guaratuba",
    "/blog/seguranca-digital-empresas-guia-2024",
    "/blog/sinais-computador-com-virus",
    "/blog/ssd-vs-hd-vale-a-pena-upgrade",
    "/blog/tela-azul-windows-como-resolver",
    "/blog/trocar-windows-por-linux-vale-a-pena",
    "/blog/wifi-caindo-toda-hora",
    "/blog/wifi-lento-como-melhorar",
    "/blog/windows-11-atualizacao-kb5074105-novidades",
    "/blog/windows-11-lento-como-resolver",
    "/blog/windows-11-vale-a-pena-atualizar",
    "/blog/windows-nao-atualiza-erros",
    "/cftv",
    "/cftv/araucaria",
    "/cftv/campo-largo",
    "/cftv/curitiba",
    "/cftv/guaratuba",
    "/cftv/litoral",
    "/cftv/pinhais",
    "/cftv/sao-jose-dos-pinhais",
    "/coleta-e-entrega",
    "/coleta-formulario",
    "/como-funciona",
    "/conserto-celular-curitiba",
    "/conserto-celular/agua-verde",
    "/conserto-celular/almirante-tamandare",
    "/conserto-celular/araucaria",
    "/conserto-celular/batel",
    "/conserto-celular/boqueirao",
    "/conserto-celular/cajuru",
    "/conserto-celular/campo-largo",
    "/conserto-celular/campo-magro",
    "/conserto-celular/centro",
    "/conserto-celular/cic",
    "/conserto-celular/colombo",
    "/conserto-celular/curitiba",
    "/conserto-celular/fazenda-rio-grande",
    "/conserto-celular/pinhais",
    "/conserto-celular/piraquara",
    "/conserto-celular/portao",
    "/conserto-celular/quatro-barras",
    "/conserto-celular/santa-felicidade",
    "/conserto-celular/sao-jose-dos-pinhais",
    "/conserto-impressora-curitiba",
    "/conserto-som-curitiba",
    "/conserto-som/agua-verde",
    "/conserto-som/almirante-tamandare",
    "/conserto-som/araucaria",
    "/conserto-som/batel",
    "/conserto-som/boqueirao",
    "/conserto-som/cajuru",
    "/conserto-som/campo-largo",
    "/conserto-som/campo-magro",
    "/conserto-som/centro",
    "/conserto-som/cic",
    "/conserto-som/colombo",
    "/conserto-som/curitiba",
    "/conserto-som/fazenda-rio-grande",
    "/conserto-som/pinhais",
    "/conserto-som/piraquara",
    "/conserto-som/portao",
    "/conserto-som/quatro-barras",
    "/conserto-som/santa-felicidade",
    "/conserto-som/sao-jose-dos-pinhais",
    "/conserto-tv-curitiba",
    "/conserto-tv/agua-verde",
    "/conserto-tv/almirante-tamandare",
    "/conserto-tv/araucaria",
    "/conserto-tv/batel",
    "/conserto-tv/boqueirao",
    "/conserto-tv/cajuru",
    "/conserto-tv/campo-largo",
    "/conserto-tv/campo-magro",
    "/conserto-tv/centro",
    "/conserto-tv/cic",
    "/conserto-tv/colombo",
    "/conserto-tv/curitiba",
    "/conserto-tv/fazenda-rio-grande",
    "/conserto-tv/pinhais",
    "/conserto-tv/piraquara",
    "/conserto-tv/portao",
    "/conserto-tv/quatro-barras",
    "/conserto-tv/santa-felicidade",
    "/conserto-tv/sao-jose-dos-pinhais",
    "/conserto-videogame-curitiba",
    "/conserto-videogame/agua-verde",
    "/conserto-videogame/almirante-tamandare",
    "/conserto-videogame/araucaria",
    "/conserto-videogame/batel",
    "/conserto-videogame/boqueirao",
    "/conserto-videogame/cajuru",
    "/conserto-videogame/campo-largo",
    "/conserto-videogame/campo-magro",
    "/conserto-videogame/centro",
    "/conserto-videogame/cic",
    "/conserto-videogame/colombo",
    "/conserto-videogame/curitiba",
    "/conserto-videogame/fazenda-rio-grande",
    "/conserto-videogame/pinhais",
    "/conserto-videogame/piraquara",
    "/conserto-videogame/portao",
    "/conserto-videogame/quatro-barras",
    "/conserto-videogame/santa-felicidade",
    "/conserto-videogame/sao-jose-dos-pinhais",
    "/contato",
    "/diagnostico-60s",
    "/diagnostico-tecnico",
    "/empresa-de-ti-curitiba",
    "/equipamentos-atendidos",
    "/faq",
    "/funil-indisponivel",
    "/gestor-responsavel",
    "/index",
    "/marcas",
    "/marcas/acer",
    "/marcas/amd",
    "/marcas/apple",
    "/marcas/asus",
    "/marcas/corsair",
    "/marcas/dell",
    "/marcas/gigabyte",
    "/marcas/hp",
    "/marcas/intel",
    "/marcas/intelbras",
    "/marcas/kingston",
    "/marcas/lenovo",
    "/marcas/lg",
    "/marcas/logitech",
    "/marcas/microsoft",
    "/marcas/motorola",
    "/marcas/msi",
    "/marcas/nvidia",
    "/marcas/positivo",
    "/marcas/razer",
    "/marcas/samsung",
    "/marcas/seagate",
    "/marcas/sony",
    "/marcas/tp-link",
    "/marcas/western-digital",
    "/marcas/xiaomi",
    "/obrigado",
    "/ordem-de-servico",
    "/politica-de-privacidade",
    "/precos-e-politicas",
    "/problemas-reais-e-casos",
    "/problemas/alto-falante-queimado-curitiba",
    "/problemas/amplificador-nao-liga-curitiba",
    "/problemas/assistencia-tecnica-urgente-curitiba",
    "/problemas/backup-perdido-curitiba",
    "/problemas/cabo-rede-nao-funciona-curitiba",
    "/problemas/caixa-som-nao-carrega-curitiba",
    "/problemas/caixa-som-sem-audio-curitiba",
    "/problemas/caixa-som-sem-bluetooth-curitiba",
    "/problemas/camera-seguranca-nao-funciona-curitiba",
    "/problemas/celular-bateria-inchada-curitiba",
    "/problemas/celular-camera-nao-funciona-curitiba",
    "/problemas/celular-com-virus-curitiba",
    "/problemas/celular-lento-curitiba",
    "/problemas/celular-listras-na-tela-curitiba",
    "/problemas/celular-molhou-curitiba",
    "/problemas/celular-nao-carrega-curitiba",
    "/problemas/celular-nao-liga-curitiba",
    "/problemas/celular-sem-sinal-curitiba",
    "/problemas/celular-tela-quebrada-curitiba",
    "/problemas/celular-touch-nao-funciona-curitiba",
    "/problemas/computador-com-cheiro-de-queimado-curitiba",
    "/problemas/computador-com-som-estranho-curitiba",
    "/problemas/computador-com-tela-preta-curitiba",
    "/problemas/computador-com-virus-curitiba",
    "/problemas/computador-desligando-apos-segundos-curitiba",
    "/problemas/computador-lento-curitiba",
    "/problemas/computador-liga-e-desliga-curitiba",
    "/problemas/computador-muito-barulhento-curitiba",
    "/problemas/computador-nao-conecta-bluetooth-curitiba",
    "/problemas/computador-nao-desliga-curitiba",
    "/problemas/computador-nao-liga-curitiba",
    "/problemas/computador-nao-reconhece-usb-curitiba",
    "/problemas/computador-reiniciando-sozinho-curitiba",
    "/problemas/computador-sem-video-curitiba",
    "/problemas/computador-sem-wifi-curitiba",
    "/problemas/computador-travando-curitiba",
    "/problemas/conserto-computador-domicilio-curitiba",
    "/problemas/curto-em-placa-eletronica",
    "/problemas/custo-reparo-vs-novo",
    "/problemas/erro-0x0000007b-curitiba",
    "/problemas/erro-0x80004005-curitiba",
    "/problemas/erro-0x80070005-curitiba",
    "/problemas/erro-0x80070057-curitiba",
    "/problemas/erro-0x800f081f-curitiba",
    "/problemas/erro-0x80240034-curitiba",
    "/problemas/erro-0xc00000e-curitiba",
    "/problemas/erro-0xc000021a-curitiba",
    "/problemas/erro-ao-instalar-memoria-ram",
    "/problemas/erro-ao-instalar-windows-curitiba",
    "/problemas/erro-apos-formatacao",
    "/problemas/erro-atualizacao-windows-11-curitiba",
    "/problemas/erro-bios-curitiba",
    "/problemas/erro-disco-100-porcento-curitiba",
    "/problemas/erro-disco-cheio-curitiba",
    "/problemas/erro-driver-windows-curitiba",
    "/problemas/erro-particao-windows-curitiba",
    "/problemas/erro-registro-windows-curitiba",
    "/problemas/erro-windows-update-curitiba",
    "/problemas/erros-comuns-em-upgrade",
    "/problemas/fonte-queimada-curitiba",
    "/problemas/formatacao-resolve-curitiba",
    "/problemas/gpu-desgastada",
    "/problemas/hd-externo-nao-reconhece-curitiba",
    "/problemas/hd-fazendo-barulho-curitiba",
    "/problemas/impressora-cartucho-nao-reconhece-curitiba",
    "/problemas/impressora-erro-conexao-usb-wifi-curitiba",
    "/problemas/impressora-nao-imprime-curitiba",
    "/problemas/impressora-papel-preso-curitiba",
    "/problemas/impressora-tinta-nao-sai-curitiba",
    "/problemas/internet-lenta-curitiba",
    "/problemas/listras-tela-celular-apos-atualizacao-curitiba",
    "/problemas/manutencao-notebook-curitiba-rapido",
    "/problemas/memoria-ram-com-defeito-curitiba",
    "/problemas/microsoldagem-celular-curitiba",
    "/problemas/monitor-piscando-curitiba",
    "/problemas/monitor-sem-sinal-curitiba",
    "/problemas/mouse-nao-funciona-curitiba",
    "/problemas/notebook-apos-upgrade-nao-liga-curitiba",
    "/problemas/notebook-bateria-nao-carrega-curitiba",
    "/problemas/notebook-com-agua-ou-liquido-curitiba",
    "/problemas/notebook-com-tela-piscando-curitiba",
    "/problemas/notebook-com-tela-quebrada-curitiba",
    "/problemas/notebook-desliga-sozinho-curitiba",
    "/problemas/notebook-desligando-sozinho-curitiba",
    "/problemas/notebook-esquentando-curitiba",
    "/problemas/notebook-esquentando-desligando-curitiba",
    "/problemas/notebook-esquentando-muito-curitiba",
    "/problemas/notebook-lento-curitiba",
    "/problemas/notebook-nao-carrega-bateria-curitiba",
    "/problemas/notebook-nao-carrega-curitiba",
    "/problemas/notebook-nao-conecta-bluetooth-curitiba",
    "/problemas/notebook-nao-liga-curitiba",
    "/problemas/notebook-sem-audio-curitiba",
    "/problemas/notebook-sem-imagem-curitiba",
    "/problemas/notebook-sem-som-curitiba",
    "/problemas/notebook-sem-webcam-curitiba",
    "/problemas/notebook-sem-wifi-curitiba",
    "/problemas/notebook-superaquecendo-curitiba",
    "/problemas/notebook-teclado-nao-funciona-curitiba",
    "/problemas/notebook-tela-amarelada-curitiba",
    "/problemas/notebook-tela-escura-curitiba",
    "/problemas/notebook-tela-preta-curitiba",
    "/problemas/notebook-touchpad-nao-funciona-curitiba",
    "/problemas/o-que-causa-curto-em-placa",
    "/problemas/o-que-fazer-computador-nao-liga",
    "/problemas/o-que-fazer-notebook-lento",
    "/problemas/pc-com-barulho-estranho-curitiba",
    "/problemas/pc-com-pop-ups-e-propagandas-curitiba",
    "/problemas/pc-com-programas-pesados",
    "/problemas/pc-com-tela-congelada-curitiba",
    "/problemas/pc-com-tela-preta-curitiba",
    "/problemas/pc-com-virus-ransomware-curitiba",
    "/problemas/pc-desligando-sozinho-curitiba",
    "/problemas/pc-fazendo-barulho-estranho-curitiba",
    "/problemas/pc-nao-conecta-bluetooth-curitiba",
    "/problemas/pc-nao-conecta-internet-curitiba",
    "/problemas/pc-nao-conecta-wifi-curitiba",
    "/problemas/pc-nao-entra-modo-seguro-curitiba",
    "/problemas/pc-nao-reconhece-hd-curitiba",
    "/problemas/pc-nao-reconhece-segundo-monitor-curitiba",
    "/problemas/pc-nao-reconhece-usb-curitiba",
    "/problemas/pc-reiniciando-sozinho-curitiba",
    "/problemas/pc-sem-audio-curitiba",
    "/problemas/pc-sem-imagem-curitiba",
    "/problemas/pc-sem-som-hdmi-curitiba",
    "/problemas/pc-superaquecendo-curitiba",
    "/problemas/pc-trava-ao-jogar-curitiba",
    "/problemas/pc-travando-em-jogos-curitiba",
    "/problemas/pc-travando-jogos-curitiba",
    "/problemas/pen-drive-nao-reconhece-curitiba",
    "/problemas/placa-de-video-nao-funciona-curitiba",
    "/problemas/placa-mae-com-defeito-curitiba",
    "/problemas/placa-mae-queimada",
    "/problemas/por-que-conserto-placa-mae-custa-caro-curitiba",
    "/problemas/por-que-display-e-caro-curitiba",
    "/problemas/quando-nao-compensa-reparo",
    "/problemas/quando-trocar-computador",
    "/problemas/quanto-custa-trocar-tela-celular-curitiba",
    "/problemas/quanto-custa-trocar-tela-tv-curitiba",
    "/problemas/radio-nao-liga-curitiba",
    "/problemas/reballing-bga-curitiba",
    "/problemas/recapacitacao-placa-eletronica-curitiba",
    "/problemas/receiver-sem-som-curitiba",
    "/problemas/reflow-bga-curitiba",
    "/problemas/reparo-placa-mae-celular-curitiba",
    "/problemas/reparo-placa-mae-notebook-curitiba",
    "/problemas/reparo-placa-principal-tv-curitiba",
    "/problemas/reparo-placa-som-amplificador-curitiba",
    "/problemas/riscos-de-tentar-consertar",
    "/problemas/smart-tv-lenta-curitiba",
    "/problemas/som-automotivo-nao-funciona-curitiba",
    "/problemas/som-chiando-curitiba",
    "/problemas/som-nao-funciona-curitiba",
    "/problemas/ssd-nao-reconhece-curitiba",
    "/problemas/teclado-mouse-nao-funciona-curitiba",
    "/problemas/teclado-nao-funciona-curitiba",
    "/problemas/tecnico-computador-perto-de-mim",
    "/problemas/tecnico-informatica-emergencia-curitiba",
    "/problemas/tela-azul-windows-curitiba",
    "/problemas/troca-chip-bga-curitiba",
    "/problemas/tv-cheiro-queimado-curitiba",
    "/problemas/tv-com-linhas-na-tela-curitiba",
    "/problemas/tv-com-som-sem-imagem-curitiba",
    "/problemas/tv-com-tela-escura-curitiba",
    "/problemas/tv-controle-nao-funciona-curitiba",
    "/problemas/tv-demora-ligar-curitiba",
    "/problemas/tv-desliga-sozinha-curitiba",
    "/problemas/tv-desligando-sozinha-curitiba",
    "/problemas/tv-imagem-fantasma-curitiba",
    "/problemas/tv-listras-horizontais-verticais-conserto-curitiba",
    "/problemas/tv-listras-na-tela-curitiba",
    "/problemas/tv-manchas-na-tela-curitiba",
    "/problemas/tv-nao-conecta-wifi-bluetooth-curitiba",
    "/problemas/tv-nao-liga-curitiba",
    "/problemas/tv-pixel-morto-curitiba",
    "/problemas/tv-sem-cores-curitiba",
    "/problemas/tv-sem-hdmi-curitiba",
    "/problemas/tv-sem-imagem-curitiba",
    "/problemas/tv-sem-som-curitiba",
    "/problemas/tv-sem-wifi-curitiba",
    "/problemas/tv-som-sem-video-curitiba",
    "/problemas/tv-tela-quebrada-curitiba",
    "/problemas/tv-travando-lenta-curitiba",
    "/problemas/upgrade-deu-problema",
    "/problemas/vale-a-pena-consertar-computador",
    "/problemas/vale-a-pena-consertar-notebook",
    "/problemas/wifi-caindo-curitiba",
    "/problemas/windows-lento-curitiba",
    "/problemas/windows-travando-na-atualizacao-curitiba",
    "/procedimentos-placa",
    "/procedimentos/alto-falante-queimado-curitiba",
    "/procedimentos/amplificador-nao-liga-curitiba",
    "/procedimentos/assistencia-tecnica-urgente-curitiba",
    "/procedimentos/backup-perdido-curitiba",
    "/procedimentos/cabo-rede-nao-funciona-curitiba",
    "/procedimentos/caixa-som-nao-carrega-curitiba",
    "/procedimentos/caixa-som-sem-audio-curitiba",
    "/procedimentos/caixa-som-sem-bluetooth-curitiba",
    "/procedimentos/camera-seguranca-nao-funciona-curitiba",
    "/procedimentos/celular-bateria-inchada-curitiba",
    "/procedimentos/celular-camera-nao-funciona-curitiba",
    "/procedimentos/celular-com-virus-curitiba",
    "/procedimentos/celular-lento-curitiba",
    "/procedimentos/celular-listras-na-tela-curitiba",
    "/procedimentos/celular-molhou-curitiba",
    "/procedimentos/celular-nao-carrega-curitiba",
    "/procedimentos/celular-nao-liga-curitiba",
    "/procedimentos/celular-sem-sinal-curitiba",
    "/procedimentos/celular-tela-quebrada-curitiba",
    "/procedimentos/celular-touch-nao-funciona-curitiba",
    "/procedimentos/computador-com-cheiro-de-queimado-curitiba",
    "/procedimentos/computador-com-som-estranho-curitiba",
    "/procedimentos/computador-com-tela-preta-curitiba",
    "/procedimentos/computador-com-virus-curitiba",
    "/procedimentos/computador-desligando-apos-segundos-curitiba",
    "/procedimentos/computador-lento-curitiba",
    "/procedimentos/computador-liga-e-desliga-curitiba",
    "/procedimentos/computador-muito-barulhento-curitiba",
    "/procedimentos/computador-nao-conecta-bluetooth-curitiba",
    "/procedimentos/computador-nao-desliga-curitiba",
    "/procedimentos/computador-nao-liga-curitiba",
    "/procedimentos/computador-nao-reconhece-usb-curitiba",
    "/procedimentos/computador-reiniciando-sozinho-curitiba",
    "/procedimentos/computador-sem-video-curitiba",
    "/procedimentos/computador-sem-wifi-curitiba",
    "/procedimentos/computador-travando-curitiba",
    "/procedimentos/conserto-computador-domicilio-curitiba",
    "/procedimentos/curto-em-placa-eletronica",
    "/procedimentos/custo-reparo-vs-novo",
    "/procedimentos/erro-0x0000007b-curitiba",
    "/procedimentos/erro-0x80004005-curitiba",
    "/procedimentos/erro-0x80070005-curitiba",
    "/procedimentos/erro-0x80070057-curitiba",
    "/procedimentos/erro-0x800f081f-curitiba",
    "/procedimentos/erro-0x80240034-curitiba",
    "/procedimentos/erro-0xc00000e-curitiba",
    "/procedimentos/erro-0xc000021a-curitiba",
    "/procedimentos/erro-ao-instalar-memoria-ram",
    "/procedimentos/erro-ao-instalar-windows-curitiba",
    "/procedimentos/erro-apos-formatacao",
    "/procedimentos/erro-atualizacao-windows-11-curitiba",
    "/procedimentos/erro-bios-curitiba",
    "/procedimentos/erro-disco-100-porcento-curitiba",
    "/procedimentos/erro-disco-cheio-curitiba",
    "/procedimentos/erro-driver-windows-curitiba",
    "/procedimentos/erro-particao-windows-curitiba",
    "/procedimentos/erro-registro-windows-curitiba",
    "/procedimentos/erro-windows-update-curitiba",
    "/procedimentos/erros-comuns-em-upgrade",
    "/procedimentos/fonte-queimada-curitiba",
    "/procedimentos/formatacao-resolve-curitiba",
    "/procedimentos/gpu-desgastada",
    "/procedimentos/hd-externo-nao-reconhece-curitiba",
    "/procedimentos/hd-fazendo-barulho-curitiba",
    "/procedimentos/impressora-cartucho-nao-reconhece-curitiba",
    "/procedimentos/impressora-erro-conexao-usb-wifi-curitiba",
    "/procedimentos/impressora-nao-imprime-curitiba",
    "/procedimentos/impressora-papel-preso-curitiba",
    "/procedimentos/impressora-tinta-nao-sai-curitiba",
    "/procedimentos/internet-lenta-curitiba",
    "/procedimentos/listras-tela-celular-apos-atualizacao-curitiba",
    "/procedimentos/manutencao-notebook-curitiba-rapido",
    "/procedimentos/memoria-ram-com-defeito-curitiba",
    "/procedimentos/microsoldagem-celular-curitiba",
    "/procedimentos/monitor-piscando-curitiba",
    "/procedimentos/monitor-sem-sinal-curitiba",
    "/procedimentos/mouse-nao-funciona-curitiba",
    "/procedimentos/notebook-apos-upgrade-nao-liga-curitiba",
    "/procedimentos/notebook-bateria-nao-carrega-curitiba",
    "/procedimentos/notebook-com-agua-ou-liquido-curitiba",
    "/procedimentos/notebook-com-tela-piscando-curitiba",
    "/procedimentos/notebook-com-tela-quebrada-curitiba",
    "/procedimentos/notebook-desliga-sozinho-curitiba",
    "/procedimentos/notebook-desligando-sozinho-curitiba",
    "/procedimentos/notebook-esquentando-curitiba",
    "/procedimentos/notebook-esquentando-desligando-curitiba",
    "/procedimentos/notebook-esquentando-muito-curitiba",
    "/procedimentos/notebook-lento-curitiba",
    "/procedimentos/notebook-nao-carrega-bateria-curitiba",
    "/procedimentos/notebook-nao-carrega-curitiba",
    "/procedimentos/notebook-nao-conecta-bluetooth-curitiba",
    "/procedimentos/notebook-nao-liga-curitiba",
    "/procedimentos/notebook-sem-audio-curitiba",
    "/procedimentos/notebook-sem-imagem-curitiba",
    "/procedimentos/notebook-sem-som-curitiba",
    "/procedimentos/notebook-sem-webcam-curitiba",
    "/procedimentos/notebook-sem-wifi-curitiba",
    "/procedimentos/notebook-superaquecendo-curitiba",
    "/procedimentos/notebook-teclado-nao-funciona-curitiba",
    "/procedimentos/notebook-tela-amarelada-curitiba",
    "/procedimentos/notebook-tela-escura-curitiba",
    "/procedimentos/notebook-tela-preta-curitiba",
    "/procedimentos/notebook-touchpad-nao-funciona-curitiba",
    "/procedimentos/o-que-causa-curto-em-placa",
    "/procedimentos/o-que-fazer-computador-nao-liga",
    "/procedimentos/o-que-fazer-notebook-lento",
    "/procedimentos/pc-com-barulho-estranho-curitiba",
    "/procedimentos/pc-com-pop-ups-e-propagandas-curitiba",
    "/procedimentos/pc-com-programas-pesados",
    "/procedimentos/pc-com-tela-congelada-curitiba",
    "/procedimentos/pc-com-tela-preta-curitiba",
    "/procedimentos/pc-com-virus-ransomware-curitiba",
    "/procedimentos/pc-desligando-sozinho-curitiba",
    "/procedimentos/pc-fazendo-barulho-estranho-curitiba",
    "/procedimentos/pc-nao-conecta-bluetooth-curitiba",
    "/procedimentos/pc-nao-conecta-internet-curitiba",
    "/procedimentos/pc-nao-conecta-wifi-curitiba",
    "/procedimentos/pc-nao-entra-modo-seguro-curitiba",
    "/procedimentos/pc-nao-reconhece-hd-curitiba",
    "/procedimentos/pc-nao-reconhece-segundo-monitor-curitiba",
    "/procedimentos/pc-nao-reconhece-usb-curitiba",
    "/procedimentos/pc-reiniciando-sozinho-curitiba",
    "/procedimentos/pc-sem-audio-curitiba",
    "/procedimentos/pc-sem-imagem-curitiba",
    "/procedimentos/pc-sem-som-hdmi-curitiba",
    "/procedimentos/pc-superaquecendo-curitiba",
    "/procedimentos/pc-trava-ao-jogar-curitiba",
    "/procedimentos/pc-travando-em-jogos-curitiba",
    "/procedimentos/pc-travando-jogos-curitiba",
    "/procedimentos/pen-drive-nao-reconhece-curitiba",
    "/procedimentos/placa-de-video-nao-funciona-curitiba",
    "/procedimentos/placa-mae-com-defeito-curitiba",
    "/procedimentos/placa-mae-queimada",
    "/procedimentos/por-que-conserto-placa-mae-custa-caro-curitiba",
    "/procedimentos/por-que-display-e-caro-curitiba",
    "/procedimentos/quando-nao-compensa-reparo",
    "/procedimentos/quando-trocar-computador",
    "/procedimentos/quanto-custa-trocar-tela-celular-curitiba",
    "/procedimentos/quanto-custa-trocar-tela-tv-curitiba",
    "/procedimentos/radio-nao-liga-curitiba",
    "/procedimentos/reballing-bga-curitiba",
    "/procedimentos/recapacitacao-placa-eletronica-curitiba",
    "/procedimentos/receiver-sem-som-curitiba",
    "/procedimentos/reflow-bga-curitiba",
    "/procedimentos/reparo-placa-mae-celular-curitiba",
    "/procedimentos/reparo-placa-mae-notebook-curitiba",
    "/procedimentos/reparo-placa-principal-tv-curitiba",
    "/procedimentos/reparo-placa-som-amplificador-curitiba",
    "/procedimentos/riscos-de-tentar-consertar",
    "/procedimentos/smart-tv-lenta-curitiba",
    "/procedimentos/som-automotivo-nao-funciona-curitiba",
    "/procedimentos/som-chiando-curitiba",
    "/procedimentos/som-nao-funciona-curitiba",
    "/procedimentos/ssd-nao-reconhece-curitiba",
    "/procedimentos/teclado-mouse-nao-funciona-curitiba",
    "/procedimentos/teclado-nao-funciona-curitiba",
    "/procedimentos/tecnico-computador-perto-de-mim",
    "/procedimentos/tecnico-informatica-emergencia-curitiba",
    "/procedimentos/tela-azul-windows-curitiba",
    "/procedimentos/troca-chip-bga-curitiba",
    "/procedimentos/tv-cheiro-queimado-curitiba",
    "/procedimentos/tv-com-linhas-na-tela-curitiba",
    "/procedimentos/tv-com-som-sem-imagem-curitiba",
    "/procedimentos/tv-com-tela-escura-curitiba",
    "/procedimentos/tv-controle-nao-funciona-curitiba",
    "/procedimentos/tv-demora-ligar-curitiba",
    "/procedimentos/tv-desliga-sozinha-curitiba",
    "/procedimentos/tv-desligando-sozinha-curitiba",
    "/procedimentos/tv-imagem-fantasma-curitiba",
    "/procedimentos/tv-listras-horizontais-verticais-conserto-curitiba",
    "/procedimentos/tv-listras-na-tela-curitiba",
    "/procedimentos/tv-manchas-na-tela-curitiba",
    "/procedimentos/tv-nao-conecta-wifi-bluetooth-curitiba",
    "/procedimentos/tv-nao-liga-curitiba",
    "/procedimentos/tv-pixel-morto-curitiba",
    "/procedimentos/tv-sem-cores-curitiba",
    "/procedimentos/tv-sem-hdmi-curitiba",
    "/procedimentos/tv-sem-imagem-curitiba",
    "/procedimentos/tv-sem-som-curitiba",
    "/procedimentos/tv-sem-wifi-curitiba",
    "/procedimentos/tv-som-sem-video-curitiba",
    "/procedimentos/tv-tela-quebrada-curitiba",
    "/procedimentos/tv-travando-lenta-curitiba",
    "/procedimentos/upgrade-deu-problema",
    "/procedimentos/vale-a-pena-consertar-computador",
    "/procedimentos/vale-a-pena-consertar-notebook",
    "/procedimentos/wifi-caindo-curitiba",
    "/procedimentos/windows-lento-curitiba",
    "/procedimentos/windows-travando-na-atualizacao-curitiba",
    "/quando-nao-compensa",
    "/seja-parceiro",
    "/servicos",
    "/servicos/backup-recuperacao/centro",
    "/servicos/computador-lento",
    "/servicos/computador-nao-liga",
    "/servicos/conserto-celular",
    "/servicos/conserto-pc-notebook/agua-verde",
    "/servicos/conserto-pc-notebook/araucaria",
    "/servicos/conserto-pc-notebook/batel",
    "/servicos/conserto-pc-notebook/campo-largo",
    "/servicos/conserto-pc-notebook/centro",
    "/servicos/conserto-pc-notebook/cic",
    "/servicos/conserto-pc-notebook/pinhais",
    "/servicos/conserto-pc-notebook/portao",
    "/servicos/conserto-pc-notebook/sao-jose-dos-pinhais",
    "/servicos/conserto-placa",
    "/servicos/conserto-tv",
    "/servicos/formatacao",
    "/servicos/formatacao-computador/agua-verde",
    "/servicos/formatacao-computador/araucaria",
    "/servicos/formatacao-computador/batel",
    "/servicos/formatacao-computador/campo-comprido",
    "/servicos/formatacao-computador/campo-largo",
    "/servicos/formatacao-computador/centro",
    "/servicos/formatacao-computador/cic",
    "/servicos/formatacao-computador/pinhais",
    "/servicos/formatacao-computador/portao",
    "/servicos/formatacao-computador/sao-jose-dos-pinhais",
    "/servicos/manutencao-de-computador",
    "/servicos/manutencao-de-notebook",
    "/servicos/manutencao-tv",
    "/servicos/manutencao-tv/agua-verde",
    "/servicos/manutencao-tv/alto-da-xv",
    "/servicos/manutencao-tv/batel",
    "/servicos/manutencao-tv/bigorrilho",
    "/servicos/manutencao-tv/boa-vista",
    "/servicos/manutencao-tv/boqueirao",
    "/servicos/manutencao-tv/cabral",
    "/servicos/manutencao-tv/cajuru",
    "/servicos/manutencao-tv/centro",
    "/servicos/manutencao-tv/cic",
    "/servicos/manutencao-tv/cristo-rei",
    "/servicos/manutencao-tv/ecoville",
    "/servicos/manutencao-tv/jardim-das-americas",
    "/servicos/manutencao-tv/portao",
    "/servicos/manutencao-tv/reboucas",
    "/servicos/manutencao-tv/santa-felicidade",
    "/servicos/montagem-pc",
    "/servicos/montagem-pc/cic",
    "/servicos/recuperacao-de-dados",
    "/servicos/redes-e-wifi",
    "/servicos/redes-wifi/agua-verde",
    "/servicos/redes-wifi/alto-da-xv",
    "/servicos/redes-wifi/araucaria",
    "/servicos/redes-wifi/batel",
    "/servicos/redes-wifi/bigorrilho",
    "/servicos/redes-wifi/boa-vista",
    "/servicos/redes-wifi/boqueirao",
    "/servicos/redes-wifi/cabral",
    "/servicos/redes-wifi/cajuru",
    "/servicos/redes-wifi/campo-largo",
    "/servicos/redes-wifi/centro",
    "/servicos/redes-wifi/cic",
    "/servicos/redes-wifi/cristo-rei",
    "/servicos/redes-wifi/ecoville",
    "/servicos/redes-wifi/jardim-das-americas",
    "/servicos/redes-wifi/pinhais",
    "/servicos/redes-wifi/portao",
    "/servicos/redes-wifi/reboucas",
    "/servicos/redes-wifi/santa-felicidade",
    "/servicos/redes-wifi/sao-jose-dos-pinhais",
    "/servicos/remocao-de-virus",
    "/servicos/remocao-virus/agua-verde",
    "/servicos/remocao-virus/araucaria",
    "/servicos/remocao-virus/batel",
    "/servicos/remocao-virus/campo-largo",
    "/servicos/remocao-virus/centro",
    "/servicos/remocao-virus/cic",
    "/servicos/remocao-virus/pinhais",
    "/servicos/remocao-virus/portao",
    "/servicos/remocao-virus/sao-jose-dos-pinhais",
    "/servicos/suporte-tecnico-empresarial",
    "/servicos/upgrade-ssd-memoria/agua-verde",
    "/servicos/upgrade-ssd-memoria/araucaria",
    "/servicos/upgrade-ssd-memoria/batel",
    "/servicos/upgrade-ssd-memoria/centro",
    "/servicos/upgrade-ssd-memoria/cic",
    "/servicos/upgrade-ssd-memoria/pinhais",
    "/servicos/upgrade-ssd-memoria/portao",
    "/servicos/upgrade-ssd-memoria/santa-felicidade",
    "/servicos/upgrade-ssd-memoria/sao-jose-dos-pinhais",
    "/servicos/upgrade-ssd-ram",
    "/sobre",
    "/status",
    "/tecnico-informatica-almirante-tamandare",
    "/tecnico-informatica-araucaria",
    "/tecnico-informatica-campo-largo",
    "/tecnico-informatica-campo-magro",
    "/tecnico-informatica-colombo",
    "/tecnico-informatica-curitiba",
    "/tecnico-informatica-fazenda-rio-grande",
    "/tecnico-informatica-pinhais",
    "/tecnico-informatica-piraquara",
    "/tecnico-informatica-quatro-barras",
    "/tecnico-informatica-sao-jose-pinhais",
    "/termos-e-condicoes"
  ],
  validPatterns: [
    "/arrumar-pc/:cidade",
    "/arrumar-pc/servico/:servico/:cidade",
    "/blog/:slug",
    "/conserto-celular/:local",
    "/conserto-som/:local",
    "/conserto-tv/:local",
    "/conserto-videogame/:local",
    "/marcas/:slug",
    "/problemas/:slug",
    "/procedimentos/:slug",
    "/servicos/:servico/:cidade"
  ],
  patternInfo: [
    {
      pattern: "/arrumar-pc/:cidade",
      closed: true,
      knownCount: 21
    },
    {
      pattern: "/arrumar-pc/servico/:servico/:cidade",
      closed: false,
      knownCount: 0
    },
    {
      pattern: "/blog/:slug",
      closed: true,
      knownCount: 157
    },
    {
      pattern: "/conserto-celular/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/conserto-som/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/conserto-tv/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/conserto-videogame/:local",
      closed: true,
      knownCount: 19
    },
    {
      pattern: "/marcas/:slug",
      closed: true,
      knownCount: 26
    },
    {
      pattern: "/problemas/:slug",
      closed: true,
      knownCount: 189
    },
    {
      pattern: "/procedimentos/:slug",
      closed: true,
      knownCount: 189
    },
    {
      pattern: "/servicos/:servico/:cidade",
      closed: true,
      knownCount: 75
    }
  ],
  redirects: [
    {
      from: "/servicos/formatacao-computador",
      to: "/servicos/formatacao",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/remocao-virus",
      to: "/servicos/remocao-de-virus",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/upgrade-ssd-memoria",
      to: "/servicos/upgrade-ssd-ram",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/conserto-pc-notebook",
      to: "/servicos/manutencao-de-computador",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/conserto-notebook-curitiba",
      to: "/servicos/manutencao-de-notebook",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/redes-wifi",
      to: "/servicos/redes-e-wifi",
      motivo: "variacao-slug"
    },
    {
      from: "/tecnico-informatica-sao-jose-dos-pinhais",
      to: "/tecnico-informatica-sao-jose-pinhais",
      motivo: "variacao-slug"
    },
    {
      from: "/servicos/backup-recuperacao",
      to: "/servicos/recuperacao-de-dados",
      motivo: "variacao-slug"
    },
    {
      from: "/formatacao-de-computador-curitiba",
      to: "/servicos/formatacao",
      motivo: "url-antiga"
    },
    {
      from: "/remocao-de-virus-curitiba",
      to: "/servicos/remocao-de-virus",
      motivo: "url-antiga"
    },
    {
      from: "/upgrade-ssd-curitiba",
      to: "/servicos/upgrade-ssd-ram",
      motivo: "url-antiga"
    },
    {
      from: "/upgrade-memoria-ram-curitiba",
      to: "/servicos/upgrade-ssd-ram",
      motivo: "url-antiga"
    },
    {
      from: "/conserto-de-notebook-curitiba",
      to: "/servicos/manutencao-de-notebook",
      motivo: "url-antiga"
    },
    {
      from: "/suporte-tecnico-remoto",
      to: "/atendimento-remoto",
      motivo: "url-antiga"
    },
    {
      from: "/assistencia-tecnica-empresas-curitiba",
      to: "/servicos/suporte-tecnico-empresarial",
      motivo: "url-antiga"
    },
    {
      from: "/suporte-empresas",
      to: "/servicos/suporte-tecnico-empresarial",
      motivo: "url-antiga"
    },
    {
      from: "/reflow-bga-curitiba",
      to: "/procedimentos/reflow-bga-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/reballing-bga-curitiba",
      to: "/procedimentos/reballing-bga-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/troca-chip-bga-curitiba",
      to: "/procedimentos/troca-chip-bga-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/microsoldagem-celular-curitiba",
      to: "/procedimentos/microsoldagem-celular-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/recapacitacao-placa-eletronica-curitiba",
      to: "/procedimentos/recapacitacao-placa-eletronica-curitiba",
      motivo: "url-antiga"
    },
    {
      from: "/privacidade",
      to: "/politica-de-privacidade",
      motivo: "alias-institucional"
    },
    {
      from: "/termos",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/valores",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/precos",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/termos-condicoes-valores",
      to: "/precos-e-politicas",
      motivo: "alias-institucional"
    },
    {
      from: "/pessoa-fisica",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/para-voce",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/residencial",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/tecnico-a-domicilio",
      to: "/atendimento-domicilio",
      motivo: "alias-pf"
    },
    {
      from: "/pessoa-juridica",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/para-empresas",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/empresas",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/ti-para-empresas",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    },
    {
      from: "/suporte-corporativo",
      to: "/empresa-de-ti-curitiba",
      motivo: "alias-pj"
    }
  ],
  privatePrefixes: [
    "/admin",
    "/ads"
  ],
  assetPrefixes: [
    "/assets/",
    "/lovable-uploads/",
    "/images/",
    "/fonts/",
    "/css/",
    "/blog/"
  ],
  assetFiles: [
    "/_headers",
    "/_redirects",
    "/apple-touch-icon-20260624.png",
    "/apple-touch-icon.png",
    "/assets/AcademiaSJP-CUy8k3Ql.js",
    "/assets/AdminDashboard-DIx_M88u.js",
    "/assets/AdminFunnel-rixVzlRO.js",
    "/assets/AdminLogin-mLw1ZOqE.js",
    "/assets/AdminReviews-xlVBOafB.js",
    "/assets/AdminVitals-DgiW8nA5.js",
    "/assets/AfonsoPena-CSwmp1sx.js",
    "/assets/AgricolareSJP-BYAgmj48.js",
    "/assets/AguaVerde-vCdwrVIC.js",
    "/assets/AguaVerdeBairro-DHw9c7GV.js",
    "/assets/AltoBoqueiraoCtba-CT3ywNcY.js",
    "/assets/AltoGloria-DDjNjog4.js",
    "/assets/AltoMaracanaColombo-Cvu0Hibz.js",
    "/assets/AltoTaruma-BIAw8uSX.js",
    "/assets/AnimatedSection-DOx-4k8S.js",
    "/assets/AntonioOliveraCM-C7UK3teK.js",
    "/assets/AraucariaCentro-Cn1zhcGx.js",
    "/assets/Aristocrata-Dx36Ja5B.js",
    "/assets/ArrumarPC-3Bxu8BUv.js",
    "/assets/ArrumarPCCity-BPLDp6Nt.js",
    "/assets/ArrumarPCServicoCidade-CUxglVmM.js",
    "/assets/AssistenciaEletrodomesticosInteligentesCuritiba-DSemeJYU.js",
    "/assets/AssistenciaTecnicaCuritiba-BKpQYWLF.js",
    "/assets/AtendimentoDomicilio-CKYgKeaH.js",
    "/assets/AtendimentoRemoto-CBJZSEMH.js",
    "/assets/AtubaColombo-DFpBGURJ.js",
    "/assets/AtubaPinhais-BsWfiz7J.js",
    "/assets/Aviacao-ovnVAsOk.js",
    "/assets/Bacacheri-CulFtpQz.js",
    "/assets/BackupCentro-CrwEkhY8.js",
    "/assets/BairroLocalLayout-CAb9Yd-L.js",
    "/assets/BairroTemplate-DwUwsBsS.js",
    "/assets/BariguiAraucaria-CX8_MXyl.js",
    "/assets/BarroPreto-wg9kLWEc.js",
    "/assets/BateiasCL-D9ATvNE5.js",
    "/assets/Batel-DKlySckT.js",
    "/assets/BenefitsGrid-PRCXpAof.js",
    "/assets/Bigorrilho-3tLw2J2n.js",
    "/assets/BlocoInteligencia-1b_YYbWE.js",
    "/assets/Blog-CbFMM_0m.js",
    "/assets/BlogPost-tf-4bltN.js",
    "/assets/BlogPostFAQ-DRbNHlCs.js",
    "/assets/BoaVista-DzHBcbt6.js",
    "/assets/BoaVistaTamandare-bjDohOgN.js",
    "/assets/BonecaSJP-B5KQuli2.js",
    "/assets/Boqueirao-BHoWNXrV.js",
    "/assets/BoqueiraoAraucaria-C8oxKVSR.js",
    "/assets/BordaDoCampoQB-fpkpDczO.js",
    "/assets/BordaDoCampoSJP-HktJhaBd.js",
    "/assets/BordoDoCampoSJP2-B6ZALc1B.js",
    "/assets/BotiatuvaCL-BsJ4oPSx.js",
    "/assets/BotiatuvaCM-ZZVnRMi5.js",
    "/assets/Braga-CoUnZOtb.js",
    "/assets/Breadcrumbs-bjZL0yTi.js",
    "/assets/CFTV-CZUUD-fY.js",
    "/assets/CFTVAraucaria-D-abEA3B.js",
    "/assets/CFTVCampoLargo-BDOSegAw.js",
    "/assets/CFTVCityTemplate-Bwfc2dT_.js",
    "/assets/CFTVCuritiba-CpNakwAt.js",
    "/assets/CFTVGuaratuba-1-2Gv_6d.js",
    "/assets/CFTVLitoral-D0jEIUQ-.js",
    "/assets/CFTVPinhais-HBAJXPWR.js",
    "/assets/CFTVSaoJosePinhais-NVTiWZN5.js",
    "/assets/CIC-BBi7oD63.js",
    "/assets/CTASection-5q34bJ07.js",
    "/assets/Cabral-D3JBDJai.js",
    "/assets/CacheiraAraucaria-Ddtj9wDV.js",
    "/assets/CachoeiraAT-BQ2qETS6.js",
    "/assets/CaiuaPiraquara-I-VuQex1.js",
    "/assets/Cajuru-Bh9Hh2j7.js",
    "/assets/CaliforniaAraucaria-CximRiOg.js",
    "/assets/CampinaDaBarra-vxF69dSE.js",
    "/assets/CampinaGrandeColombo-CmtIjdGb.js",
    "/assets/CampoComprido-DNVMQG_4.js",
    "/assets/CampoDoTenenteTamandare-BUgxWWuq.js",
    "/assets/CampoLargoCentro-Dmxf4iNi.js",
    "/assets/CampoLargoSJP-CNk8cJo1.js",
    "/assets/CampoPequenoColombo-DsbtC_hT.js",
    "/assets/CapaoImbuia-DzX3D9t2.js",
    "/assets/CapelaVelhaAraucaria-DTqBf5LL.js",
    "/assets/CategoryLocalTemplate-w3zCLYe2.js",
    "/assets/Centro-9dXsGRCF.js",
    "/assets/CentroAlmiranteTamandare-D4Kn8a5z.js",
    "/assets/CentroCampoMagro-NRPiTKwj.js",
    "/assets/CentroColombo-BnEP47li.js",
    "/assets/CentroFRG-Dxr0CzhF.js",
    "/assets/CentroPiraquara-ChtJzuhL.js",
    "/assets/CentroQuatroBarras-DQtjwQxq.js",
    "/assets/ChapadaAraucaria-H4bU10sb.js",
    "/assets/CidadeJardimSJP-DIrZLjt4.js",
    "/assets/CidadeLandingLayout-okMOGfL-.js",
    "/assets/CityServiceSchema-DzhtycmI.js",
    "/assets/ClusterLinks-SUlMMfal.js",
    "/assets/ColareColombo-B6yP65k6.js",
    "/assets/ColetaEntrega-Cx9LPDpL.js",
    "/assets/ColetaFormulario-aPe7MTUW.js",
    "/assets/ColoniaAntonioPradoAT-B_nJsNjO.js",
    "/assets/ColoniaMalhadaCL-2rzlE_Dd.js",
    "/assets/ColoniaMurcySJP-RD3Lk4QP.js",
    "/assets/ComoFunciona-Da0t_D_-.js",
    "/assets/ComputadorLento-DO9HQpYF.js",
    "/assets/ComputadorNaoLiga-DTTwVXLM.js",
    "/assets/ConsertoCelular-6vHykuls.js",
    "/assets/ConsertoImpressoraCuritiba-Br4_p4Ru.js",
    "/assets/ConsertoNotebookAraucaria-T26V9bC3.js",
    "/assets/ConsertoNotebookBatel-BYkpo9pa.js",
    "/assets/ConsertoNotebookCIC-B9XS1kPg.js",
    "/assets/ConsertoNotebookCampoLargo-0W2twAnp.js",
    "/assets/ConsertoNotebookPinhais-BwCgLnpN.js",
    "/assets/ConsertoNotebookPortao-C4I7oEIs.js",
    "/assets/ConsertoNotebookSaoJosePinhais-DaOlczGR.js",
    "/assets/ConsertoPlaca-CIPqPE9b.js",
    "/assets/ConsertoTV-uzFfVI6E.js",
    "/assets/Contato-CzYIUxWg.js",
    "/assets/CorreiaDeFreitasCL-cG9C4JRj.js",
    "/assets/Costeira-Di823x92.js",
    "/assets/CosteiraAraucaria-H6mH1PQ-.js",
    "/assets/CristoRei-BiROIHmJ.js",
    "/assets/Cruzeiro-uOhiJIJj.js",
    "/assets/DelRey-3pIe_zq1.js",
    "/assets/Diagnostico60s-BTgkMmlw.js",
    "/assets/DiagnosticoTecnico-CRqPkkIY.js",
    "/assets/EeatProofsSection-DRpO0hug.js",
    "/assets/EmbuColombo-DvuhjsGm.js",
    "/assets/EmilianoPerneta-XidagsmR.js",
    "/assets/EmpresaDeTiCuritiba-2cIEapnk.js",
    "/assets/EquipamentosAtendidos-Csj1V-hx.js",
    "/assets/EspigoAlegreCM-Bgsmlekd.js",
    "/assets/EstacaoAraucaria-DOL5o2sI.js",
    "/assets/EstanciaPinhais-D_DXYVvd.js",
    "/assets/EucaliptosFRG-Cq0kGhc-.js",
    "/assets/EucaliptosFRG2-CLrkIURz.js",
    "/assets/FAQ-DsQgmx6U.js",
    "/assets/FatimaColombo-D1O892Ee.js",
    "/assets/FazendaVelhaAraucaria-CoRGMC9p.js",
    "/assets/Fazendinha-DhdetQxu.js",
    "/assets/FerrariaCampoLargo-CjcVr4xZ.js",
    "/assets/FloatingParticles-BKLQ5V8q.js",
    "/assets/Footer-CXuDl26i.js",
    "/assets/FormatacaoAraucaria-CcM1K_ax.js",
    "/assets/FormatacaoCampoComprido-CVgpw-hi.js",
    "/assets/FormatacaoCampoLargo-Dsmde-gR.js",
    "/assets/FormatacaoCentro-ZKByKuKS.js",
    "/assets/FormatacaoPinhais-DysVO_N5.js",
    "/assets/FormatacaoPortao-MgKFUiGN.js",
    "/assets/FormatacaoSaoJosePinhais-CJA8GVn_.js",
    "/assets/FunilIndisponivel-DvS2Sygc.js",
    "/assets/GA4ChecklistPanel-B9N7wrbI.js",
    "/assets/GabirobalColombo-BhLBc1Gd.js",
    "/assets/GestorResponsavel-CuDAKhCQ.js",
    "/assets/GraciosaMirQB-DcnvLJv5.js",
    "/assets/GraciosaPinhais-BkO2Ut76.js",
    "/assets/GralhaAzulFRG-BZCV72FY.js",
    "/assets/GuajuviraAraucaria-BSiLiL-K.js",
    "/assets/GuaraitubaColombo-B6Ue6nIA.js",
    "/assets/GuaritubaPiraquara-C4flFfGG.js",
    "/assets/Guatupe-CEYsOY-l.js",
    "/assets/Hauer-CLLNXa8y.js",
    "/assets/Header-B7qmmyxJ.js",
    "/assets/HomeSections-BOIs0roW.js",
    "/assets/HortenciaFRG-DLe5Llbr.js",
    "/assets/HugoLange-BL4RneiK.js",
    "/assets/IguacuAraucaria-CnixSgcL.js",
    "/assets/IguacuFRG-BZ--NgMQ.js",
    "/assets/IndependenciaSJP-DCttilrj.js",
    "/assets/IndustrialAraucaria-mQS1FORI.js",
    "/assets/InterlinkingBlock-Cll-_JGn.js",
    "/assets/IpeSJP-BrQuDhDh.js",
    "/assets/IraiPiraquara-D8S10JNt.js",
    "/assets/ItaliaSJP-ajWb0iIK.js",
    "/assets/ItaquiCL-CBAoZF8_.js",
    "/assets/JardimAmelia-CrNYYqsP.js",
    "/assets/JardimAmericaCL-BbjBh9D8.js",
    "/assets/JardimAmericas-DXQ1L6zS.js",
    "/assets/JardimBelaVistaPiraquara-Dvp8Tz9y.js",
    "/assets/JardimBoaVistaAraucaria-BEo2nv0z.js",
    "/assets/JardimBoaVistaCM-BqfbQsfk.js",
    "/assets/JardimClaudia-Ct0ruVqx.js",
    "/assets/JardimClaudiaIIPinhais-DNFukhn1.js",
    "/assets/JardimCondorFRG-B-pvHcAj.js",
    "/assets/JardimDasPedrasFRG-DdzmgDaB.js",
    "/assets/JardimDonaRosaPinhais-Cs_vbRKo.js",
    "/assets/JardimEsperancaCL-D1Lxa5YT.js",
    "/assets/JardimEsplanadaPinhais-WfykZMDQ.js",
    "/assets/JardimEstadosFRG-Cyw4z7jR.js",
    "/assets/JardimFlorestalQB-BDsJgQG2.js",
    "/assets/JardimGrazielaAT-BtftwmDQ.js",
    "/assets/JardimGuilherminaCampoLargo-DO39QTp7.js",
    "/assets/JardimIguacuAraucaria-5gN6lwYI.js",
    "/assets/JardimIperigoFRG-D3PYnzXZ.js",
    "/assets/JardimJaponeQB-BhvDWmXf.js",
    "/assets/JardimKarlaPinhais-D_iuV4jp.js",
    "/assets/JardimLaranjeirasCL-C5meBOUD.js",
    "/assets/JardimMeninoDeusQB-CM1-w1-3.js",
    "/assets/JardimMontoSantoAT-DyTFhVpT.js",
    "/assets/JardimNovoHorizonteCL-CM0dfxa7.js",
    "/assets/JardimOsascoColombo-DGS9CTOx.js",
    "/assets/JardimParaisoAT-2phjRDrI.js",
    "/assets/JardimParanaguaTamandare-DbYyQm06.js",
    "/assets/JardimPedroDemeterco-pyCI6MxL.js",
    "/assets/JardimPlanaltoCL-R1v8c16T.js",
    "/assets/JardimPlanaltoIICL-7RagInwW.js",
    "/assets/JardimPrimaveraPiraquara-CZgnKiav.js",
    "/assets/JardimRomaAT-BwA6A2gh.js",
    "/assets/JardimSantoAntonioPiraquara-DLyHVBCh.js",
    "/assets/JardimSaoJorgeTamandare-D5x54SGW.js",
    "/assets/JardimSaoPauloPiraquara-DlX9fjtM.js",
    "/assets/JardimShangrilaAraucaria-PvGWB5l5.js",
    "/assets/JardimSocial-DS-tm1MC.js",
    "/assets/JardimTropicalPinhais-B4XVHWl8.js",
    "/assets/JardimUniaoPiraquara-DfWjaMVL.js",
    "/assets/JardimWissingerPinhais-FjIEOESJ.js",
    "/assets/JoqueiFRCM-Fe3sM-D4.js",
    "/assets/Juveve-CeOcFyNJ.js",
    "/assets/LamenhaGrandeCL-DmxNYHtz.js",
    "/assets/LegacyApp-C47F0xlZ.js",
    "/assets/LocalBusinessJsonLd-DtR3hPN7.js",
    "/assets/ManutencaoTV-BL3IhS-b.js",
    "/assets/ManutencaoTvAguaVerde-w8vvfJbw.js",
    "/assets/ManutencaoTvAltoXV-B3kZW8wk.js",
    "/assets/ManutencaoTvBatel-B9ihn7zN.js",
    "/assets/ManutencaoTvBigorrilho-BdGXvpbT.js",
    "/assets/ManutencaoTvBoaVista-NCxa6UYk.js",
    "/assets/ManutencaoTvBoqueirao-qjvpA8Vm.js",
    "/assets/ManutencaoTvCabral-BG9141Ry.js",
    "/assets/ManutencaoTvCajuru-BrY4VJUe.js",
    "/assets/ManutencaoTvCentro-BiUgp4rf.js",
    "/assets/ManutencaoTvCic-Do606rMl.js",
    "/assets/ManutencaoTvCristoRei-Bbh9Pky7.js",
    "/assets/ManutencaoTvEcoville-Cglg1TUn.js",
    "/assets/ManutencaoTvJardimAmericas-KGfBNg8O.js",
    "/assets/ManutencaoTvPortao-DLkS0Tjk.js",
    "/assets/ManutencaoTvReboucas-BDf8bQ6E.js",
    "/assets/ManutencaoTvSantaFelicidade-BbdnWriY.js",
    "/assets/MaracanaColombo-Bgl_EKIT.js",
    "/assets/MarcaPage-BaQFH7e0.js",
    "/assets/Marcas-DMLQgCmy.js",
    "/assets/MariaAntonieta-COMdrNqx.js",
    "/assets/Merces-BwLBnFxg.js",
    "/assets/MontagemPc-CB-SNUjG.js",
    "/assets/MontagemPcCIC-DhBd1FnN.js",
    "/assets/MonzaColombo-DK9VmW7s.js",
    "/assets/NacoesFRG-DBkzAUQ-.js",
    "/assets/NotFound-Cr6SYbWV.js",
    "/assets/NovoMundo-B6qvB97l.js",
    "/assets/Obrigado-Db4wgs_1.js",
    "/assets/OrdemDeServico-YD4G0bT1.js",
    "/assets/OswaldoCruzColombo-BjkOeXBN.js",
    "/assets/OuroFinoCL-UQsc4NVP.js",
    "/assets/OuroFinoSJP-DVScg9Gq.js",
    "/assets/PageHero-CcKWQmjV.js",
    "/assets/PageSEO-Dl01jxi-.js",
    "/assets/PalmitalCL-CqZhimKn.js",
    "/assets/PalmitalColombo-DlYQL80c.js",
    "/assets/PalmitalPinhais-vnL4wd05.js",
    "/assets/ParqueDaFonte-eQ30geeG.js",
    "/assets/ParqueNascentesPinhais-CLZn7Nye.js",
    "/assets/PassaunaAraucaria-BL414p-I.js",
    "/assets/PedroMoroSJP-DLYpFdHg.js",
    "/assets/PilarEditorialLinks-C1NANX-l.js",
    "/assets/PinevillePinhais-Dx-EXE9M.js",
    "/assets/PinhaisCentro-CQxBURqO.js",
    "/assets/Pinheirinho-DSiPSQP4.js",
    "/assets/PioneirosFRG-DUZtGE1d.js",
    "/assets/PlantaDeodoroPiraquara-DX_X1Mne.js",
    "/assets/PlantaSaoTiagoAraucaria-D513o7TZ.js",
    "/assets/PoliticaPrivacidade-5-O28Jc1.js",
    "/assets/Portao-CT2Ea2-K.js",
    "/assets/PortoDasLaranjeiras-CkXvq6aD.js",
    "/assets/PradoVelhoPiraquara-DG6enIck.js",
    "/assets/PrecoVisitaTecnica-CJbQp6b3.js",
    "/assets/PrecosEPoliticas-xEiKMP4O.js",
    "/assets/ProblemaPage-BSl4pX65.js",
    "/assets/ProblemasReaisCasos-B-CAvexb.js",
    "/assets/ProcedimentosPlaca-Cut3q93X.js",
    "/assets/QuandoNaoCompensa-sMnrMNtD.js",
    "/assets/QuissisanaSJP-3LKYPGjm.js",
    "/assets/RealImageSection-DmInC6CI.js",
    "/assets/Reboucas-DrCjoIh0.js",
    "/assets/RedesWifiAguaVerde-B-0oHiRO.js",
    "/assets/RedesWifiAltoXV-BhApI43j.js",
    "/assets/RedesWifiAraucaria-Cb1mBkqd.js",
    "/assets/RedesWifiBatel-C3eGw8WB.js",
    "/assets/RedesWifiBigorrilho-Chx-ZJCZ.js",
    "/assets/RedesWifiBoaVista-0bb-OiqD.js",
    "/assets/RedesWifiBoqueirao-CGHf06SG.js",
    "/assets/RedesWifiCIC-TD3-m3zh.js",
    "/assets/RedesWifiCabral-B8H1LJXT.js",
    "/assets/RedesWifiCajuru-4UaeEjZi.js",
    "/assets/RedesWifiCampoLargo-D-gLNmej.js",
    "/assets/RedesWifiCentro-BW4lwN48.js",
    "/assets/RedesWifiCristoRei-DiJug2sK.js",
    "/assets/RedesWifiEcoville-Dzddk587.js",
    "/assets/RedesWifiJardimAmericas-kglWv-By.js",
    "/assets/RedesWifiPinhais--EgSOH9p.js",
    "/assets/RedesWifiPortao-C6Q2mJOk.js",
    "/assets/RedesWifiReboucas-CfogYNn8.js",
    "/assets/RedesWifiSantaFelicidadeAncora-BuBHu2Fu.js",
    "/assets/RedesWifiSaoJosePinhais-DemcMTFU.js",
    "/assets/RemocaoVirusAraucaria-C-AR0prH.js",
    "/assets/RemocaoVirusBatel-CV55gVkl.js",
    "/assets/RemocaoVirusCampoLargo-Cq6NAYDp.js",
    "/assets/RemocaoVirusCentro-CR96rwJ2.js",
    "/assets/RemocaoVirusPinhais-BzDtSsSG.js",
    "/assets/RemocaoVirusPortao-CoVPOv5-.js",
    "/assets/RemocaoVirusSaoJosePinhais-0kLye9Vr.js",
    "/assets/ReviewsGrid-BfSs-cS3.js",
    "/assets/RioPequenoSJP-CfRDxCbk.js",
    "/assets/RioVerdeCM-CgyDA3ow.js",
    "/assets/RocaGrandeColombo-BU37vNy4.js",
    "/assets/RondinhaCL-Ctq_nvOW.js",
    "/assets/SabiaAraucaria-DvSd6gwt.js",
    "/assets/SantaCruzCL-DD87x0nq.js",
    "/assets/SantaFelicidade-CN6FFkiG.js",
    "/assets/SantaTerezinhaColombo-BaZOHQU7.js",
    "/assets/SantaTerezinhaFRG-BRwCiEu0.js",
    "/assets/SaoCristaoPiraquara-dNxPZuHC.js",
    "/assets/SaoCristovao-BbpCe5hq.js",
    "/assets/SaoDomingos-BYLGTtX1.js",
    "/assets/SaoFrancisco-B9pRAB4L.js",
    "/assets/SaoGabrielColombo-mrm0A1ML.js",
    "/assets/SaoJoseCampoLargo-CKMEMSui.js",
    "/assets/SaoJoseDosPinhais-Dp18TyK3.js",
    "/assets/SaoLourencoFRG-C_CSzWh7.js",
    "/assets/SaoLourencoQB-CE3WNh0h.js",
    "/assets/SaoMarcos-oBoxlITB.js",
    "/assets/SaoMarcosCampoLargo-Ua1v98aZ.js",
    "/assets/SaoMiguelAraucaria-laaGhkSt.js",
    "/assets/SaoSebastiaoCM-8TIXkvGI.js",
    "/assets/SaoSilvestreCL-Bf31shCS.js",
    "/assets/SaoVenancioAT-DU-lF2LE.js",
    "/assets/SedeCampoMagro-BNtjbAFT.js",
    "/assets/SejaParceiro-BxCqHVTI.js",
    "/assets/Seminario-DB5DQb83.js",
    "/assets/ServiceLandingSchema-CTB1gQAt.js",
    "/assets/ServiceLocalLinks-oCVo9Ps4.js",
    "/assets/ServicoBairroGerado-M8r1R_uP.js",
    "/assets/ServicoBairroTemplate-DFAsRj4y.js",
    "/assets/ServicoCidadePage-B9IAVQug.js",
    "/assets/ServicoCore-B0BwIrmP.js",
    "/assets/Servicos-OqBBVh2K.js",
    "/assets/SeteVilas-CNAXpSx3.js",
    "/assets/SitioCercado-TgBqtpnS.js",
    "/assets/Sobre-6DWPywCr.js",
    "/assets/Status-Iy_b_HaD.js",
    "/assets/TanguaAT-DWiClDr_.js",
    "/assets/Taruma-CcXJcdm7.js",
    "/assets/TaxiqueiraColomboo-Cq5uzyzZ.js",
    "/assets/TecnicoInformaticaAlmiranteTamandare-Gd-zbshq.js",
    "/assets/TecnicoInformaticaAraucaria-C7McyqCR.js",
    "/assets/TecnicoInformaticaCampoLargo-BqApEtdA.js",
    "/assets/TecnicoInformaticaCampoMagro-9PjaLD4V.js",
    "/assets/TecnicoInformaticaColombo-cxpwxUNU.js",
    "/assets/TecnicoInformaticaCuritiba-DFNyRArl.js",
    "/assets/TecnicoInformaticaCuritibaAds-CE-1tx-Y.js",
    "/assets/TecnicoInformaticaFazendaRioGrande-D7Lav-15.js",
    "/assets/TecnicoInformaticaPinhais-CXSs1yrB.js",
    "/assets/TecnicoInformaticaPiraquara-Sd0MmU1A.js",
    "/assets/TecnicoInformaticaQuatroBarras-C1YA2pSX.js",
    "/assets/TecnicoInformaticaSaoJosePinhais-CynNs6jT.js",
    "/assets/TermosCondicoes-C4Fe-kZO.js",
    "/assets/ThomazCoelhoAraucaria-BqdNppe-.js",
    "/assets/ThomazCoelhoIIAraucaria-CD4jJ7U8.js",
    "/assets/TimbotuvaCL-BOs_QevJ.js",
    "/assets/Tindiquera-m5iadBJD.js",
    "/assets/Tingui-DPiKwX41.js",
    "/assets/TranqueiraAT-UlW2izVI.js",
    "/assets/TresCorregosCL-LVgdBzIL.js",
    "/assets/TrustSection-B2f5yDyl.js",
    "/assets/Uberaba-7Uhjf0TW.js",
    "/assets/UpgradeSsdAraucaria-DG1N91v9.js",
    "/assets/UpgradeSsdBatel-BLJdHSp8.js",
    "/assets/UpgradeSsdPinhais-CFj-dTVx.js",
    "/assets/UpgradeSsdSantaFelicidade-AOMZRUU8.js",
    "/assets/UpgradeSsdSaoJosePinhais-Tnv10ghS.js",
    "/assets/ValeDasAguas-BFtERb2o.js",
    "/assets/VargemGrande-Cz6Y1Oh4.js",
    "/assets/VilaAmeliaPinhais-C5F8nTwr.js",
    "/assets/VilaCandidaCL-Dqsw8Cw8.js",
    "/assets/VilaIzabel-B_B70sFc.js",
    "/assets/VilaMacedoPiraquara-Co1htOtj.js",
    "/assets/VilaMariaAntonietaPinhais-JAR4-9am.js",
    "/assets/VilaMariaQB-CdveWNds.js",
    "/assets/VilaNovaAraucaria-BWNGf1yi.js",
    "/assets/VilaSaoJoseQB-LP689KhE.js",
    "/assets/VilaSoleneCL-B5LJGDct.js",
    "/assets/VilaTaruma-gij2QqCi.js",
    "/assets/WeissopolisPinhais-B9bX6CmD.js",
    "/assets/WhatsAppChat-Clx4HL2e.js",
    "/assets/WhatsAppChatbot-D3NGbBLH.js",
    "/assets/Xaxim-DbKU8Wpn.js",
    "/assets/accordion-BHKXPgDm.js",
    "/assets/badge-clkf-EpR.js",
    "/assets/blogEditorialCovers-ss5JLhtd.js",
    "/assets/blogEditorialRegistry-Cswl8Xbl.js",
    "/assets/blogPostsContent-CVt78Z_5.js",
    "/assets/brandsData-HmyhpRLt.js",
    "/assets/cftv-hero-C2ia0q8m.jpg",
    "/assets/cftv-hero-D_slKZ7e.js",
    "/assets/cidadesData-CQ2Z1yVj.js",
    "/assets/cities-CrX0xORL.js",
    "/assets/coletaConfig-DfBQFfwd.js",
    "/assets/editorialClusters-BG3Ovtjl.js",
    "/assets/gestorResponsavel-CnOuxL4b.js",
    "/assets/hero-arrumar-pc-belem-1280-B1pE2Xnx.jpg",
    "/assets/hero-arrumar-pc-belem-1280-BDr07QVJ.webp",
    "/assets/hero-arrumar-pc-belem-1536-BBwPyEze.webp",
    "/assets/hero-arrumar-pc-belem-1536-_8MOwOx6.jpg",
    "/assets/hero-arrumar-pc-belem-768-B1SXGyz3.webp",
    "/assets/hero-arrumar-pc-belem-768-CNZO28Yy.jpg",
    "/assets/hero-arrumar-pc-belem-DxktoJCW.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-1280-BjEvcq3H.webp",
    "/assets/hero-arrumar-pc-belo-horizonte-1280-DuzQkDn5.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-1536-BCtFhajW.webp",
    "/assets/hero-arrumar-pc-belo-horizonte-1536-D988ollT.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-768-Djf8q7_F.webp",
    "/assets/hero-arrumar-pc-belo-horizonte-768-Drh5dpWs.jpg",
    "/assets/hero-arrumar-pc-belo-horizonte-BSxL9HHs.jpg",
    "/assets/hero-arrumar-pc-brasilia-1280-BgTzv7PE.webp",
    "/assets/hero-arrumar-pc-brasilia-1280-DKbCxALX.jpg",
    "/assets/hero-arrumar-pc-brasilia-1536-B4ozxIPs.webp",
    "/assets/hero-arrumar-pc-brasilia-1536-D-y3NcLF.jpg",
    "/assets/hero-arrumar-pc-brasilia-768-BNqbKxHx.webp",
    "/assets/hero-arrumar-pc-brasilia-768-C23vaEyT.jpg",
    "/assets/hero-arrumar-pc-brasilia-BJrG6Tzc.jpg",
    "/assets/hero-arrumar-pc-campinas-1280-B8idh88g.jpg",
    "/assets/hero-arrumar-pc-campinas-1280-OUiVQh3k.webp",
    "/assets/hero-arrumar-pc-campinas-1536-CQUOI01r.webp",
    "/assets/hero-arrumar-pc-campinas-1536-DYdUj0wm.jpg",
    "/assets/hero-arrumar-pc-campinas-768-BMU96GQX.jpg",
    "/assets/hero-arrumar-pc-campinas-768-BOqqju3R.webp",
    "/assets/hero-arrumar-pc-campinas-nHsVE00G.jpg",
    "/assets/hero-arrumar-pc-campo-grande-1280-B4jI2oDe.jpg",
    "/assets/hero-arrumar-pc-campo-grande-1280-D0_YoSWL.webp",
    "/assets/hero-arrumar-pc-campo-grande-1536-BDapa_LO.jpg",
    "/assets/hero-arrumar-pc-campo-grande-1536-Be-qe0ki.webp",
    "/assets/hero-arrumar-pc-campo-grande-768-BrFZHFxA.webp",
    "/assets/hero-arrumar-pc-campo-grande-768-CVLjn6co.jpg",
    "/assets/hero-arrumar-pc-campo-grande-TosZFSpU.jpg",
    "/assets/hero-arrumar-pc-cuiaba-1280-DOszEQMA.webp",
    "/assets/hero-arrumar-pc-cuiaba-1280-DZfe7ltx.jpg",
    "/assets/hero-arrumar-pc-cuiaba-1536-CQU8YbjU.webp",
    "/assets/hero-arrumar-pc-cuiaba-1536-D6J-fuea.jpg",
    "/assets/hero-arrumar-pc-cuiaba-768-Ba_ldpQN.jpg",
    "/assets/hero-arrumar-pc-cuiaba-768-CubeosJg.webp",
    "/assets/hero-arrumar-pc-cuiaba-BHlf2rv-.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-1280-Be_PLGlN.webp",
    "/assets/hero-arrumar-pc-curitiba-nacional-1280-D_5MBzKk.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-1536-B-ZA5Wpt.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-1536-B2lKmJSI.webp",
    "/assets/hero-arrumar-pc-curitiba-nacional-768-Ak5oHfYd.webp",
    "/assets/hero-arrumar-pc-curitiba-nacional-768-CgVG2Mr1.jpg",
    "/assets/hero-arrumar-pc-curitiba-nacional-BWwBUm_G.jpg",
    "/assets/hero-arrumar-pc-florianopolis-1280-DJefZuo0.jpg",
    "/assets/hero-arrumar-pc-florianopolis-1280-jTKWhWps.webp",
    "/assets/hero-arrumar-pc-florianopolis-1536-BtX5BG-e.jpg",
    "/assets/hero-arrumar-pc-florianopolis-1536-H7Oenh5y.webp",
    "/assets/hero-arrumar-pc-florianopolis-768-CeD9bi2p.webp",
    "/assets/hero-arrumar-pc-florianopolis-768-D5f2dNq-.jpg",
    "/assets/hero-arrumar-pc-florianopolis-D14sfDAY.jpg",
    "/assets/hero-arrumar-pc-fortaleza-1280-BYIfVn80.jpg",
    "/assets/hero-arrumar-pc-fortaleza-1280-Bt5uxsol.webp",
    "/assets/hero-arrumar-pc-fortaleza-1536-CvTcUSGj.webp",
    "/assets/hero-arrumar-pc-fortaleza-1536-DzJbQpeY.jpg",
    "/assets/hero-arrumar-pc-fortaleza-768-DXi4DUct.webp",
    "/assets/hero-arrumar-pc-fortaleza-768-FBPaHVZi.jpg",
    "/assets/hero-arrumar-pc-fortaleza-wRHH5l6h.jpg",
    "/assets/hero-arrumar-pc-goiania-1280-9eigbKso.jpg",
    "/assets/hero-arrumar-pc-goiania-1280-CdS0m-GL.webp",
    "/assets/hero-arrumar-pc-goiania-1536-Qdf56Djh.jpg",
    "/assets/hero-arrumar-pc-goiania-1536-cCxfHQwi.webp",
    "/assets/hero-arrumar-pc-goiania-768-BKYsayJX.jpg",
    "/assets/hero-arrumar-pc-goiania-768-ByplqC9L.webp",
    "/assets/hero-arrumar-pc-goiania-iYlWgWMa.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-1280-Cxq_bfvV.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-1280-DK-AoGj9.webp",
    "/assets/hero-arrumar-pc-joao-pessoa-1536-1nSdR4qe.webp",
    "/assets/hero-arrumar-pc-joao-pessoa-1536-DzQj8QLv.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-768-DSNxKET9.jpg",
    "/assets/hero-arrumar-pc-joao-pessoa-768-TPlzMCEK.webp",
    "/assets/hero-arrumar-pc-joao-pessoa-DAvJEHI4.jpg",
    "/assets/hero-arrumar-pc-maceio-1280--zhzrMLG.webp",
    "/assets/hero-arrumar-pc-maceio-1280-B8h5TOIE.jpg",
    "/assets/hero-arrumar-pc-maceio-1536-Cb6-htzV.webp",
    "/assets/hero-arrumar-pc-maceio-1536-D15Mw9zd.jpg",
    "/assets/hero-arrumar-pc-maceio-768-C8x3tAYS.webp",
    "/assets/hero-arrumar-pc-maceio-768-DwrtdiIR.jpg",
    "/assets/hero-arrumar-pc-maceio-CVITa_VZ.jpg",
    "/assets/hero-arrumar-pc-manaus-1280-DXKrdiXk.jpg",
    "/assets/hero-arrumar-pc-manaus-1280-LPRsJc3O.webp",
    "/assets/hero-arrumar-pc-manaus-1536-BVC4euou.webp",
    "/assets/hero-arrumar-pc-manaus-1536-JSa2FuIw.jpg",
    "/assets/hero-arrumar-pc-manaus-768-DLlwWGqZ.webp",
    "/assets/hero-arrumar-pc-manaus-768-LvjUtfMr.jpg",
    "/assets/hero-arrumar-pc-manaus-CX14Fnfy.jpg",
    "/assets/hero-arrumar-pc-natal-1280-DpYNYWEc.jpg",
    "/assets/hero-arrumar-pc-natal-1280-dv-EJwW6.webp",
    "/assets/hero-arrumar-pc-natal-1536-DF_RbzZf.jpg",
    "/assets/hero-arrumar-pc-natal-1536-DQmHdSt8.webp",
    "/assets/hero-arrumar-pc-natal-768-5esMPnYy.webp",
    "/assets/hero-arrumar-pc-natal-768-DJ98N1On.jpg",
    "/assets/hero-arrumar-pc-natal-D_GghYn2.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-1280-DNLI6ls5.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-1280-Dtpfn-sZ.webp",
    "/assets/hero-arrumar-pc-porto-alegre-1536-CLbxAsmF.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-1536-KnbkDg90.webp",
    "/assets/hero-arrumar-pc-porto-alegre-768-BOXam7Lf.jpg",
    "/assets/hero-arrumar-pc-porto-alegre-768-Bf1DIKYd.webp",
    "/assets/hero-arrumar-pc-porto-alegre-C1HXpLeH.jpg",
    "/assets/hero-arrumar-pc-recife-1280-BuF3jnPO.jpg",
    "/assets/hero-arrumar-pc-recife-1280-U34QHSDJ.webp",
    "/assets/hero-arrumar-pc-recife-1536-C2bRnBek.webp",
    "/assets/hero-arrumar-pc-recife-1536-UmGWnRhs.jpg",
    "/assets/hero-arrumar-pc-recife-768-Bve6S0N8.jpg",
    "/assets/hero-arrumar-pc-recife-768-CDCVyTKs.webp",
    "/assets/hero-arrumar-pc-recife-ByaKL3AR.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1280-Ch6Ju853.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1280-D-VF46hJ.webp",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1536-CLS2aK4R.webp",
    "/assets/hero-arrumar-pc-rio-de-janeiro-1536-DOZOhL2f.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-768-BPWerF76.webp",
    "/assets/hero-arrumar-pc-rio-de-janeiro-768-uJTXjCtx.jpg",
    "/assets/hero-arrumar-pc-rio-de-janeiro-DIU38_Kc.jpg",
    "/assets/hero-arrumar-pc-salvador-1280-Dy-EHWlJ.jpg",
    "/assets/hero-arrumar-pc-salvador-1280-zvzVtimH.webp",
    "/assets/hero-arrumar-pc-salvador-1536-BsqjXETZ.webp",
    "/assets/hero-arrumar-pc-salvador-1536-CJN5X22Q.jpg",
    "/assets/hero-arrumar-pc-salvador-768-BEnlrXym.webp",
    "/assets/hero-arrumar-pc-salvador-768-BrUyiC20.jpg",
    "/assets/hero-arrumar-pc-salvador-pyYTkeL7.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-1280-BgrMWAzd.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-1280-DMXNT82x.webp",
    "/assets/hero-arrumar-pc-sao-paulo-1536-BX8gJuVx.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-1536-CPlriY0v.webp",
    "/assets/hero-arrumar-pc-sao-paulo-768--F4CiZVy.jpg",
    "/assets/hero-arrumar-pc-sao-paulo-768-BDYo1f9p.webp",
    "/assets/hero-arrumar-pc-sao-paulo-UqvB6GPs.jpg",
    "/assets/hero-arrumar-pc-vitoria-1280-B8EbfrVj.webp",
    "/assets/hero-arrumar-pc-vitoria-1280-D3vxeyqV.jpg",
    "/assets/hero-arrumar-pc-vitoria-1536-BAkEkapH.webp",
    "/assets/hero-arrumar-pc-vitoria-1536-BQZenwLq.jpg",
    "/assets/hero-arrumar-pc-vitoria-768-B5Y_HUpe.webp",
    "/assets/hero-arrumar-pc-vitoria-768-CuncjJhZ.jpg",
    "/assets/hero-arrumar-pc-vitoria-ysV1gJDF.jpg",
    "/assets/hero-jardim-botanico-Bl121eXV.webp",
    "/assets/hero-jardim-botanico-COGeHOBY.webp",
    "/assets/hero-jardim-botanico-CvQKAyOl.avif",
    "/assets/hero-jardim-botanico-Cy-2ic_K.webp",
    "/assets/hero-jardim-botanico-D0L9seYu.avif",
    "/assets/hero-jardim-botanico-DQRYEK5k.jpeg",
    "/assets/hero-jardim-botanico-DS6V-VsA.avif",
    "/assets/hero-jardim-botanico-m2pBKRSC.jpeg",
    "/assets/hero-jardim-botanico-xxHx1Qkz.jpeg",
    "/assets/hero-opera-de-arame-4N5lNii2.jpeg",
    "/assets/hero-opera-de-arame-B6JvbxUM.avif",
    "/assets/hero-opera-de-arame-B8QbpXqR.webp",
    "/assets/hero-opera-de-arame-BLV2k7Jt.jpeg",
    "/assets/hero-opera-de-arame-BPiz6ENY.webp",
    "/assets/hero-opera-de-arame-BiXhCRi1.avif",
    "/assets/hero-opera-de-arame-ByzuxneY.webp",
    "/assets/hero-opera-de-arame-CKH21uEx.jpeg",
    "/assets/hero-opera-de-arame-PW3JQ5gI.avif",
    "/assets/hero-oscar-niemeyer-BBr3aXSu.jpeg",
    "/assets/hero-oscar-niemeyer-BKx9lI8P.webp",
    "/assets/hero-oscar-niemeyer-CUBI5pdq.jpeg",
    "/assets/hero-oscar-niemeyer-CwxyYoE_.avif",
    "/assets/hero-oscar-niemeyer-D-yYXTSS.webp",
    "/assets/hero-oscar-niemeyer-DIVh-ZTZ.jpeg",
    "/assets/hero-oscar-niemeyer-Ed0ZLjgg.avif",
    "/assets/hero-oscar-niemeyer-e0tYcT3s.avif",
    "/assets/hero-oscar-niemeyer-xVFoNzhT.webp",
    "/assets/hero-parque-tangua-B9fINM_5.avif",
    "/assets/hero-parque-tangua-Bl0u2WHq.webp",
    "/assets/hero-parque-tangua-Bu9bA1I5.avif",
    "/assets/hero-parque-tangua-CMrXq1EY.jpeg",
    "/assets/hero-parque-tangua-CO9tOZdK.jpeg",
    "/assets/hero-parque-tangua-DHLBNrLl.webp",
    "/assets/hero-parque-tangua-P_VYBcjH.webp",
    "/assets/hero-parque-tangua-T9JFb8xw.avif",
    "/assets/hero-parque-tangua-ubKHMI3T.jpeg",
    "/assets/images-DrOI4iuo.js",
    "/assets/index-0TjAzhpZ.css",
    "/assets/index-DDdnZZw_.css",
    "/assets/index-YecTtupC.js",
    "/assets/index-lO1I95sm.js",
    "/assets/label-DUrAoQoP.js",
    "/assets/og-arrumar-pc-belem-Baw5HNjK.jpg",
    "/assets/og-arrumar-pc-belo-horizonte-Dzo9gC4g.jpg",
    "/assets/og-arrumar-pc-brasil-CubHo-x4.jpg",
    "/assets/og-arrumar-pc-brasilia-zPwVmPff.jpg",
    "/assets/og-arrumar-pc-campinas-C9AjH1L9.jpg",
    "/assets/og-arrumar-pc-campo-grande-BEDxfEwN.jpg",
    "/assets/og-arrumar-pc-cuiaba-D3pFMUV_.jpg",
    "/assets/og-arrumar-pc-curitiba-nacional-DeURmIkp.jpg",
    "/assets/og-arrumar-pc-florianopolis-DLdHSpz8.jpg",
    "/assets/og-arrumar-pc-fortaleza-Byw-lRGT.jpg",
    "/assets/og-arrumar-pc-goiania-Ql2v0KVb.jpg",
    "/assets/og-arrumar-pc-joao-pessoa-B4RnoMoj.jpg",
    "/assets/og-arrumar-pc-maceio-BRkoRhdb.jpg",
    "/assets/og-arrumar-pc-manaus-CmkkcZCu.jpg",
    "/assets/og-arrumar-pc-natal-DLotTjYz.jpg",
    "/assets/og-arrumar-pc-porto-alegre-D30G9ffS.jpg",
    "/assets/og-arrumar-pc-recife-Bs68c_MX.jpg",
    "/assets/og-arrumar-pc-rio-de-janeiro-DbixX1zN.jpg",
    "/assets/og-arrumar-pc-salvador-UgtH5GH8.jpg",
    "/assets/og-arrumar-pc-sao-paulo-DeK1gSYG.jpg",
    "/assets/og-arrumar-pc-vitoria-xGC6Okn6.jpg",
    "/assets/ogCacheBust-CdZWbORc.js",
    "/assets/politicaComercial-CIdINzbs.js",
    "/assets/precosConfig-Dye353A_.js",
    "/assets/problemaPagesData-Cr0njMLd.js",
    "/assets/select-CUOMrG0b.js",
    "/assets/servicoCidadeData-CMGzgn25.js",
    "/assets/servicosCore-CN1DLmOB.js",
    "/assets/sonner-F-VsefD9.js",
    "/assets/toaster-KbNO9CjX.js",
    "/assets/use-toast-Y3g5TK3t.js",
    "/assets/useAdminAuth-OCkoin-G.js",
    "/assets/vendor-BXKp90Nh.js",
    "/assets/webVitals-erOU0amC.js",
    "/assets/whatsappUtm-BElvX8wo.js",
    "/assets/wifiTvBairroData-C2IXoFec.js",
    "/assets/windows-11-kb5074105-update-CNLAHtC2.jpg",
    "/blog/backup-como-proteger-seus-arquivos.jpg",
    "/blog/como-melhorar-sinal-wifi-em-casa.jpg",
    "/blog/como-saber-se-pc-tem-virus-malware.jpg",
    "/blog/computador-lento-causas-solucoes.jpg",
    "/blog/notebook-nao-liga-o-que-fazer.jpg",
    "/blog/quando-trocar-hd-por-ssd.jpg",
    "/css/style.css",
    "/dynamic-slugs.json",
    "/f783ab585dfa9e6b017cb058009cccae.txt",
    "/favicon-20260624.ico",
    "/favicon-20260624.png",
    "/favicon-32-20260624.png",
    "/favicon-32.png",
    "/favicon.ico",
    "/favicon.png",
    "/fonts/montserrat-var.woff2",
    "/fonts/poppins-600.woff2",
    "/fonts/poppins-700.woff2",
    "/llms-full.txt",
    "/llms.txt",
    "/logo.webp",
    "/lovable-uploads/1c69699b-770f-4ea3-bd50-34bb6823a3b5.png",
    "/lovable-uploads/22325e55-7640-4775-99b0-4d43b5cad21d.png",
    "/lovable-uploads/279c1746-6e5b-4d0e-93d4-976d837ecec0.png",
    "/lovable-uploads/53d9783d-317d-495e-86b6-22371a986744.png",
    "/lovable-uploads/727e8770-4368-4aa5-a5a5-e495f01d9124.png",
    "/lovable-uploads/7364f9af-20c4-4e14-8105-585235697ca1.png",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-240.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-360.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-480.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859-800.webp",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859.png",
    "/lovable-uploads/77ec0b6a-9ce8-4e20-b893-7eff7ec03859.webp",
    "/lovable-uploads/829c2c24-8525-4b99-8cad-42c8cfc83a91.png",
    "/lovable-uploads/87899615-1234-4c6d-a8ca-ee38ec566ef4.png",
    "/lovable-uploads/87899615-1234-4c6d-a8ca-ee38ec566ef4.webp",
    "/lovable-uploads/97228481-0bbd-4d82-a9aa-bcc0212e1c7b.png",
    "/lovable-uploads/b2277aaf-f886-48c7-822a-6a5d1e266855.png",
    "/lovable-uploads/b702f033-fd78-4d1e-ae32-2ad60f672710.png",
    "/lovable-uploads/b702f033-fd78-4d1e-ae32-2ad60f672710.webp",
    "/lovable-uploads/c858cf99-e05f-4d8f-a05a-c741ebfabfea.png",
    "/lovable-uploads/c858cf99-e05f-4d8f-a05a-c741ebfabfea.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302-1200.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302-400.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302-800.webp",
    "/lovable-uploads/cover-celular-curitiba.373a7302.jpg",
    "/lovable-uploads/cover-celular-curitiba.jpg",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89-1200.webp",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89-400.webp",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89-800.webp",
    "/lovable-uploads/cover-wifi-curitiba.fdcb2d89.jpg",
    "/lovable-uploads/cover-wifi-curitiba.jpg",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b-1200.webp",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b-400.webp",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b-800.webp",
    "/lovable-uploads/cover-windows-curitiba.8f6a333b.jpg",
    "/lovable-uploads/cover-windows-curitiba.jpg",
    "/lovable-uploads/f6b6dc27-d68d-4f00-9c1f-c407ef986264.png",
    "/lovable-uploads/ff1b2738-e2a0-4b39-bdb7-47b8b71e33cb.png",
    "/manifest.json",
    "/og-image.png",
    "/placeholder.svg",
    "/robots.txt",
    "/sitemap-bairros.xml",
    "/sitemap-editorial.xml",
    "/sitemap-index.xml",
    "/sitemap-main.xml",
    "/sitemap-marcas.xml",
    "/sitemap-news.xml",
    "/sitemap-problemas.xml",
    "/sitemap-regioes.xml",
    "/sitemap-servicos.xml",
    "/sitemap.xml"
  ],
  curated: [
    "/",
    "/atendimento-domicilio",
    "/atendimento-remoto",
    "/bairros/agua-verde",
    "/bairros/batel",
    "/bairros/centro",
    "/bairros/cic",
    "/bairros/portao",
    "/blog",
    "/blog/backup-como-proteger-seus-arquivos",
    "/blog/como-melhorar-sinal-wifi-em-casa",
    "/blog/como-saber-se-pc-tem-virus-malware",
    "/blog/computador-lento-causas-solucoes",
    "/blog/notebook-nao-liga-o-que-fazer",
    "/blog/quando-trocar-hd-por-ssd",
    "/coleta-e-entrega",
    "/como-funciona",
    "/contato",
    "/diagnostico-tecnico",
    "/empresa-de-ti-curitiba",
    "/equipamentos-atendidos",
    "/faq",
    "/precos-e-politicas",
    "/quando-nao-compensa",
    "/servicos",
    "/servicos/conserto-pc-notebook/agua-verde",
    "/servicos/conserto-pc-notebook/centro",
    "/servicos/formatacao",
    "/servicos/formatacao-computador/agua-verde",
    "/servicos/formatacao-computador/batel",
    "/servicos/formatacao-computador/cic",
    "/servicos/manutencao-de-computador",
    "/servicos/manutencao-de-notebook",
    "/servicos/recuperacao-de-dados",
    "/servicos/redes-e-wifi",
    "/servicos/remocao-de-virus",
    "/servicos/remocao-virus/agua-verde",
    "/servicos/remocao-virus/cic",
    "/servicos/suporte-tecnico-empresarial",
    "/servicos/upgrade-ssd-memoria/agua-verde",
    "/servicos/upgrade-ssd-memoria/centro",
    "/servicos/upgrade-ssd-memoria/cic",
    "/servicos/upgrade-ssd-memoria/portao",
    "/servicos/upgrade-ssd-ram",
    "/sobre",
    "/tecnico-informatica-araucaria",
    "/tecnico-informatica-campo-largo",
    "/tecnico-informatica-colombo",
    "/tecnico-informatica-curitiba",
    "/tecnico-informatica-pinhais",
    "/tecnico-informatica-sao-jose-pinhais"
  ]
};

// worker.js
import notFoundHtml from "./b2fdf587cd4d0ec8b704f5030f514c5f321a22b8-404.html";

// ../scripts/lib/edge-router.mjs
var ORIGIN_PLACEHOLDER = "LOVABLE_ORIGIN_NOT_CONFIGURED";
var ALLOWED_HOSTS = ["tecnico.curitiba.br", "www.tecnico.curitiba.br"];
var MANIFEST_MINIMUMS = {
  validExact: 200,
  redirects: 1,
  assetFiles: 5
};
function normalizePath(rawPath) {
  if (typeof rawPath !== "string" || rawPath === "") return null;
  let p = rawPath;
  if (!p.startsWith("/")) return null;
  if (/[\u0000-\u001f\u007f]/.test(p)) return null;
  try {
    p = decodeURIComponent(p);
  } catch {
    return null;
  }
  if (/[\u0000-\u001f\u007f]/.test(p)) return null;
  const out = [];
  for (const seg of p.split("/")) {
    if (seg === "" || seg === ".") continue;
    if (seg === "..") {
      if (out.length === 0) return null;
      out.pop();
      continue;
    }
    out.push(seg);
  }
  const normalized = `/${out.join("/")}`;
  return normalized === "/" ? "/" : normalized.replace(/\/+$/, "");
}
__name(normalizePath, "normalizePath");
function compileManifest(manifest) {
  if (!manifest || typeof manifest !== "object") throw new Error("manifesto ausente");
  const exact = new Set((manifest.validExact ?? []).map((p) => normalizePath(p) ?? p));
  const patternInfo = manifest.patternInfo ?? (manifest.validPatterns ?? []).map((pattern) => ({ pattern, closed: false }));
  const openPatterns = patternInfo.filter((p) => !p.closed).map((p) => pathToRegex(p.pattern));
  const redirects = /* @__PURE__ */ new Map();
  for (const r of manifest.redirects ?? []) {
    const from = normalizePath(r.from ?? r[0]);
    if (from) redirects.set(from, r.to ?? r[1]);
  }
  const assetFiles = new Set((manifest.assetFiles ?? []).map((f) => f.startsWith("/") ? f : `/${f}`));
  return {
    exact,
    openPatterns,
    redirects,
    assetFiles,
    counts: {
      validExact: exact.size,
      redirects: redirects.size,
      assetFiles: assetFiles.size
    }
  };
}
__name(compileManifest, "compileManifest");
function pathToRegex(routePath) {
  const source = routePath.split("/").filter(Boolean).map((seg) => seg === "*" || seg.startsWith(":") ? "[^/]+" : seg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("/");
  return new RegExp(`^/${source}/?$`);
}
__name(pathToRegex, "pathToRegex");
function assertManifestSane(compiled2) {
  const problems = [];
  for (const [key, min] of Object.entries(MANIFEST_MINIMUMS)) {
    if (compiled2.counts[key] < min) problems.push(`${key}=${compiled2.counts[key]} < m\xEDnimo ${min}`);
  }
  return problems;
}
__name(assertManifestSane, "assertManifestSane");
var looksLikeFile = /* @__PURE__ */ __name((p) => /\.[a-z0-9]{1,8}$/i.test(p), "looksLikeFile");
function decide(req, m) {
  const host = String(req.host ?? "").toLowerCase().split(":")[0];
  if (!ALLOWED_HOSTS.includes(host)) return { action: "reject", status: 421, reason: "host-nao-permitido" };
  const pathname = normalizePath(req.pathname);
  if (pathname === null) return { action: "notfound", status: 404, reason: "path-malformado" };
  const search = req.search ?? "";
  const target = m.redirects.get(pathname);
  if (target) {
    const location = target.includes("?") || !search ? target : `${target}${search}`;
    return { action: "redirect", status: 301, location, reason: "alias" };
  }
  if (looksLikeFile(pathname)) {
    if (m.assetFiles.has(pathname)) return { action: "asset", status: 200, reason: "asset-existente" };
    return { action: "notfound", status: 404, reason: "asset-inexistente" };
  }
  if (m.exact.has(pathname) || m.openPatterns.some((re) => re.test(pathname))) {
    return { action: "proxy", status: 200, reason: "rota-valida" };
  }
  return { action: "notfound", status: 404, reason: "rota-inexistente" };
}
__name(decide, "decide");

// worker.js
var compiled = compileManifest(route_manifest_default);
var manifestProblems = assertManifestSane(compiled);
var NOT_FOUND_HEADERS = {
  "content-type": "text/html; charset=UTF-8",
  "cache-control": "no-store",
  "x-robots-tag": "noindex, nofollow"
};
function notFound(method) {
  const body = method === "HEAD" ? null : notFoundHtml;
  return new Response(body, { status: 404, headers: NOT_FOUND_HEADERS });
}
__name(notFound, "notFound");
var worker_default = {
  async fetch(request, env) {
    if (manifestProblems.length) {
      return new Response("edge desabilitado: manifesto inv\xE1lido", { status: 503 });
    }
    const url = new URL(request.url);
    const d = decide({ host: url.hostname, method: request.method, pathname: url.pathname, search: url.search }, compiled);
    if (d.action === "reject") return new Response("host n\xE3o atendido", { status: 421 });
    if (d.action === "redirect") {
      const location = new URL(d.location, url.origin).toString();
      return new Response(null, {
        status: 301,
        headers: { location, "cache-control": "public, max-age=86400" }
      });
    }
    if (d.action === "notfound") return notFound(request.method);
    const mode = env?.ORIGIN_MODE ?? "dns";
    if (mode === "dns") return fetch(request);
    const origin = env?.LOVABLE_ORIGIN ?? ORIGIN_PLACEHOLDER;
    if (origin === ORIGIN_PLACEHOLDER) {
      return new Response("origem n\xE3o configurada", { status: 503 });
    }
    const target = new URL(url.pathname + url.search, `https://${origin}`);
    const proxied = new Request(target.toString(), request);
    proxied.headers.set("host", origin);
    proxied.headers.set("x-forwarded-host", url.hostname);
    return fetch(proxied);
  }
};
export {
  worker_default as default
};
//# sourceMappingURL=worker.js.map
