/**
 * Data for all supported tech brands — used by TechBrandsMarquee and MarcaPage.
 * Each brand has a slug, display name, inline SVG path for the logo icon,
 * description, services offered, and recent news/updates.
 */
// @ts-nocheck


export interface BrandInfo {
  slug: string;
  name: string;
  /** SVG viewBox default is "0 0 24 24" — path data only */
  logoPath: string;
  /** Optional secondary path for two-tone logos */
  logoPath2?: string;
  color: string; // brand accent color (HSL or hex for the logo tint)
  description: string;
  fundacao: string;
  sede: string;
  servicos: string[];
  novidades: { titulo: string; texto: string; data: string }[];
  dicasManutencao: string[];
  problemasComuns: { problema: string; solucao: string }[];
}

export const brandsData: BrandInfo[] = [
  {
    slug: "dell",
    name: "Dell",
    logoPath: "M21.8 7.8H16l-4 8.4L7.9 7.8H2.2L8.5 20h3l2.7-5.5L16.8 20h3L21.8 7.8z",
    color: "#007DB8",
    description: "A Dell Technologies é líder mundial em computadores, servidores e soluções corporativas. Fundada por Michael Dell, a marca é referência em notebooks robustos e desktops de alto desempenho.",
    fundacao: "1984",
    sede: "Round Rock, Texas, EUA",
    servicos: ["Conserto de notebook Dell", "Upgrade de SSD e RAM em Dell", "Formatação de Dell Inspiron, Vostro e Latitude", "Troca de tela Dell", "Reparo de placa-mãe Dell"],
    novidades: [
      { titulo: "Dell XPS 2026 com IA integrada", texto: "A nova linha XPS traz processadores com NPU dedicada para tarefas de inteligência artificial local, além de tela OLED de 14 polegadas com HDR 1000.", data: "2026-03" },
      { titulo: "Dell Latitude com 5G nativo", texto: "Os modelos corporativos Latitude agora vêm com conectividade 5G integrada, ideal para profissionais em campo.", data: "2026-02" },
      { titulo: "Programa Dell Recondicionados", texto: "A Dell ampliou seu programa de equipamentos recondicionados com garantia de fábrica, reduzindo o lixo eletrônico.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Atualize os drivers pelo Dell SupportAssist regularmente",
      "Limpe as saídas de ar a cada 6 meses para evitar superaquecimento",
      "Use a bateria entre 20% e 80% para prolongar a vida útil",
      "Faça backup com Dell Backup and Recovery antes de formatações",
    ],
    problemasComuns: [
      { problema: "Notebook Dell não liga", solucao: "Remova a bateria, segure o botão power por 30s, reconecte e tente novamente. Se persistir, pode ser problema na placa-mãe." },
      { problema: "Tela piscando no Dell Inspiron", solucao: "Atualize os drivers de vídeo pelo Dell SupportAssist. Em muitos casos, é incompatibilidade de driver após atualização do Windows." },
      { problema: "Dell Latitude lento após atualização", solucao: "Desative programas de inicialização desnecessários e considere um upgrade de SSD. Notebooks com HD mecânico ficam muito lentos com o Windows 11." },
    ],
  },
  {
    slug: "hp",
    name: "HP",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1.5 14.5H8V7.5h2.5l2 4.5 2-4.5H17v9h-2.5v-5.5l-2 4.5-2-4.5v5.5z",
    color: "#0096D6",
    description: "A HP (Hewlett-Packard) é uma das maiores fabricantes de computadores e impressoras do mundo. Seus notebooks das linhas Pavilion, Envy e ProBook são amplamente utilizados no Brasil.",
    fundacao: "1939",
    sede: "Palo Alto, Califórnia, EUA",
    servicos: ["Conserto de notebook HP", "Reparo de impressora HP", "Upgrade de memória HP Pavilion", "Formatação HP Envy e ProBook", "Troca de teclado HP"],
    novidades: [
      { titulo: "HP OmniBook Ultra com Snapdragon X", texto: "A HP lançou a nova linha OmniBook com processador ARM, prometendo até 26 horas de bateria em uso real.", data: "2026-03" },
      { titulo: "Impressoras HP+ com assinatura de tinta", texto: "O programa HP Instant Ink agora oferece planos a partir de R$9,90/mês com tinta entregue automaticamente.", data: "2026-02" },
      { titulo: "HP amplia garantia no Brasil", texto: "Notebooks HP comprados em 2026 terão 2 anos de garantia de fábrica no Brasil.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o HP Support Assistant para manter drivers atualizados",
      "Limpe o cabeçote da impressora HP mensalmente para evitar entupimento",
      "Notebooks HP Pavilion: verifique a pasta térmica a cada 2 anos",
      "Evite usar carregadores genéricos — podem danificar a porta de carga",
    ],
    problemasComuns: [
      { problema: "Impressora HP não imprime", solucao: "Execute o diagnóstico pelo HP Smart. Geralmente é cabeçote entupido ou driver desatualizado." },
      { problema: "HP Pavilion superaquecendo", solucao: "Limpe as saídas de ar com ar comprimido e considere trocar a pasta térmica. Modelos com i5/i7 sofrem mais." },
      { problema: "Tela preta no HP Envy", solucao: "Faça um hard reset: desconecte tudo, segure power 15s. Se não resolver, pode ser problema no flex da tela." },
    ],
  },
  {
    slug: "lenovo",
    name: "Lenovo",
    logoPath: "M2 7h20v10H2V7zm2 2v6h16V9H4zm3 1h2v4H7v-4zm3 0h2v4h-2v-4zm3 0h2v4h-2v-4z",
    color: "#E2231A",
    description: "A Lenovo é a maior fabricante de PCs do mundo, conhecida pelos robustos ThinkPad (linha corporativa) e pelos populares IdeaPad. A marca chinesa adquiriu a divisão de PCs da IBM.",
    fundacao: "1984",
    sede: "Pequim, China",
    servicos: ["Conserto de Lenovo ThinkPad", "Upgrade de SSD NVMe Lenovo", "Formatação de Lenovo IdeaPad", "Troca de tela Lenovo", "Reparo de dobradiça Lenovo Yoga"],
    novidades: [
      { titulo: "ThinkPad X1 Carbon Gen 14", texto: "O novo ThinkPad X1 vem com Intel Core Ultra e tela OLED de 2.8K. Pesa apenas 1.08kg.", data: "2026-03" },
      { titulo: "Lenovo Legion Go 2", texto: "O console portátil da Lenovo recebeu uma atualização com chip AMD Z2 Extreme e tela de 8.8 polegadas.", data: "2026-02" },
      { titulo: "IdeaPad Slim com IA", texto: "A linha IdeaPad Slim 2026 traz assistente IA integrado para otimização automática de desempenho e bateria.", data: "2026-01" },
    ],
    dicasManutencao: [
      "ThinkPads permitem upgrade fácil — aproveite para adicionar RAM e SSD",
      "Use o Lenovo Vantage para atualizações de BIOS e drivers",
      "Calibre a bateria a cada 3 meses (carregue 100%, descarregue até 5%)",
      "Modelos Yoga: cuidado ao abrir a tela além de 360° com força",
    ],
    problemasComuns: [
      { problema: "Lenovo IdeaPad lento", solucao: "O IdeaPad com HD mecânico fica muito lento. Upgrade para SSD resolve 90% dos casos de lentidão." },
      { problema: "Teclado do ThinkPad com teclas falhando", solucao: "Pode ser sujeira acumulada. Limpeza com ar comprimido resolve na maioria dos casos. Se não, troca do teclado." },
      { problema: "Lenovo Yoga tela tremendo", solucao: "Geralmente é o cabo flat da tela que se desgasta com o uso em modo tablet. Troca do flat resolve." },
    ],
  },
  {
    slug: "asus",
    name: "ASUS",
    logoPath: "M12 2L2 19h20L12 2zm0 4l6.5 11h-13L12 6z",
    color: "#00539B",
    description: "A ASUS é referência em notebooks gamers (ROG), placas-mãe e equipamentos de alto desempenho. Também fabrica roteadores Wi-Fi considerados entre os melhores do mercado.",
    fundacao: "1989",
    sede: "Taipei, Taiwan",
    servicos: ["Conserto de ASUS ROG", "Upgrade de ASUS VivoBook", "Reparo de placa-mãe ASUS", "Configuração de roteador ASUS", "Formatação de ASUS ZenBook"],
    novidades: [
      { titulo: "ASUS ROG Strix 2026 com RTX 5070", texto: "A linha ROG Strix recebeu as novas GPUs NVIDIA RTX 5070, com desempenho 40% superior à geração anterior.", data: "2026-03" },
      { titulo: "ASUS ZenBook com tela dobrável", texto: "O novo ZenBook 17 Fold traz tela OLED dobrável de 17.3 polegadas que pode ser usado como dois monitores.", data: "2026-02" },
      { titulo: "Roteadores ASUS Wi-Fi 7", texto: "A ASUS lançou roteadores Wi-Fi 7 com velocidades de até 19Gbps e cobertura mesh inteligente.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Notebooks ROG: monitore temperaturas com o MyASUS e limpe coolers semestralmente",
      "Atualize a BIOS pelo ASUS EZ Update para melhorar estabilidade",
      "Roteadores ASUS: atualize o firmware regularmente para segurança",
      "VivoBook: evite usar em superfícies macias que bloqueiam a ventilação",
    ],
    problemasComuns: [
      { problema: "ASUS ROG superaquecendo em jogos", solucao: "Ative o modo Turbo no Armoury Crate. Limpe os coolers e troque a pasta térmica se tiver mais de 1 ano de uso." },
      { problema: "ASUS VivoBook sem Wi-Fi", solucao: "Verifique se o modo avião não está ativado (Fn+F2). Atualize o driver Wi-Fi pelo MyASUS." },
      { problema: "Placa-mãe ASUS não dá POST", solucao: "Faça o procedimento de CMOS reset. Remova a bateria da BIOS por 30 segundos e recoloque." },
    ],
  },
  {
    slug: "acer",
    name: "Acer",
    logoPath: "M3 12l3-7h2l-3 7 3 7H6l-3-7zm6-7h2l3 7-3 7h-2l3-7-3-7zm6 0h2l3 7-3 7h-2l3-7-3-7z",
    color: "#83B81A",
    description: "A Acer é conhecida pelos notebooks com excelente custo-benefício, como as linhas Aspire e Nitro. Também é forte em monitores gamer da linha Predator.",
    fundacao: "1976",
    sede: "Taipei, Taiwan",
    servicos: ["Conserto de Acer Aspire", "Upgrade de Acer Nitro", "Formatação de Acer Swift", "Troca de tela Acer", "Reparo de carregador Acer"],
    novidades: [
      { titulo: "Acer Nitro V com RTX 4060", texto: "O novo Nitro V oferece RTX 4060 por um preço acessível, tornando-o um dos melhores custo-benefício gamer.", data: "2026-03" },
      { titulo: "Acer Swift Go 14 com OLED", texto: "O ultrabook Swift Go agora vem com tela OLED de 14 polegadas e bateria para 15 horas.", data: "2026-02" },
      { titulo: "Monitor Predator XB3 com 240Hz", texto: "O novo monitor gamer da Acer traz painel IPS de 27 polegadas com 240Hz e 0.5ms.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Acer Nitro: limpe os coolers a cada 4 meses para jogos — esquenta muito",
      "Use o Acer Care Center para diagnósticos e atualizações",
      "Aspire: upgrade de RAM para 16GB faz grande diferença no desempenho",
      "Cuidado com a dobradiça — modelos Aspire têm dobradiça frágil",
    ],
    problemasComuns: [
      { problema: "Acer Aspire não carrega", solucao: "Verifique se o LED do carregador acende. Muitos Aspire têm problema no conector DC — pode precisar de troca." },
      { problema: "Acer Nitro travando em jogos", solucao: "Limpe os coolers, troque a pasta térmica e verifique se os drivers da NVIDIA estão atualizados." },
      { problema: "Tela do Acer com manchas", solucao: "Manchas escuras na tela geralmente indicam pressão no painel LCD. É necessário trocar a tela." },
    ],
  },
  {
    slug: "samsung",
    name: "Samsung",
    logoPath: "M3 8.5C3 7.67 3.67 7 4.5 7h15c.83 0 1.5.67 1.5 1.5v9c0 .83-.67 1.5-1.5 1.5h-15C3.67 19 3 18.33 3 17.5v-9zM5 9v8h14V9H5zm2 2h2v4H7v-4zm3 0h1v4h-1v-4zm2 0h2v4h-2v-4zm3 0h1v4h-1v-4z",
    color: "#1428A0",
    description: "A Samsung é gigante em eletrônicos, desde smartphones Galaxy até TVs, monitores e SSDs. Seus SSDs da linha EVO e PRO são referência em desempenho e confiabilidade.",
    fundacao: "1938",
    sede: "Seul, Coreia do Sul",
    servicos: ["Conserto de Smart TV Samsung", "Upgrade com SSD Samsung EVO", "Formatação de notebook Samsung", "Reparo de celular Samsung Galaxy", "Configuração de monitor Samsung"],
    novidades: [
      { titulo: "Samsung Galaxy S26 Ultra com IA Generativa", texto: "O Galaxy S26 Ultra traz recursos avançados de IA generativa, incluindo tradução em tempo real e edição de fotos com IA.", data: "2026-03" },
      { titulo: "SSD Samsung 990 EVO Plus", texto: "O novo SSD NVMe da Samsung atinge 7.450MB/s de leitura sequencial, ideal para gamers e profissionais.", data: "2026-02" },
      { titulo: "Samsung TV OLED S95F", texto: "A TV OLED 4K de 77 polegadas da Samsung com processador Neural Quantum oferece qualidade de cinema em casa.", data: "2026-01" },
    ],
    dicasManutencao: [
      "SSDs Samsung: use o Samsung Magician para monitorar saúde e atualizar firmware",
      "Smart TVs: reinicie mensalmente para limpar cache e melhorar desempenho",
      "Galaxy: use o Samsung Smart Switch para backups completos",
      "Monitores: calibre as cores com o modo sRGB para trabalho profissional",
    ],
    problemasComuns: [
      { problema: "Smart TV Samsung não liga", solucao: "Desconecte da tomada por 60 segundos. Se piscar o LED, pode ser problema na placa de energia." },
      { problema: "SSD Samsung não detectado", solucao: "Verifique se o SSD está bem encaixado no slot M.2. Atualize a BIOS e verifique se NVMe está habilitado." },
      { problema: "Galaxy com tela fantasma", solucao: "Tela AMOLED com burn-in. Em casos leves, apps de correção ajudam. Em casos graves, troca da tela." },
    ],
  },
  {
    slug: "lg",
    name: "LG",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c3.87 0 7 3.13 7 7h-4c0-1.66-1.34-3-3-3V5zm0 2c2.76 0 5 2.24 5 5h-2c0-1.66-1.34-3-3-3V7z",
    color: "#A50034",
    description: "A LG é referência em TVs, monitores ultrawide e eletrodomésticos inteligentes. Seus painéis OLED são considerados os melhores do mercado para qualidade de imagem.",
    fundacao: "1958",
    sede: "Seul, Coreia do Sul",
    servicos: ["Conserto de TV LG", "Reparo de monitor LG Ultrawide", "Manutenção de TV LG OLED", "Configuração de Smart TV LG", "Reparo de placa de TV LG"],
    novidades: [
      { titulo: "LG OLED Evo G5 com MLA", texto: "A TV LG OLED G5 com tecnologia Micro Lens Array atinge 3.000 nits de brilho, líder absoluta em qualidade.", data: "2026-03" },
      { titulo: "Monitor LG UltraGear 32 OLED", texto: "Monitor gamer OLED de 32 polegadas com 240Hz e 0.03ms de resposta.", data: "2026-02" },
      { titulo: "LG webOS 26 com assistentes IA", texto: "O novo sistema webOS da LG integra assistentes de IA para recomendação personalizada de conteúdo.", data: "2026-01" },
    ],
    dicasManutencao: [
      "TVs LG OLED: ative o pixel refresher mensalmente para prevenir burn-in",
      "Evite deixar imagens estáticas por longos períodos em TVs OLED",
      "Monitores ultrawide: use o OnScreen Control da LG para gerenciar janelas",
      "Atualize o firmware da TV pelo menu Configurações > Suporte",
    ],
    problemasComuns: [
      { problema: "TV LG com som mas sem imagem", solucao: "Pode ser problema na retroiluminação LED. Teste com lanterna próxima à tela — se vir imagem fraca, são os LEDs." },
      { problema: "LG OLED com burn-in", solucao: "Use o Pixel Refresher integrado. Em casos severos, é necessário trocar o painel OLED." },
      { problema: "Smart TV LG lenta", solucao: "Limpe o cache dos apps, desinstale apps não usados e faça um reset de fábrica se necessário." },
    ],
  },
  {
    slug: "apple",
    name: "Apple",
    logoPath: "M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.81-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z",
    color: "#555555",
    description: "A Apple é criadora do iPhone, iPad, Mac e Apple Watch. Seus produtos são conhecidos pela integração entre hardware e software, design premium e ecossistema fechado.",
    fundacao: "1976",
    sede: "Cupertino, Califórnia, EUA",
    servicos: ["Conserto de MacBook", "Reparo de iMac", "Formatação de Mac", "Upgrade de SSD MacBook Pro", "Reparo de tela MacBook"],
    novidades: [
      { titulo: "MacBook Pro M5 Max", texto: "O novo MacBook Pro com chip M5 Max traz 18 núcleos de CPU e 40 de GPU, ideal para edição de vídeo 8K.", data: "2026-03" },
      { titulo: "Apple Intelligence expandida", texto: "A Apple Intelligence agora oferece resumo de emails, transcrição de reuniões e geração de imagens nativas.", data: "2026-02" },
      { titulo: "macOS 17 Sequoia", texto: "O macOS 17 traz integração profunda com iPhone, espelhamento de tela e novos recursos de produtividade.", data: "2026-01" },
    ],
    dicasManutencao: [
      "MacBooks com M1+ não precisam de antivírus, mas mantenha o sistema atualizado",
      "Use o Utilitário de Disco para verificar erros no SSD periodicamente",
      "Limpe a tela Retina apenas com pano de microfibra levemente úmido",
      "Faça backup com Time Machine regularmente — é a melhor proteção contra perda de dados",
    ],
    problemasComuns: [
      { problema: "MacBook não carrega", solucao: "Resete o SMC (Intel) ou faça shutdown completo por 30s (Apple Silicon). Verifique o cabo MagSafe/USB-C." },
      { problema: "Mac lento após atualização", solucao: "Limpe caches com o Utilitário de Disco, verifique o Monitor de Atividade para processos pesados." },
      { problema: "Teclado butterfly com teclas travadas", solucao: "Modelos 2016-2019 tinham teclado butterfly problemático. Apple faz troca gratuita em alguns casos." },
    ],
  },
  {
    slug: "positivo",
    name: "Positivo",
    logoPath: "M4 4h16v16H4V4zm2 2v12h12V6H6zm3 3h6v2H9V9zm0 4h6v2H9v-2z",
    color: "#00A651",
    description: "A Positivo é a maior fabricante brasileira de computadores. Seus modelos são populares pelo preço acessível e presença em escolas e programas governamentais.",
    fundacao: "1989",
    sede: "Curitiba, Paraná, Brasil",
    servicos: ["Conserto de notebook Positivo", "Upgrade de RAM e SSD Positivo", "Formatação de Positivo Motion", "Troca de tela Positivo", "Reparo de teclado Positivo"],
    novidades: [
      { titulo: "Positivo Motion C com Intel N-Series", texto: "O novo Motion C traz processadores Intel N-Series com melhor eficiência energética e tela Full HD IPS.", data: "2026-03" },
      { titulo: "Positivo amplia linha empresarial", texto: "A Positivo lançou a linha Master para empresas com gerenciamento remoto e garantia on-site.", data: "2026-02" },
      { titulo: "Tablets Positivo para educação", texto: "Novos tablets educacionais com conteúdo interativo e proteção contra quedas para uso escolar.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Positivo Motion: upgrade para SSD é essencial — vem com eMMC lento de fábrica",
      "Adicione RAM se o modelo permite — muitos vêm com apenas 4GB soldado",
      "Mantenha o Windows limpo de programas desnecessários de fábrica (bloatware)",
      "Use um cooler externo em modelos compactos para evitar throttling",
    ],
    problemasComuns: [
      { problema: "Positivo muito lento de fábrica", solucao: "O armazenamento eMMC é muito lento. Instalar um SSD SATA muda completamente a experiência." },
      { problema: "Positivo não reconhece Wi-Fi", solucao: "Atualize o driver Wi-Fi manualmente pelo site da Positivo. O Windows Update nem sempre encontra o correto." },
      { problema: "Tela do Positivo com baixa resolução", solucao: "Muitos modelos vêm com tela HD (1366x768). Não há upgrade possível, mas um monitor externo resolve." },
    ],
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    logoPath: "M3 3h8v8H3V3zm10 0h8v8h-8V3zM3 13h8v8H3v-8zm10 0h8v8h-8v-8z",
    color: "#00A4EF",
    description: "A Microsoft é a criadora do Windows, Office 365, Xbox e Surface. O Windows é o sistema operacional mais usado no mundo e o Office é padrão em empresas.",
    fundacao: "1975",
    sede: "Redmond, Washington, EUA",
    servicos: ["Instalação de Windows 11", "Configuração de Office 365", "Formatação com Windows original", "Ativação de licença Microsoft", "Suporte para Microsoft Surface"],
    novidades: [
      { titulo: "Windows 12 anunciado para 2026", texto: "A Microsoft confirmou o Windows 12 com interface redesenhada, IA Copilot integrada ao sistema e requisitos de TPM 3.0.", data: "2026-03" },
      { titulo: "Microsoft 365 Copilot para todos", texto: "O Copilot agora está disponível para assinantes pessoais do Microsoft 365, com IA para Word, Excel e PowerPoint.", data: "2026-02" },
      { titulo: "Surface Pro 11 com Snapdragon X Elite", texto: "O novo Surface Pro 11 traz processador ARM com bateria de 19 horas e compatibilidade com apps x86.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Mantenha o Windows Update ativado — patches de segurança são críticos",
      "Use o Windows Security (Defender) — é suficiente para maioria dos usuários",
      "Limpe arquivos temporários regularmente com a Limpeza de Disco",
      "Crie um ponto de restauração antes de instalar programas desconhecidos",
    ],
    problemasComuns: [
      { problema: "Windows 11 lento após atualização", solucao: "Desative efeitos visuais, limpe arquivos temporários e verifique programas de inicialização." },
      { problema: "Office 365 não ativa", solucao: "Faça logout e login novamente com sua conta Microsoft. Se persistir, use a ferramenta de reparo do Office." },
      { problema: "Tela azul frequente no Windows", solucao: "Verifique drivers de vídeo e RAM. Use o Verificador de Memória do Windows para testar a RAM." },
    ],
  },
  {
    slug: "intel",
    name: "Intel",
    logoPath: "M4 8h3v8H4V8zm5-2h3v12H9V6zm5 4h3v4h-3v-4zm4-3h2v10h-2V7z",
    color: "#0071C5",
    description: "A Intel é a maior fabricante de processadores para PCs e servidores. Seus chips Core i3, i5, i7 e i9 equipam a maioria dos computadores do mercado.",
    fundacao: "1968",
    sede: "Santa Clara, Califórnia, EUA",
    servicos: ["Diagnóstico de processador Intel", "Upgrade de PC com Intel", "Montagem de PC Intel", "Configuração de PC Intel Core", "Teste de estabilidade Intel"],
    novidades: [
      { titulo: "Intel Core Ultra 200V (Arrow Lake)", texto: "A nova arquitetura Arrow Lake traz até 24 núcleos e NPU integrada para IA, com 15% mais desempenho por watt.", data: "2026-03" },
      { titulo: "Intel Arc B-Series GPU", texto: "As GPUs Intel Arc B580 e B770 competem com NVIDIA e AMD no segmento intermediário.", data: "2026-02" },
      { titulo: "Intel 18A em produção", texto: "O processo de fabricação Intel 18A (1.8nm) entrou em produção, prometendo chips mais rápidos e eficientes.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Monitore temperaturas com Intel XTU ou HWMonitor — acima de 90°C é crítico",
      "Troque a pasta térmica a cada 2 anos para manter temperaturas ideais",
      "Processadores Intel K/KF precisam de cooler dedicado — não use o cooler box",
      "Atualize o Intel ME (Management Engine) pela fabricante da placa-mãe",
    ],
    problemasComuns: [
      { problema: "PC com Intel travando", solucao: "Verifique temperaturas e fonte de alimentação. Processadores Intel 13ª/14ª gen tiveram bug de degradação — atualize o BIOS." },
      { problema: "Intel UHD Graphics com desempenho ruim", solucao: "Atualize os drivers pela Intel Arc Control. Para jogos, considere uma GPU dedicada." },
      { problema: "PC Intel não liga após upgrade", solucao: "Verifique compatibilidade do processador com a placa-mãe. Pode ser necessário atualizar a BIOS antes." },
    ],
  },
  {
    slug: "amd",
    name: "AMD",
    logoPath: "M2 17L8.5 5h3.2l1.8 3.4L15.3 5h3.2L22 17h-3.5l-3-6.5L12 17h-2.5L6 10.5 3.5 17H2z",
    color: "#ED1C24",
    description: "A AMD é a principal concorrente da Intel em processadores (Ryzen) e da NVIDIA em placas de vídeo (Radeon). Seus chips Ryzen revolucionaram o mercado de desktops e notebooks.",
    fundacao: "1969",
    sede: "Santa Clara, Califórnia, EUA",
    servicos: ["Montagem de PC AMD Ryzen", "Upgrade com processador AMD", "Configuração de Radeon RX", "Diagnóstico de PC AMD", "Otimização de desempenho AMD"],
    novidades: [
      { titulo: "AMD Ryzen 9000X3D com 3D V-Cache", texto: "Os novos Ryzen 9000X3D trazem cache 3D de 144MB, dominando benchmarks de jogos.", data: "2026-03" },
      { titulo: "Radeon RX 9070 XT lançada", texto: "A RX 9070 XT compete com a RTX 5070 por preço menor, com ray tracing melhorado e FSR 4.", data: "2026-02" },
      { titulo: "AMD EPYC Turin para servidores", texto: "Os processadores EPYC com até 192 núcleos dominam o mercado de data centers e cloud.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Ryzen se beneficia muito de RAM em dual channel — use sempre dois pentes",
      "Ative PBO (Precision Boost Overdrive) na BIOS para máximo desempenho",
      "Atualize os drivers Radeon pelo AMD Adrenalin para melhor desempenho em jogos",
      "Monitore temperaturas com Ryzen Master — o limite seguro é 95°C",
    ],
    problemasComuns: [
      { problema: "PC AMD reiniciando sozinho", solucao: "Verifique se o PBO está configurado corretamente e se a fonte suporta a potência. Atualize a BIOS." },
      { problema: "Radeon com artefatos visuais", solucao: "Atualize os drivers AMD Adrenalin. Se persistir, pode ser problema térmico na GPU — limpe os coolers." },
      { problema: "RAM não funciona em dual channel com AMD", solucao: "Coloque os pentes nos slots corretos (geralmente A2 e B2). Verifique a QVL da placa-mãe." },
    ],
  },
  {
    slug: "nvidia",
    name: "NVIDIA",
    logoPath: "M2 12c0-1.5.4-3 1.2-4.3C6.5 4.7 12 3 12 3s-2.2 2.5-2.2 5.3c0 1.3.5 2.5 1.3 3.4.5-.8 1.2-1.5 2-2 .9-.5 1.8-.7 2.8-.7 2.8 0 5.1 2.3 5.1 5.1 0 1.7-.8 3.2-2.1 4.2-.3-1.5-1.1-2.8-2.3-3.7-1.1-.8-2.4-1.3-3.8-1.3-2.4 0-4.4 1.6-5 3.8C4.5 16 2 14.2 2 12z",
    color: "#76B900",
    description: "A NVIDIA é líder absoluta em GPUs (GeForce RTX) e tecnologias de IA. Suas placas de vídeo são indispensáveis para gamers, designers e profissionais de machine learning.",
    fundacao: "1993",
    sede: "Santa Clara, Califórnia, EUA",
    servicos: ["Instalação de placa de vídeo NVIDIA", "Configuração de driver GeForce", "Montagem de PC com RTX", "Diagnóstico de GPU NVIDIA", "Reparo térmico de GPU NVIDIA"],
    novidades: [
      { titulo: "GeForce RTX 5090 e 5080 lançadas", texto: "As novas RTX 5090 e 5080 trazem DLSS 4 com Multi Frame Generation, gerando até 4 frames por frame renderizado.", data: "2026-03" },
      { titulo: "NVIDIA AI Workstation", texto: "A NVIDIA lançou estações de trabalho com GPU dedicada para treinar modelos de IA localmente.", data: "2026-02" },
      { titulo: "GeForce NOW com RTX 5080 na nuvem", texto: "O serviço de cloud gaming da NVIDIA agora oferece GPUs RTX 5080 para jogos em 4K 120fps.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Mantenha o GeForce Experience atualizado para drivers Game Ready",
      "Monitore temperaturas com GPU-Z — acima de 85°C indica necessidade de manutenção",
      "Limpe os coolers da GPU a cada 6 meses — poeira reduz desempenho drasticamente",
      "Use DLSS sempre que disponível — melhora FPS sem perder qualidade visual",
    ],
    problemasComuns: [
      { problema: "GPU NVIDIA com artefatos", solucao: "Pode ser superaquecimento ou degradação do chip. Limpe os coolers, troque a pasta térmica. Em casos graves, reflow." },
      { problema: "Driver NVIDIA causando tela preta", solucao: "Inicie em Modo Seguro e use DDU (Display Driver Uninstaller) para limpar o driver antigo, depois reinstale." },
      { problema: "PC não reconhece placa de vídeo NVIDIA", solucao: "Verifique se a GPU está bem encaixada no slot PCIe e se os cabos de energia estão conectados." },
    ],
  },
  {
    slug: "kingston",
    name: "Kingston",
    logoPath: "M2 8h20v8H2V8zm2 2v4h4v-4H4zm6 0v4h4v-4h-4zm6 0v4h4v-4h-4z",
    color: "#E4002B",
    description: "A Kingston é a maior fabricante de memória RAM e SSDs do mundo. Seus produtos são conhecidos pela confiabilidade e excelente custo-benefício.",
    fundacao: "1987",
    sede: "Fountain Valley, Califórnia, EUA",
    servicos: ["Upgrade com SSD Kingston", "Instalação de RAM Kingston", "Diagnóstico de memória Kingston", "Upgrade Kingston FURY para gamers", "Recuperação de pen drive Kingston"],
    novidades: [
      { titulo: "Kingston FURY Renegade DDR5-8000", texto: "A nova RAM DDR5-8000 com iluminação RGB atinge velocidades recordes para overclockers e gamers.", data: "2026-03" },
      { titulo: "SSD Kingston KC4000 NVMe", texto: "O KC4000 atinge 7.300MB/s de leitura, competindo diretamente com o Samsung 990 PRO.", data: "2026-02" },
      { titulo: "Kingston IronKey com criptografia quântica", texto: "Pen drives ultra-seguros com proteção contra ataques de computação quântica para empresas.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o Kingston SSD Manager para monitorar saúde e atualizar firmware do SSD",
      "RAM Kingston FURY: ative o perfil XMP/EXPO na BIOS para velocidade máxima",
      "Pen drives Kingston: use 'Remover hardware com segurança' para evitar corrupção",
      "Verifique a compatibilidade da RAM no site da Kingston antes de comprar",
    ],
    problemasComuns: [
      { problema: "SSD Kingston não detectado", solucao: "Verifique se está bem encaixado no slot M.2/SATA. Teste em outro slot ou computador." },
      { problema: "RAM Kingston não funciona na velocidade anunciada", solucao: "Ative o perfil XMP na BIOS. Sem XMP, a RAM roda na velocidade padrão JEDEC (geralmente 4800MHz)." },
      { problema: "Pen drive Kingston corrompido", solucao: "Use o chkdsk no Windows ou formate com a Kingston Format Utility. Dados podem ser recuperados com software especializado." },
    ],
  },
  {
    slug: "corsair",
    name: "Corsair",
    logoPath: "M12 2C9.5 2 7.3 3.2 5.8 5.2L12 12l6.2-6.8C16.7 3.2 14.5 2 12 2zM4.5 6.5C3 8.5 2 11.1 2 14c0 4.4 3.6 8 8 8h4c4.4 0 8-3.6 8-8 0-2.9-1-5.5-2.5-7.5L12 14 4.5 6.5z",
    color: "#F1C40F",
    description: "A Corsair é líder em periféricos gamer, memória RAM, fontes de alimentação e gabinetes. Seus produtos são referência em qualidade para entusiastas e overclockers.",
    fundacao: "1994",
    sede: "Milpitas, Califórnia, EUA",
    servicos: ["Montagem de PC com Corsair", "Instalação de RAM Corsair Vengeance", "Configuração de cooler Corsair iCUE", "Upgrade de fonte Corsair", "Setup de periféricos Corsair"],
    novidades: [
      { titulo: "Corsair Xeneon Edge OLED", texto: "Monitor gamer OLED de 27 polegadas com QD-OLED e 240Hz — cores perfeitas e resposta instantânea.", data: "2026-03" },
      { titulo: "Corsair K70 MAX magnético", texto: "Teclado com switches magnéticos ajustáveis, permitindo personalizar o ponto de atuação de cada tecla.", data: "2026-02" },
      { titulo: "Fonte Corsair HX1500i Platinum", texto: "Fonte modular de 1500W com eficiência Platinum, ideal para sistemas com RTX 5090.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o iCUE para gerenciar RGB, monitorar temperaturas e configurar perfis",
      "Fontes Corsair: limpe o filtro de poeira do ventilador semestralmente",
      "RAM Corsair Vengeance: ative XMP para obter a velocidade anunciada",
      "Coolers AIO Corsair: verifique o nível do líquido a cada 3 anos",
    ],
    problemasComuns: [
      { problema: "iCUE não detecta dispositivos", solucao: "Reinstale o iCUE completamente. Verifique se o dispositivo está no USB correto e atualize o firmware." },
      { problema: "Fonte Corsair desligando PC", solucao: "Pode ser sobrecarga. Verifique a potência total do sistema. Teste com outra tomada dedicada." },
      { problema: "Cooler AIO Corsair com barulho", solucao: "Bolhas de ar no sistema. Posicione o radiador acima da bomba. Se persistir, pode ser desgaste da bomba." },
    ],
  },
  {
    slug: "tp-link",
    name: "TP-Link",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 4c3.31 0 6 2.69 6 6s-2.69 6-6 6-6-2.69-6-6 2.69-6 6-6zm0 2c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4zm0 2c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2z",
    color: "#4ACBD6",
    description: "A TP-Link é líder mundial em roteadores e equipamentos de rede. Seus produtos oferecem excelente custo-benefício para redes domésticas e empresariais.",
    fundacao: "1996",
    sede: "Shenzhen, China",
    servicos: ["Configuração de roteador TP-Link", "Instalação de rede mesh TP-Link Deco", "Configuração de switch TP-Link", "Instalação de câmera TP-Link Tapo", "Otimização de Wi-Fi TP-Link"],
    novidades: [
      { titulo: "TP-Link Deco BE85 Wi-Fi 7", texto: "O sistema mesh Wi-Fi 7 com velocidade de até 22Gbps e cobertura de 700m².", data: "2026-03" },
      { titulo: "Câmeras Tapo com IA", texto: "As câmeras de segurança Tapo agora detectam pessoas, veículos e animais com IA local.", data: "2026-02" },
      { titulo: "TP-Link Omada Cloud SDN", texto: "Plataforma de gerenciamento de rede em nuvem para pequenas e médias empresas.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Atualize o firmware do roteador mensalmente pelo app Tether",
      "Posicione o roteador no centro da casa, elevado, longe de espelhos e metal",
      "Use canais Wi-Fi menos congestionados — o app Tether mostra a análise",
      "Sistema mesh Deco: coloque os nós a no máximo 10m de distância entre si",
    ],
    problemasComuns: [
      { problema: "Wi-Fi TP-Link caindo toda hora", solucao: "Atualize o firmware, mude o canal Wi-Fi para 5GHz e verifique interferência de outros dispositivos." },
      { problema: "Roteador TP-Link não configura", solucao: "Acesse 192.168.0.1 pelo navegador com cabo ethernet. Use o app Tether para configuração guiada." },
      { problema: "Mesh Deco sem cobertura uniforme", solucao: "Reposicione os nós — não devem ter paredes grossas ou metal entre eles. Máximo 10m de distância." },
    ],
  },
  {
    slug: "intelbras",
    name: "Intelbras",
    logoPath: "M3 6h18v12H3V6zm2 2v8h14V8H5zm2 2h3v2H7v-2zm5 0h5v1h-5v-1zm0 2h5v1h-5v-1zm-5 2h10v1H7v-1z",
    color: "#00A859",
    description: "A Intelbras é a maior fabricante brasileira de câmeras de segurança, DVRs, interfones e equipamentos de rede. Líder absoluta em CFTV no Brasil.",
    fundacao: "1976",
    sede: "São José, Santa Catarina, Brasil",
    servicos: ["Instalação de câmera Intelbras", "Configuração de DVR Intelbras", "Reparo de sistema CFTV Intelbras", "Instalação de interfone Intelbras", "Configuração de roteador Intelbras"],
    novidades: [
      { titulo: "Intelbras iM7 Full Color com IA", texto: "Câmera com imagem colorida 24h e detecção inteligente de invasão por IA.", data: "2026-03" },
      { titulo: "DVR Intelbras MHDX 5200 4K", texto: "O novo DVR suporta até 32 câmeras em 4K com compressão H.265+ e acesso remoto Cloud.", data: "2026-02" },
      { titulo: "Intelbras Wi-Fi 6 Mesh", texto: "A linha Twibi Giga+ agora com Wi-Fi 6 oferece cobertura mesh para toda a casa.", data: "2026-01" },
    ],
    dicasManutencao: [
      "DVRs Intelbras: verifique o HD a cada 6 meses — HDs de vigilância têm vida útil de 3-5 anos",
      "Câmeras externas: limpe a lente mensalmente para imagem nítida",
      "Atualize o firmware pelo Intelbras Cloud pelo app",
      "Use nobreak no DVR — quedas de energia corrompem o HD de vigilância",
    ],
    problemasComuns: [
      { problema: "DVR Intelbras sem imagem", solucao: "Verifique os cabos BNC e a alimentação das câmeras. Teste cada câmera individualmente." },
      { problema: "Intelbras Cloud não conecta", solucao: "Verifique se o DVR está conectado à internet. Atualize o firmware e reconfigure o Cloud no app." },
      { problema: "Câmera Intelbras com imagem escura à noite", solucao: "Verifique se os LEDs infravermelhos estão funcionando. Câmeras Full Color precisam de iluminação mínima." },
    ],
  },
  {
    slug: "motorola",
    name: "Motorola",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 2c1.93 0 3.68.78 4.95 2.05L12 12V4zm-6.95 4.05C6.32 6.78 8.07 4 10 4v8L5.05 6.05zM4 12c0-1.93.78-3.68 2.05-4.95L12 12H4zm8 8c-1.93 0-3.68-.78-4.95-2.05L12 12v8zm6.95-4.05C17.68 17.22 15.93 20 14 20v-8l4.95 5.95zM20 12c0 1.93-.78 3.68-2.05 4.95L12 12h8z",
    color: "#5C2D91",
    description: "A Motorola, agora parte da Lenovo, é uma das marcas de celular mais populares no Brasil. A linha Moto G oferece excelente custo-benefício e a Moto Edge traz recursos premium.",
    fundacao: "1928",
    sede: "Chicago, Illinois, EUA",
    servicos: ["Conserto de celular Motorola", "Troca de tela Moto G", "Reparo de Motorola Edge", "Formatação de Motorola", "Troca de bateria Motorola"],
    novidades: [
      { titulo: "Moto G85 com tela curva AMOLED", texto: "O Moto G85 traz tela curva AMOLED de 120Hz, câmera de 50MP e carregamento de 68W.", data: "2026-03" },
      { titulo: "Motorola Edge 60 Ultra", texto: "Topo de linha com Snapdragon 8 Gen 4, câmera de 200MP e zoom óptico de 5x.", data: "2026-02" },
      { titulo: "Moto AI Assistant", texto: "A Motorola integrou IA generativa ao sistema, com transcrição de ligações e resumo de notificações.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o Moto Care para diagnósticos e suporte oficial",
      "Mantenha o sistema atualizado — Motorola libera patches de segurança mensais",
      "Evite carregadores de terceiros — use o TurboPower original",
      "Limpe a porta USB-C regularmente com escova antiestática",
    ],
    problemasComuns: [
      { problema: "Moto G não carrega", solucao: "Limpe a porta USB-C com cuidado. Teste com outro cabo. Se não resolver, pode ser problema no conector." },
      { problema: "Tela do Motorola com ghost touch", solucao: "Pode ser película de baixa qualidade causando interferência. Remova e teste. Se persistir, problema no digitalizador." },
      { problema: "Motorola lento após atualização", solucao: "Limpe o cache de apps (Configurações > Apps). Em último caso, faça reset de fábrica com backup." },
    ],
  },
  {
    slug: "xiaomi",
    name: "Xiaomi",
    logoPath: "M4 4h16v16H4V4zm2 2v12h12V6H6zm4 3h4c.55 0 1 .45 1 1v4c0 .55-.45 1-1 1h-4c-.55 0-1-.45-1-1v-4c0-.55.45-1 1-1z",
    color: "#FF6700",
    description: "A Xiaomi é a terceira maior fabricante de smartphones do mundo. Além de celulares, fabrica notebooks (Mi Notebook), roteadores, smartbands e ecossistema IoT.",
    fundacao: "2010",
    sede: "Pequim, China",
    servicos: ["Conserto de celular Xiaomi", "Troca de tela Xiaomi Redmi", "Reparo de Xiaomi POCO", "Formatação de Xiaomi", "Desbloqueio de bootloader Xiaomi"],
    novidades: [
      { titulo: "Xiaomi 16 Ultra com câmera Leica", texto: "O Xiaomi 16 Ultra traz câmera co-desenvolvida com Leica, sensor de 1 polegada e zoom óptico 10x.", data: "2026-03" },
      { titulo: "POCO F7 — Performance acessível", texto: "O POCO F7 com Snapdragon 8s Gen 4 entrega desempenho flagship por metade do preço.", data: "2026-02" },
      { titulo: "Xiaomi HyperOS 3.0", texto: "O novo sistema operacional da Xiaomi traz integração com IoT, controle de dispositivos por IA e interface redesenhada.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Xiaomi: desative atualizações de apps da Mi Store se não usa — consome bateria",
      "Ative o modo de proteção de bateria para limitar a carga em 80%",
      "POCO: monitore a temperatura em jogos — o app Game Turbo ajuda",
      "Desbloqueie o bootloader apenas se souber o que está fazendo — anula a garantia",
    ],
    problemasComuns: [
      { problema: "Xiaomi com MIUI travando", solucao: "Limpe o cache do sistema (Configurações > Sobre > Limpar dados). Atualize para a versão mais recente do HyperOS." },
      { problema: "Redmi sem sinal de celular", solucao: "Ative e desative o modo avião. Se persistir, verifique a bandeja do SIM e faça reset de rede." },
      { problema: "Xiaomi com anúncios no sistema", solucao: "Desative 'Receber recomendações' em cada app da Xiaomi (Segurança, Mi Browser, Temas, etc.)." },
    ],
  },
  {
    slug: "sony",
    name: "Sony",
    logoPath: "M2 9h3l1.5 3L8 9h3v6H8.5v-3.5L7 14.5h-1L4.5 11.5V15H2V9zm11 0h3c1.66 0 3 1.34 3 3s-1.34 3-3 3h-3V9zm2.5 2v2h.5c.55 0 1-.45 1-1s-.45-1-1-1h-.5zM21 9h1v6h-1V9z",
    color: "#000000",
    description: "A Sony é gigante em entretenimento, conhecida pelo PlayStation, TVs Bravia, fones WH-1000XM e câmeras Alpha. Seus sensores de câmera equipam smartphones de diversas marcas.",
    fundacao: "1946",
    sede: "Tóquio, Japão",
    servicos: ["Conserto de PlayStation Sony", "Reparo de TV Sony Bravia", "Manutenção de PS5", "Conserto de fone Sony WH-1000XM", "Configuração de home theater Sony"],
    novidades: [
      { titulo: "PlayStation 5 Pro Enhanced", texto: "A versão Enhanced do PS5 Pro traz SSD de 2TB, ray tracing melhorado e suporte a 8K.", data: "2026-03" },
      { titulo: "Sony Bravia 9 Mini-LED", texto: "A TV Bravia 9 com Mini-LED e XR Processor oferece contraste excepcional e Google TV integrada.", data: "2026-02" },
      { titulo: "Sony WH-1000XM6", texto: "O melhor fone com cancelamento de ruído do mercado agora tem 40 horas de bateria e áudio espacial.", data: "2026-01" },
    ],
    dicasManutencao: [
      "PS5: limpe os filtros de poeira a cada 3 meses — acesso fácil pela tampa lateral",
      "TVs Bravia: calibre as cores com o modo Filmmaker para melhor imagem",
      "Fones WH-1000XM: não dobre as almofadas — guarde no case original",
      "PlayStation: use SSD NVMe M.2 com heatsink para expandir o armazenamento",
    ],
    problemasComuns: [
      { problema: "PS5 desligando sozinho", solucao: "Pode ser superaquecimento — limpe as saídas de ar e o interior. Se persistir, troque a pasta térmica do APU." },
      { problema: "TV Sony sem som pelo HDMI ARC", solucao: "Ative HDMI CEC nas configurações. Teste com outro cabo HDMI. Atualize o firmware da TV." },
      { problema: "Fone Sony não emparelha", solucao: "Faça reset: segure power + noise canceling por 7 segundos. Depois emparelhe novamente." },
    ],
  },
  {
    slug: "razer",
    name: "Razer",
    logoPath: "M2 12c3-6 5-8 10-10 0 4-2 7-4 9 4-3 8-4 14-3-3 5-7 8-12 10 1-3 3-7 4-9-4 2-8 3-12 3z",
    color: "#00FF00",
    description: "A Razer é referência mundial em periféricos gamer: mouses, teclados, headsets e notebooks gaming. Conhecida pelo ecossistema Chroma RGB e pela qualidade premium dos seus produtos para eSports.",
    fundacao: "2005",
    sede: "Irvine, Califórnia, EUA",
    servicos: ["Reparo de notebook Razer Blade", "Configuração de periféricos Razer", "Instalação de Razer Synapse", "Manutenção de mouse Razer", "Troca de switches de teclado Razer"],
    novidades: [
      { titulo: "Razer Blade 18 com RTX 5080", texto: "O notebook gamer mais fino de 18 polegadas agora com RTX 5080 e tela Mini-LED de 240Hz.", data: "2026-03" },
      { titulo: "Razer Viper V3 Pro Wireless", texto: "Mouse gamer com sensor Focus Pro 36K, peso de 54g e polling rate de 8000Hz via HyperPolling.", data: "2026-02" },
      { titulo: "Razer BlackWidow V5 com switches ópticos", texto: "Teclado mecânico com switches ópticos Gen 3, atuação em 0.1mm e vida útil de 150 milhões de cliques.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Razer Blade: limpe os coolers a cada 3 meses — superaquece facilmente em jogos pesados",
      "Use o Razer Synapse para gerenciar perfis, RGB e atualizar firmware dos periféricos",
      "Mouse Razer: limpe os patins (feet) e o sensor regularmente para tracking perfeito",
      "Teclados mecânicos Razer: remova keycaps e limpe com ar comprimido semestralmente",
    ],
    problemasComuns: [
      { problema: "Razer Blade superaquecendo", solucao: "Limpe os ventiladores internos, troque a pasta térmica e use um cooler pad. O perfil 'Balanced' no Synapse ajuda a reduzir temperaturas." },
      { problema: "Mouse Razer com double click", solucao: "Pode ser desgaste do switch. Em mouses com switches ópticos, atualize o firmware. Em mecânicos, troca do switch resolve." },
      { problema: "Razer Synapse não reconhece dispositivo", solucao: "Desinstale completamente o Synapse, reinicie, reinstale a versão mais recente e conecte o dispositivo em outra porta USB." },
    ],
  },
  {
    slug: "logitech",
    name: "Logitech",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c3.87 0 7 3.13 7 7s-3.13 7-7 7-7-3.13-7-7 3.13-7 7-7zm0 2.5a4.5 4.5 0 100 9 4.5 4.5 0 000-9z",
    color: "#00B8FC",
    description: "A Logitech é líder global em periféricos: mouses, teclados, webcams, headsets e caixas de som. A linha MX Master é referência em produtividade e a linha G Pro domina o cenário competitivo.",
    fundacao: "1981",
    sede: "Lausanne, Suíça",
    servicos: ["Configuração de periféricos Logitech", "Instalação de Logitech Options+", "Reparo de mouse Logitech", "Configuração de webcam Logitech", "Setup de headset Logitech"],
    novidades: [
      { titulo: "Logitech MX Master 4", texto: "O mouse de produtividade mais icônico do mercado agora com sensor 8K, bateria de 90 dias e MagSpeed Scroll aprimorado.", data: "2026-03" },
      { titulo: "Logitech G Pro X 2 Superlight", texto: "Mouse gamer de 57g com sensor HERO 2 de 44K DPI e LIGHTFORCE switches híbridos.", data: "2026-02" },
      { titulo: "Logitech Brio 4K Pro", texto: "Webcam profissional com HDR, enquadramento automático por IA e microfone com cancelamento de ruído.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o Logi Options+ para personalizar botões, gestos e atualizar firmware",
      "MX Master: limpe a roda de scroll magnética com pano de microfibra para manter a precisão",
      "Webcams Logitech: limpe a lente semanalmente para imagem nítida em reuniões",
      "Receptores Unifying: guarde o nano receptor no compartimento do mouse quando não usar",
    ],
    problemasComuns: [
      { problema: "Mouse Logitech com lag no Bluetooth", solucao: "Troque para o receptor Logi Bolt/Unifying — é mais estável. Ou atualize o firmware pelo Options+." },
      { problema: "Logitech MX Keys não conecta em 3 dispositivos", solucao: "Segure o botão do canal por 3 segundos para entrar em modo de pareamento. Cada canal é independente." },
      { problema: "Webcam Logitech com imagem escura", solucao: "Ajuste o balanço de branco e exposição pelo Logi Tune. Posicione uma fonte de luz à frente, nunca atrás." },
    ],
  },
  {
    slug: "western-digital",
    name: "Western Digital",
    logoPath: "M2 8h4l2 8 2-8h4l2 8 2-8h4v8h-3l-2-6-2 6h-4l-2-6-2 6H2V8z",
    color: "#005EB8",
    description: "A Western Digital (WD) é uma das maiores fabricantes de discos rígidos e SSDs do mundo. As linhas WD Blue, Black e Red são referência para uso doméstico, gamer e NAS respectivamente.",
    fundacao: "1970",
    sede: "San José, Califórnia, EUA",
    servicos: ["Instalação de HD WD", "Upgrade com SSD WD Blue", "Recuperação de dados WD", "Configuração de NAS com WD Red", "Diagnóstico de HD WD"],
    novidades: [
      { titulo: "WD Black SN850X com 8TB", texto: "O SSD NVMe gamer agora disponível em 8TB com leitura de 7.300MB/s para quem precisa de espaço e velocidade.", data: "2026-03" },
      { titulo: "WD Red Pro para NAS com CMR", texto: "Discos de 24TB com gravação CMR, otimizados para NAS com 8+ baias e uso 24/7.", data: "2026-02" },
      { titulo: "WD Elements Portátil USB-C", texto: "HD externo redesenhado com USB-C nativo e velocidades de até 130MB/s em modelos de até 5TB.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o WD Dashboard para monitorar a saúde do SSD e atualizar firmware",
      "HDs WD: evite mover o computador com o HD em uso — cabeçotes são frágeis",
      "WD Red para NAS: configure SMART monitoring para alertas antecipados de falha",
      "Faça backup 3-2-1: 3 cópias, 2 mídias diferentes, 1 fora do local",
    ],
    problemasComuns: [
      { problema: "HD WD fazendo barulho de clique", solucao: "Cliques repetitivos indicam falha iminente nas cabeças de leitura. Faça backup IMEDIATO e substitua o disco." },
      { problema: "SSD WD Blue não detectado", solucao: "Verifique se está no slot M.2 correto (SATA vs NVMe). Atualize a BIOS e verifique no Gerenciador de Disco." },
      { problema: "HD externo WD Elements não reconhecido", solucao: "Teste em outra porta USB e outro cabo. Se piscar e desconectar, pode ser problema na placa controladora do case." },
    ],
  },
  {
    slug: "seagate",
    name: "Seagate",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 5h4v3h3l-5 5-5-5h3V7zm-4 8h12v2H6v-2z",
    color: "#6EBE49",
    description: "A Seagate é uma das maiores fabricantes de HDs e SSDs do mundo. Conhecida pelos HDs Barracuda para desktops e IronWolf para NAS, também produz SSDs FireCuda para gamers.",
    fundacao: "1978",
    sede: "Fremont, Califórnia, EUA",
    servicos: ["Instalação de HD Seagate", "Upgrade com SSD Seagate FireCuda", "Recuperação de dados Seagate", "Configuração de NAS com IronWolf", "Diagnóstico de HD Seagate"],
    novidades: [
      { titulo: "Seagate FireCuda 540 PCIe 5.0", texto: "SSD NVMe com velocidade de leitura de 10.000MB/s, o mais rápido da Seagate para gamers e criadores.", data: "2026-03" },
      { titulo: "Seagate IronWolf Pro 24TB", texto: "HD de 24TB para NAS com sensores de vibração rotacional e 5 anos de garantia para uso contínuo.", data: "2026-02" },
      { titulo: "Seagate Barracuda com HAMR", texto: "Nova tecnologia HAMR permite discos de até 30TB+ para armazenamento massivo de dados.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o SeaTools para diagnóstico gratuito de saúde do HD — detecta erros antes da falha",
      "HDs Seagate Barracuda: ideal para armazenamento, mas não para sistema operacional — use SSD para o SO",
      "IronWolf: configure Health Management no NAS Synology/QNAP para monitoramento contínuo",
      "Nunca desligue o computador pela tomada — desligamento abrupto corrompe setores do HD",
    ],
    problemasComuns: [
      { problema: "HD Seagate Barracuda lento", solucao: "Execute o SeaTools para verificar setores defeituosos. Se tiver muitos reallocated sectors, substitua urgente." },
      { problema: "Seagate Expansion não aparece no PC", solucao: "Verifique no Gerenciamento de Disco se aparece como 'Não alocado'. Pode precisar ser inicializado e formatado." },
      { problema: "HD Seagate com erro SMART", solucao: "Erros SMART são alertas de falha iminente. Faça backup imediato e substitua o disco — não ignore alertas SMART." },
    ],
  },
  {
    slug: "msi",
    name: "MSI",
    logoPath: "M4 4h16v2l-3 3v6l3 3v2H4v-2l3-3V9L4 6V4zm6 6v4h4v-4h-4z",
    color: "#FF0000",
    description: "A MSI (Micro-Star International) é uma das maiores fabricantes de placas-mãe, placas de vídeo e notebooks gamer do mundo. A linha Stealth, Raider e Titan são referência em performance gaming.",
    fundacao: "1986",
    sede: "Taipei, Taiwan",
    servicos: ["Conserto de notebook MSI", "Reparo de placa de vídeo MSI", "Upgrade de notebook MSI Stealth", "Configuração de placa-mãe MSI", "Manutenção térmica MSI"],
    novidades: [
      { titulo: "MSI Titan 18 HX com RTX 5090", texto: "O notebook gamer mais poderoso do mercado com RTX 5090, i9-15900HX, tela Mini-LED 4K 120Hz e 128GB RAM.", data: "2026-03" },
      { titulo: "Placa-mãe MSI MEG Z890 ACE", texto: "Placa top para Intel Arrow Lake com Wi-Fi 7, Thunderbolt 5 e VRM de 24+2 fases.", data: "2026-02" },
      { titulo: "MSI MAG 274QRF QD-OLED", texto: "Monitor gamer QD-OLED de 27 polegadas com 360Hz, 0.03ms e HDR True Black 400.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Notebooks MSI: use o MSI Center para controlar perfis de desempenho e coolers",
      "Placas de vídeo MSI: atualize a BIOS da GPU apenas quando necessário e com versão oficial",
      "MSI Afterburner é essencial para monitorar temperaturas e ajustar curva de ventilação",
      "Notebooks gamer MSI: troque a pasta térmica a cada 1-2 anos — esquentam muito",
    ],
    problemasComuns: [
      { problema: "MSI notebook desligando em jogos", solucao: "Superaquecimento é a causa mais comum. Limpe os coolers, troque pasta térmica e use o modo Extreme Cooling no MSI Center." },
      { problema: "Placa de vídeo MSI com artefatos", solucao: "Atualize drivers via GeForce Experience. Se persistir, verifique temperaturas — pode precisar de reparo térmico (reflow)." },
      { problema: "MSI Dragon Center não funciona", solucao: "Desinstale o Dragon Center e migre para o MSI Center (versão atual). O Dragon Center foi descontinuado." },
    ],
  },
  {
    slug: "gigabyte",
    name: "Gigabyte",
    logoPath: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 4c3.31 0 6 2.69 6 6h-3c0-1.66-1.34-3-3-3V6zm0 2c2.21 0 4 1.79 4 4h-2c0-1.1-.9-2-2-2V8zm0 2c1.1 0 2 .9 2 2h-2v-2z",
    color: "#F37321",
    description: "A Gigabyte é uma das maiores fabricantes de placas-mãe, placas de vídeo e notebooks do mundo. Conhecida pela qualidade das linhas AORUS (gamer) e pela durabilidade Ultra Durable das placas-mãe.",
    fundacao: "1986",
    sede: "Taipei, Taiwan",
    servicos: ["Reparo de placa-mãe Gigabyte", "Configuração de placa de vídeo Gigabyte", "Conserto de notebook Gigabyte AORUS", "Upgrade com placa-mãe Gigabyte", "Diagnóstico de placa Gigabyte"],
    novidades: [
      { titulo: "Gigabyte AORUS Master Z890", texto: "Placa-mãe topo de linha para Intel Arrow Lake com VRM de 22 fases, DDR5-8400 e Thunderbolt 5.", data: "2026-03" },
      { titulo: "Gigabyte RTX 5080 AORUS Master", texto: "Placa de vídeo com cooler de 3 fans, backplate de vapor chamber e LED Matrix personalizado.", data: "2026-02" },
      { titulo: "AORUS 17X notebook gamer", texto: "Notebook com tela MiniLED de 17.3 polegadas, 240Hz, RTX 5070Ti e teclado mecânico Cherry MX.", data: "2026-01" },
    ],
    dicasManutencao: [
      "Use o Gigabyte App Center / Control Center para atualizar BIOS e drivers",
      "Placas-mãe Gigabyte: atualize a BIOS pelo Q-Flash Plus — não precisa de CPU instalada",
      "Placas de vídeo AORUS: configure a curva de ventilação pelo AORUS Engine",
      "Notebooks AORUS: monitore temperaturas pelo Gigabyte Control Center e limpe coolers semestralmente",
    ],
    problemasComuns: [
      { problema: "Placa-mãe Gigabyte sem POST", solucao: "Use os LEDs de diagnóstico (Debug LED) para identificar o componente com problema. Faça CMOS reset retirando a bateria." },
      { problema: "Gigabyte GPU com cooler barulhento", solucao: "Atualize a BIOS da GPU pelo @BIOS. Se persistir, os fans podem precisar de lubrificação ou troca." },
      { problema: "Q-Flash não reconhece pendrive", solucao: "Use pendrive USB 2.0 formatado em FAT32. Renomeie o arquivo BIOS exatamente como o manual indica." },
    ],
  },
];

export function getBrandBySlug(slug: string): BrandInfo | undefined {
  return brandsData.find((b) => b.slug === slug);
}
